### ISSUE TITLE
Move Gremlin plugin back into project

### ISSUE THREAD

**Issue by technige** [technige/py2neo#288]
Move the Gremlin plugin into **py2neo.plugins** from https://github.com/nigelsmall/py2neo-gremlin.

**Comment by sir-wiggles** [comment]
I'm trying to get `py2neo` to work with gremlin.  I have the plugin installed on the server and it works through `curl` but I can't get it to work through `py2nep`. I get the error `GremlinPlugin` not found.

Listing the extensions on the server doesn't show anything.
```
$ curl -s -G http://localhost:7474/db/data/
{
  "extensions" : {
  },
  "node" : "http://localhost:7474/db/data/node",
  "node_index" : "http://localhost:7474/db/data/index/node",
  "relationship_index" : "http://localhost:7474/db/data/index/relationship",
  "extensions_info" : "http://localhost:7474/db/data/ext",
  "relationship_types" : "http://localhost:7474/db/data/relationship/types",
  "batch" : "http://localhost:7474/db/data/batch",
  "cypher" : "http://localhost:7474/db/data/cypher",
  "indexes" : "http://localhost:7474/db/data/schema/index",
  "constraints" : "http://localhost:7474/db/data/schema/constraint",
  "transaction" : "http://localhost:7474/db/data/transaction",
  "node_labels" : "http://localhost:7474/db/data/labels",
  "neo4j_version" : "2.1.7"
} 
```

I've tried hacking around and used the url that I used in the command line, but I either get back 403 "method not allowed" or an empty string back.

Not sure what I'm doing wrong.  Do I need to install a different plugin?  Currently I have https://github.com/neo4j-contrib/gremlin-plugin installed
