### ISSUE TITLE
Resources locked by a failed transaction are not released (automatic rollback)

### ISSUE THREAD

**Issue by guidj** [technige/py2neo#396]
Hi Nigel,

I noticed a behaviour from the package when I attempt to create a Node that violates a unique constraint.
## Problem:

When a transaction attempts to create a resource with a unique constraint, if the transaction fails with a `py2neo.cypher.error.schema.ConstraintViolation` error, any subsequent transactions that attempt to use the resource fail.
## Steps:
1. Create unique constraint on a label, e.g. Person (name)
2. Create a node (Person {name: "John"}) using the `CypherTransaction`
3. Attempt to create a node with the same name: (Person {name: "John"}), py2neo throws a `py2neo.cypher.error.schema.ConstraintViolation`, from Neo4j
4. Attempt to delete the node, it fails with a `SocketTimeoutError`

To prevent the SocketTimeout error, one must rollback the transaction, that's `tx.rollback()`, before attempting step 4.

I'm not sure if this is intentional, so we can control our transactions ourselves. But it leaves the db in an inconsistent state if we don't rollback the transaction.
Maybe for certain cases, like `ConstraintViolation` errors, the transaction could be automatically rolled back. That'd be my suggestion.

**Comment by nigelsmall** [comment]
This sounds more like a server issue than something that should be addressed in a driver. Maybe discuss the issue on the Neo4j mailing list?

**Comment by guidj** [comment]
I tried posting the topic to the neo4j google-group twice, but I can seem to see my post.
I'll keep trying to verify it.

**Comment by optimuspaul** [comment]
I think that ConstraintViolation transactions are automatically rolled back now.  I'm finding a strange issue though when if you try to rollback a transition that threw a ConstraintViolation you get a 404. Using the py2neo transactions as a context manager will raise GraphErrors in those cases now giving errors that don't make a ton of sense.
