### ISSUE TITLE
drop_uniqueness_constraint causes GraphError: HTTP DELETE returned response 500

### ISSUE THREAD

**Issue by cloutiertyler** [technige/py2neo#399]
I have a very simple graph schema which just requires that all nodes with the label "User" have a uniqueness constraint on their "email". During the setUp of my testing I make the following graph call.

```
graph.schema.create_uniqueness_constraint("User", "email")
```

During the tearDown of my testing I do the following.

```
constraints = graph.schema.get_uniqueness_constraints("User")
for constraint in constraints:
    graph.schema.drop_uniqueness_constraint("User", constraint)
```

I have printed to confirm that there is only one constraint for a "User" node and that the constraint is "email". However during tearDown dropping the constrain raises the following exception.

```
File "/usr/local/lib/python2.7/dist-packages/py2neo/schema.py", line 80, in drop_uniqueness_constraint
label=label, property_key=property_key).delete()
File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 339, in delete
raise_from(self.error_class(message, **content), error)
File "/usr/local/lib/python2.7/dist-packages/py2neo/util.py", line 235, in raise_from
raise exception
GraphError: HTTP DELETE returned response 500
```

I looked through the py2neo schema code as well as the ResourceTemplate code and nothing jumped out at me as being problematic, especially given the similarity of the `create_uniqueness_constraint` method which is successful. Could this really be a problem with the neo4j database?

**Comment by nigelsmall** [comment]
A 500 response is almost always indicative of a server problem. So the chances are you've hit a condition that the server doesn't have a code path for.

From your description, I'm wondering if you are attempting to delete the constraint or underlying index before it's been fully created. In real world production usage, constraints wouldn't be rapidly created and deleted, although this is perfectly valid for a test case. Maybe there's a bug there where a better response ought to be sent.

Either way, I don't think this is py2neo issue so your best bet is to try to produce a small piece of code that demonstrates the problem (reasonably) consistently then post this to the Neo4j GitHub issue list.

**Comment by TheArtOfEngineering** [comment]
Wow, that was fast. Yes, after some fiddling with the order and frequency of my calls to for creating and deleting constraints, it might be exactly what you described. It seems to be intermittent which lends credence to your theory. I'll see if I can't pin down exactly what it is. Thanks for the super fast response. py2neo is great by the way!
