### ISSUE TITLE
Enable passing multiple properties  and disable return value (merge_one)

### ISSUE THREAD

**Issue by bsuire** [technige/py2neo#401]
I think it would be great to be able to set multiple properties with the merge_one() method (while I'm sure it would be great to be able to do the same with other methods). Also, I would find it useful to be able to specify that a method shouldn't return any values in order to improve performance.
Thoughts?

**Comment by nigelsmall** [comment]
You're not the first to suggest allowing merge_one to accept multiple properties. I'm considering adding that so watch this space.

As to your second point, the higher level functions like this are intended to provide simplicity over performance. Making each such that you can "disable" the return value would certainly not aid simplicity and would provide negligible performance gain. Cypher is the key to more flexibility and performance so you may find it useful to look into that instead.

**Comment by bsuire** [comment]
Sounds good. Thanks Nigel!

**Comment by flipdazed** [comment]
I posted a workaround to this in stackoverflow...

http://stackoverflow.com/a/30634579/4013571
