### ISSUE TITLE
'ResourceTemplate' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by kutschkem** [technige/py2neo#410]
The following code fails with the current py2neo on pip. I am on Windows 7 with Python 2.7.9:

```
    nodes = [ Node('COMPANY', id= id, name= name) for id, name in results]
    graph.create_unique(nodes)
```

 File "src/main/python/tasks/trusted_edges_to_neo.py", line 13, in import_companies
    graph.create_unique(nodes)
  File "C:\tools\python\envs\networkpoc\lib\site-packages\py2neo\core.py", line 724, in create_unique
    statement = CreateStatement(self)
  File "C:\tools\python\envs\networkpoc\lib\site-packages\py2neo\cypher\create.py", line 44, in **init**
    self.supports_node_labels = self.graph.supports_node_labels
  File "C:\tools\python\envs\networkpoc\lib\site-packages\py2neo\core.py", line 1086, in supports_node_labels
    return self.neo4j_version >= (2, 0)
  File "C:\tools\python\envs\networkpoc\lib\site-packages\py2neo\core.py", line 964, in neo4j_version
    return version_tuple(self.resource.metadata["neo4j_version"])
AttributeError: 'ResourceTemplate' object has no attribute 'metadata'

**Comment by kutschkem** [comment]
The problem here is that I accidentally passed a string with curly braces, which leads to the creation of a ResourceTemplate instead of a Resource. I was passing a format string to the Graph constructor that I forgot to format. So, really my fault and not py2neo. Anyway, maybe this could fail differently, more obviously connected to an unbound resource template. The error message does not help much to debug this problem on the user side.

**Comment by nigelsmall** [comment]
I agree this isn't ideal and I'll leave this ticket open to try to come up with a better solution. At the moment, the presence of a curly bracket signals that we have a URL template instead of a URL, as you say. It would be better to determine this explicitly though, which wouldn't be a problem from a library perspective but would add a little more complexity in the discovery logic of Neo4j.

**Comment by technige** [comment]
Obsolete in v4
