### ISSUE TITLE
Neo.ClientError.Security.AuthorizationFailed"

### ISSUE THREAD

**Issue by scheung38** [technige/py2neo#440]
Installation was done via brew install neo4j and neo4j is running ok in the background:
$ neo4j start
Then in script:

```
from py2neo import Graph
graph = Graph()
```

returns:

```
{
    errors: [
{
    code: "Neo.ClientError.Security.AuthorizationFailed",
    message: "No authorization header supplied."
}
      ]
}
```

How to resolve thanks. Not sure if this is also for py2neo, but someone mentioned 

```
For Neo4j v2.2.5 it's in $NEO4J_HOME/conf/neo4j-server.properties line 23. Neo home is the top-level directory where neo has been extracted.
```

But I don't know where to find this conf file as I didnt have NEO4J_HOME setup

**Comment by nigelsmall** [comment]
Neo4j requires authentication. Please see the section on auth in the py2neo manual:
http://py2neo.org/2.0/essentials.html#authentication
