### ISSUE TITLE
Authorisation for CypherTransactions

### ISSUE THREAD

**Issue by Bondza** [technige/py2neo#441]
When trying to run a transaction after setting authentication I get the following error:

```
py2neo.error.Unauthorized: http://<host>/db/data/transaction/commit
```

I've checked the HTTP package sent to the database and the authorization header is not sent with the `POST` to the path above. It is however present during the first `GET` request to `/db/data` when creating the `Graph`.

I setup my connection as shown in the [documentation](http://py2neo.org/2.0/essentials.html#authentication):

```
authenticate('{host}:{port}'.format(host=args.host, port=args.port), args.username, args.password)
graph = Graph('http://{host}:{port}/db/data/'.format(host=args.host, port=args.port))
```

I've also tried adding username & password to the URI when creating the `Graph` object but that yields the same result. 

And then I get the `Unauthorized` error when I do:

```
tx = graph.cypher.begin()
... some queries ...
tx.commit()
```

**Comment by nigelsmall** [comment]
I'm not sure why this would be failing. Have you confirmed that you have the correct user name and password set? You could try hard-coding the values to rule out they're not being passed in incorrectly and make sure you can use those exact credentials to log into the browser.

You can also try the `watch` function to see what is being passed to and from the server:
http://py2neo.org/2.0/cookbook.html#monitoring-client-server-interaction
