### ISSUE TITLE
Killed stream transaction

### ISSUE THREAD

**Issue by jmsierra** [technige/py2neo#442]
Hi there,

I'm developing some performance test with py2neo and Neo4j 2.2.5. I am using streams to retrieve data bit a bit, as there is a huge amount and this way python seems to use much less memory. My code is as follows:

```
      stream = self.neo4j_graph.cypher.stream(query)
        for row in stream:
            print row.path
        stream.close()
```

The problem I have is that when the program is killed, the transaction (and the execution of the query) seems to remain alive on the server side until it finishes.

I was wondering if there is a way of killing that transaction within the program when it dies. 

Many thanks,
Juan M. Sierra

**Comment by nigelsmall** [comment]
Hi Juan

I have several thoughts here:

1. You are developing a performance test with py2neo. To what end? Are you aware of the underlying

**Comment by nigelsmall** [comment]
Accidentally closed, sorry. A few thoughts here:

1. What is the ultimate aim of your performance tests? Depending on the answer, the HTTP interface (that py2neo uses) may not be the fastest option.
2. Using less memory and better performance are often competing aims. You should decide which of these is most important.
3. The `stream` method is _generally_ slower than `execute`. This is because it attempts to incrementally decode the JSON that is returned, which is not something supported by the built-in JSON routines.

With regard to the lingering transaction, what indicators are you seeing that makes you think the server is still running the query?

**Comment by jmsierra** [comment]
Hi Nigel,

**Regarding 1:**
The background is that I have a tree-like data stored in a table in a traditional relational database. When trying to query it recursively, it was taking far too long. So, I decided to have a go with neo4j and see if it can get better performance. I have the python client and the neo4j server in separate different machines.

What drivers would you recommend for this purpose? 

**Regarding 2&3:**
Regarding the memory, there are some cases when I need to retrieve about 30-70 million rows, and in some cases the client crashed due to lack of memory (the client is running in a relatively small machine). So, I changed it to use the stream and it worked perfectly fine.

**Regarding the lingering transaction:**
When I kill the python client and this was running a long query, I can see in the Neo4j JConsole that the "NumberOfOpenTransactions" doesn't decrease and, on the Neo4j server machine, that the data partition is still busy. Whereas, when a normal or short query finishes normally the number of open transactions reduces and the data partition usage goes flat. 

I know that the Neo4j server should be the responsible of killing the dropped sessions at its side, but I'd like to know if there is a way to signal to Neo4j server that the current query must be stopped.

Thank you very much indeed for your prompt reply and help.

**Comment by nigelsmall** [comment]
I'm not sure why the server isn't killing it off. That said, 30-70 million rows is a very large result and so it may be taking a while to free resources. Could you share your Cypher query?

I'm looking at adding "kill" functionality to transactions in the next release. This may ultimately help in this instance if all other ideas fail.

**Comment by jmsierra** [comment]
Hi Nigel,
Sorry for the delay. 

The query looks like:
```cypher
match (:FILE {fileid:1}) -[:CONTAINS]-> 
  (:FILE {name:'level1'}) -[:CONTAINS]-> 
    (:FILE {name:'level2'}) -[:CONTAINS]-> 
      (:FILE {name:'level3'}) -[:CONTAINS]-> 
            (ft:FILE {name:'level4'}) 
match p=(ft) -[:CONTAINS*]-> (f:FILE) 
where  f.filemode >= 32768 and f.filemode < 40960 
return reduce(path = '/level1/level2/level3', n IN nodes(p) | path + '/' + n.name) as path 
order by path;
```
The system is imitating the behavior of the command find in linux. 

Regarding the kill functionality, I do believe something was introduced in one of the latest Neo4j server releases to kill a transaction, but unfortunately can't find where I read about it. I did make a small test using the parameters:
 * org.neo4j.server.webserver.limit.executiontime=
 * execution_guard_enabled=true

It did kill the transactions and it seemed to free up the resources. However it isn't an ideal solution as you have wait for a fix amount of time before it takes place.

Many thanks,
Juan
