### ISSUE TITLE
errors on create_unique in stderr

### ISSUE THREAD

**Issue by npem** [technige/py2neo#452]
Hi,

In my code I call:
 x = graph.create_unique(Relationship(pkg_node, rel_type, node))

The edge is always created, but I also get errors printed to standard error that are unexpected and that I cannot trap.

Here is sample output:
 Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018836' start=u'node/449829' end=u'node/449830' type=u'contains' properties={}
 Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018837' start=u'node/449830' end=u'node/449165' type=u'Characterized_By' properties={}
 Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018838' start=u'node/449830' end=u'node/449167' type=u'Created' properties={}
 Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018839' start=u'node/449830' end=u'node/449799' type=u'Used' properties={}
 Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018840' start=u'node/449830' end=u'node/449801' type=u'Characterized_By' properties={}
 Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018841' start=u'node/449830' end=u'node/449828' type=u'Connected_To' properties={}

Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018836',) in function remove at 0x7f659c2a7b18 ignored
 Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018837',) in function remove at 0x7f659c2a7b18 ignored
 Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018838',) in function remove at 0x7f659c2a7b18 ignored
 Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018839',) in function remove at 0x7f659c2a7b18 ignored
 Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018840',) in function remove at 0x7f659c2a7b18 ignored
 Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018841',) in function remove at 0x7f659c2a7b18 ignored

Can you shed any light on this issue, or tell me where to look?  Using version 2.0.8.

I had submitted this earlier but on an older version and with a mistaken title.  I closed that issue and created this one.

Thanks

**Comment by horejsek** [comment]
I see this in my log a lot as well. Using latest py2neo library, version 3. For now I don't why this is happening. It's fine and after while this message starts appearing. With 2.x.x I never saw anything similar to this.

**Comment by bellanchor** [comment]
I met this problem too, using version 2 and 3.
@npem  Do you figure out what is happening?
Thanks.
