### ISSUE TITLE
Set timeout for cypher execute

### ISSUE THREAD

**Issue by amyth** [technige/py2neo#465]
Hey Nigel, I want to override the default timeout for requests for different queries. I see that httpstream was updated in [this commit](https://github.com/nigelsmall/py2neo/commit/1f7eb867c88659baaa93d05d6f3f1252df6cc211) but I still cant figure out how can I override the the socket timeout of 30s.

**Comment by nigelsmall** [comment]
Sorry but no mechanism exists to control the timeout per query.

**Comment by rotten** [comment]
I go into the py2neo library on every server where I install it, and change it.  On my ubuntu servers I usually find the python 2 version in /usr/local/lib/python2.7/**dist-**packages/py2neo .  On my mac, I find it in /usr/local/lib/python2.7/**site_**packages/py2neo.

I edit the file packages/httpstream/http.py .   _30 seconds_ is way too short for many of my long running queries.  I usually bump it up to 10 minutes or more.

I usually double check that a fresh pyc is generated after I make the update so I'm confident I edited the right file.

**Comment by amyth** [comment]
@nigelsmall Thanks for your response. Is it possible to have such a feature in the future ? At least a separate timeout setting i.e configurable for read and write queries.

**Comment by technige** [comment]
@rotten you are referring to the TCP connection timeout, I think that @amyth is referring to query execution timeouts.
