### ISSUE TITLE
Unable to execute transactions against neo when configured behind a path

### ISSUE THREAD

**Issue by taimur38** [technige/py2neo#467]
I have neo configured to sit behind a uri by modifying `org.neo4j.server.webadmin.data.uri` in neo4j-server.properties

curling the new endpoint returns json as you would expect from neo4j, with all locations returned formatted correctly. But if I try and make a write to the db through `graph.cypher.execute(statement)`, http stream shows that while the driver makes the first POST to the correct modified endpoint at `/relurl/db/data/transaction/commit`, there is a subsequent get request which fails at `/db/data` without the new location behind it. This causes the transaction to fail

**Comment by taimur38** [comment]
It actually only happens when requesting an entire node be returned. Example:

```python
result = graph.cypher.execute('match (x:testing {id: 3}) return x')     # this errors

result = graph.cypher.execute('match (x:testing {id: 3}) return x.id')   # this does not error
```

**Comment by nigelsmall** [comment]
You can probably use `rewrite` to get around this:

http://py2neo.org/2.0/cookbook.html#uri-rewriting
