### ISSUE TITLE
delete() just hangs

### ISSUE THREAD

**Issue by rotten** [technige/py2neo#475]
I can't get py2neo's delete function to work.  It just hangs forever.  I'm not sure why.

All of these seem to just hang (until timeout):
- `g.delete(node)`
- `g.delete(relationship)`
- `node.delete()`
- `relationship.delete()`

However if I do a cypher query (with or without the "detach"), it works very quickly:

```
g.cypher.execute("match (n) where id(n) = %d detach delete n" % node._id)
```

I'm using python 2.7.11 with neo4j 2.3.2-community and py2neo 2.0.8.

**Comment by rotten** [comment]
FWIW, I get the same behavior with python 3.4.3.

**Comment by Zoher15** [comment]
+1
