### ISSUE TITLE
Problems with creating subgraph in transaction

### ISSUE THREAD

**Issue by dchaplinsky** [technige/py2neo#503]
Hello.

I'm using py2neo3b2 and Neo4j 3.0.0

I've created couple of subgraphs in memory with py2neo and now trying to load them into neo4j.
`graph.create(Subgraph(lemmas + list(jnodes_cache.values()), relations))`
It has 590 nodes and 1250 relationships.

However, py2neo hangs for quite a lot of time on this simple operation. Actually, I never had enough patience to let it finish. It works better on subgraph of smaller size though (168/340 got loaded in 1m15.7s).

Any hints?
I've tried to switch to bolt, but it doesn't seems to work (check my comment to #500).
Should I threw it to neo4j in a smaller portions?

I can give you Pickled version of objects I'm trying to load to neo4j, so you might be able to reproduce it.

**Comment by dchaplinsky** [comment]
![populatedb 2016-05-01 6 -05-22](https://cloud.githubusercontent.com/assets/131186/14942498/50f78c94-0fc7-11e6-82bd-b73f1fe64c6c.png)

**Comment by dchaplinsky** [comment]
![populatedb 2016-05-01 6 -14-07](https://cloud.githubusercontent.com/assets/131186/14942542/88c19f92-0fc8-11e6-815f-a69107d657c0.png)
This solution is order of many magnitudes quicker

**Comment by dchaplinsky** [comment]
Then I've tried to push it even further with threadpool:
```python
with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
    for x in executor.map(sub_create_nodes, paginate(lemmas + list(jnodes_cache.values()), 100)):
        pass

with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
    for x in executor.map(sub_create_rels, paginate(relations, 30)):
        pass
```

I've got a nice speed improvement, but then things turned into worse. At the middle of import to neo4j I've started receiving errors like this:
```DatabaseError: An unexpected failure occurred, see details in the database logs, reference number 26c65a6e-8dc0-4ea8-8ba9-d31824ff4946.```
Inspection of ```debug.log``` shown that neo4j complains about too many files open.

I've cranked max open files settings of mac os x to 512k and restarted the system:
```
$ sudo sysctl -a | grep files
kern.maxfiles: 524288
kern.maxfilesperproc: 524288
kern.num_files: 5589
```
That helped me to import little bit more but result was the same. More over! It's not possible to start neo4 now, as it dies on startup with same error message:
```[CIRCULAR REFERENCE:java.nio.file.FileSystemException: /usr/local/Cellar/neo4j/3.0.0/libexec/data/databases/graph.db/schema/label/lucene/labelStore/1/_6w_BlockTreeOrds_1460.tipo: Too many open files]```

I.e it cannot load DB from disk.

I have only one explanation for that atm: looks like sending too many transactions is causing major usage of file descriptors.

And now I'm officially desperate (and switching to 2.x :()

**Comment by dchaplinsky** [comment]
@nigelsmall ?

**Comment by dchaplinsky** [comment]
![fuck it i m going home penguin - google 2016-05-10 1 -03-16](https://cloud.githubusercontent.com/assets/131186/15129560/fe4d25c8-164a-11e6-82ee-529ba94dbb9b.png)

```python
def dump_nodes_to_csv(jnodes, fname):
    header = set()

    for jnode in jnodes:
        header.update(jnode.properties.keys())
    
    with open(fname, "w") as fp:
        w = DictWriter(fp, fieldnames=["wordFormId:ID(WF)", ":LABEL"] + list(header))
        w.writeheader()

        for jnode in jnodes:
            rec = {
                "wordFormId:ID(WF)": jnode["term"],
                ":LABEL": ";".join(jnode.labels)
            }
            
            rec.update(jnode.properties)
            w.writerow(rec)


def dump_relations_to_csv(jrels, fname):
    header = set()

    for rel in jrels:
        header.update(rel.properties.keys())
    
    with open(fname, "w") as fp:
        w = DictWriter(fp, fieldnames=[":START_ID(WF)", ":TYPE", ":END_ID(WF)"] + list(header))
        w.writeheader()

        for rel in jrels:
            rec = {
                ":START_ID(WF)": rel.start_node["term"],
                ":END_ID(WF)": rel.end_node["term"],
                ":TYPE": rel.type
            }
            
            rec.update(rel.properties)
            w.writerow(rec)
```

**Comment by DomWeldon** [comment]
Did you get anywhere with this? I'm struggling with the below... Not sure if this is to do with py2neo or neo itself. It's just a big cypher query....

`py2neo.database.status.DatabaseError: An unexpected failure occurred, see details in the database logs, reference number [uuid]`
