### ISSUE TITLE
Cannot find Anything on the AttributeError

### ISSUE THREAD

**Issue by yayati1** [technige/py2neo#506]
AttributeError: module 'py2neo.cypher.error.statement' has no attribute 'SyntaxError'
Whenever I try to execute a string which specifies a relation, i get he above error.
and i cant seem to find a solution for it online

**Comment by nigelsmall** [comment]
Please show some code.

**Comment by yayati1** [comment]
Hi Nigel,
It seems I was not using the correct version of Py2Neo library. The above error cleared when i upgraded py2neo to version 3b2. I am testing the milestone release 3 of Neo4j.
Thanks for the reply

**Comment by yayati1** [comment]
Hi Nigel,
I am getting the following error when I try to start the Neo4j -3.0.1 multi machine cluster 

ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@51e5cc21' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@51e5cc21' was successfully initialized, but failed to start. Please see attached cause exception.

I have successfully installed the single machine cluster on My laptop but cant seem to find a way around the multi machine problem. Any suggestions?
Please find attached the Conf file from the master machine(my laptop) 
[conf_file_neo4j.txt](https://github.com/nigelsmall/py2neo/files/262751/conf_file_neo4j.txt)

**Comment by nigelsmall** [comment]
You'd be better off asking about clustering issues on the Neo4j mailing list or public Slack rather than here.

**Comment by ExplodingCabbage** [comment]
Just saw the same bug from the original post on 2.0.8. Can't share proprietary code right now but can share the end of the stack trace:

```
  File "/myapp/venv/lib/python3.5/site-packages/py2neo/cypher/core.py", line 333, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/myapp/venv/lib/python3.5/site-packages/py2neo/cypher/core.py", line 288, in post
    raise self.error_class.hydrate(error)
  File "/myapp/venv/lib/python3.5/site-packages/py2neo/cypher/error/core.py", line 54, in hydrate
    error_cls = getattr(error_module, title)
AttributeError: module 'py2neo.cypher.error.statement' has no attribute 'SyntaxError'
```

What I believe is happening at a glance is that https://github.com/nigelsmall/py2neo/blob/py2neo-2.0.8/py2neo/cypher/error/core.py#L51 is trying to instantiate a `statement.SyntaxError` after getting that back from Neo4j, and failing because https://github.com/nigelsmall/py2neo/blob/py2neo-2.0.8/py2neo/cypher/error/statement.py has no such class.

I will try to repro in a minimal case if you like, but I think there's sufficient information here to be able to confirm the existence of a bug in 2.0.8 (and either close this issue or perhaps fix the bug, if it's not already fixed on later versions) without needing a minimal test case.

**Comment by ExplodingCabbage** [comment]
One note about the above: in the deployment where I reproed this error I was using py2neo 2.0.8 but Neo4j 3 and the bug may simply be due to using an unsupported version of Neo4j.

**Comment by piyush121** [comment]
I am also getting same error in my queries : 
`Traceback (most recent call last):
  File "writeQueries.py", line 116, in <module>
    filterInterestedCandidates()
  File "writeQueries.py", line 59, in filterInterestedCandidates
    a = graph.cypher.execute("MATCH (age:AGE)<-[:has_age]-(person:"+str(orientation_mapping.get(use_gender_orientation))+")-[:has_height]->(height:HEIGHT) where age.age<51 AND age.age>17 AND height.height>140 WITH p MATCH (theUser:USER)-[:has_activity]->(activity:FETCH_ACTIVITY)-[:was_active_on]->(date:ACTIVE_DATE)-[:active_session]->(:ACTIVE_SESSION)-[:login_at]->(the_active_location:ACTIVE_LOCATION) where theUser.uniqueID='%s' AND date.date='2016-06-13' WITH the_active_location MATCH (p)-[:has_activity]->(:FETCH_ACTIVITY)-[:was_active_on]->(date:ACTIVE_DATE)-[:active_session]->(:ACTIVE_SESSION)-[:login_at]->(active_location:ACTIVE_LOCATION) where date.date='2016-06-13' AND toInt(distance(point(active_location),point(the_active_location)) / 1000)<150 return person" %userID)
  File "/home/ubuntu/miniconda3/envs/py3/lib/python3.5/site-packages/py2neo/cypher/core.py", line 136, in execute
    results = tx.commit()
  File "/home/ubuntu/miniconda3/envs/py3/lib/python3.5/site-packages/py2neo/cypher/core.py", line 333, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/home/ubuntu/miniconda3/envs/py3/lib/python3.5/site-packages/py2neo/cypher/core.py", line 288, in post
    raise self.error_class.hydrate(error)
  File "/home/ubuntu/miniconda3/envs/py3/lib/python3.5/site-packages/py2neo/cypher/error/core.py", line 54, in hydrate
    error_cls = getattr(error_module, title)
AttributeError: module 'py2neo.cypher.error.statement' has no attribute 'SyntaxError'`

Any solution to this error ?
