### ISSUE TITLE
Py2Neo with bolt is much slower

### ISSUE THREAD

**Issue by andyp05** [technige/py2neo#520]
I started to work with py2neo v3 and Neo4j 3.0.1 and noticed it is quite a bit slower than v2 running the same program on the same machine. After a little digging around, I discovered that when bolt is on, it takes twice as long to return a very basic cypher query using graph.run().

graph = Graph(bolt=True)
graph.run("MATCH (d:Document) RETURN d.id as id")

This query will return around 200,000 ids each less than 15 bytes long. Time for running the graph.run() command (no iterating over results) are:
Version 2 of Neo4j and py2neo returned in 2.1 seconds. 
Version 3 of Neo4j and py2neo with bolt on returns in 10.9 seconds. 
Version 3 of Neo4j and py2neo with bolt off returns in 5.6 seconds. 

In all cases, the query returns the correct results and iterating over the results in all cases is relatively fast.

I am running the DB on my desktop so network issues are not a factor. My virus protection excludes the data directory. It is a fairly fast computer with a Samsung PRO SSD, Intel i7 processor with 32 GB RAM and python 3.5.1 64 bit on Windows 10. 

Running the same functional query against MS SQL using pymssql takes 0.4s.

Any ideas as to why the slowdown?

Thanks,

Andy

**Comment by ngbravo** [comment]
I´m also seeing a 11% slowdown when using Bolt vs HTTP. I'm measuring running multiple queries, but I don't think the query itself has some influence over this.

**Comment by andyp05** [comment]
Nigel,

Some more info to hopefully help track down the issue. Native Bolt driver is much faster:

from neo4j.v1 import GraphDatabase
from py2neo import Graph
qry = "MATCH (d:Document) WHERE EXISTS(d.title) RETURN d.id as id LIMIT 10000"

driver = GraphDatabase.driver("bolt://localhost")
session = driver.session()
%timeit -n50 session.run(qry)

graphF = Graph(bolt=False)
%timeit -n50 graphF.run(qry)

graphT = Graph(bolt=True)
%timeit -n50 graphT.run(qry)

50 loops, best of 3: 95.4 µs per loop
50 loops, best of 3: 78.9 ms per loop
50 loops, best of 3: 349 ms per loop
