### ISSUE TITLE
Odd Behavior when Port 80 is used as proxy

### ISSUE THREAD

**Issue by dloker** [technige/py2neo#524]
When connecting a server on port 80, I experienced odd behavior as of version 3.

> GET http://<SERVER_IP>:80/db/data/
> < 200 OK [708]
> POST http://<SERVER_IP>:80/db/data/transaction/commit [135]
> < 200 OK [chunked]
> GET http://<SERVER_IP>:7474/db/data/

Notice that it switches the server from 80 to 7474. After digging into the code for awhile, I noticed it removes the port entirely from subsequent calls, and then DBMS defaults to the port 7474 since none is specified.

In addition, the same disappearing port 80 gave me Unathorized messages after I hacked it so that the default port was 80 for DBMS to get around the first error. I tried authorizing both port 80 and just <SERVER_IP> without any port. Neither made a difference.

> GET http://<SERVER_IP>:80/db/data/
> < 200 OK [708]
> POST http://<SERVER_IP>:80/db/data/transaction/commit [135]
> < 200 OK [chunked]
> POST http://<SERVER_IP>:80/db/data/transaction [572]
> < 201 Created [3231]
> POST http://<SERVER_IP>/db/data/transaction/306 [5882]
> < 401 Unauthorized [139]
> Traceback (most recent call last):
> ...
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 1049, in **init**
>     Entity.**init**(self, (n[0], self, n[1]), p)
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 713, in **init**
>     Walkable.**init**(self, iterable)
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 540, in **init**
>     Subgraph.**init**(self, self.**sequence[0::2], self.__sequence[1::2])
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 218, in __init**
>     self.**nodes = frozenset(nodes or [])
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 874, in __hash**
>     remote_self = remote(self)
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 767, in remote
>     return obj.**remote**
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 740, in **remote**
>     self.**remote_pending_tx.process()
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init**.py", line 1012, in process
>     self._post()
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 1180, in _post
>     rs = resource.post({"statements": self.statements})
>   File "/usr/local/lib/python2.7/dist-packages/py2neo/database/http.py", line 206, in post
>     raise Unauthorized(self.uri.string)
> py2neo.database.status.Unauthorized: http://<SERVER_IP>/db/data/transaction/306

**Comment by brycetho** [comment]
I'm running into this too.
`In [70]: tx.commit()
> POST http://neo4j.spsdev.in:80/db/data/transaction/commit [162]
~ Reconnecting (peer closed connection)
> POST http://neo4j.spsdev.in:80/db/data/transaction/commit [162]
< 200 OK [1432]
> GET http://neo4j.spsdev.in:7474/db/data/
! SocketError: Operation timed out`
