### ISSUE TITLE
Py2Neo graph.run() freezes

### ISSUE THREAD

**Issue by prashanthravindran** [technige/py2neo#531]
For the following query to get all distinct paths in a tree
`paths = graph.run("MATCH (root:TARGETS_ROOT) MATCH paths = (root)-[r:FULFILLED_BY | CONCRETELY_FULFILLED_BY *0..100]->(leaf) WHERE NOT(leaf-->()) RETURN paths")` 
py2neo freezes, whereas from the neo4j-shell the same query executes in about 70 seconds

The py2neo version is 
`In [18]: py2neo.__version__`
`Out[18]: '3'`

The number of such paths in my tree are:
`In [26]: paths = graph.run("MATCH (root:TARGETS_ROOT) MATCH paths = (root)-[r:FULFILLED_BY | CONCRETELY_FULFILLED_BY *0..10]->(leaf) WHERE NOT(leaf-->()) RETURN COUNT(paths) AS num_paths")`

`In [27]: for p in paths: print(p)
('num_paths': 182761)
`
py2neo in the case of returning the paths (not the counting case) appears to be failing silently - waited about 5 mins before interrupting. Queries that return less data work fine

I am using neo4j 2.3.2 at the server end
`In [31]: default_dbms.kernel_version`
`Out[31]: (2, 3, 2)
`

**Comment by nigelsmall** [comment]
So this will use the HTTP API. Have you tried running directly against the server, using `curl` or similar?
