### ISSUE TITLE
Make OGM play nice with Graphaware UUID plugin

### ISSUE THREAD

**Issue by mjmare** [technige/py2neo#538]
When I use UUID as a property in a GraphObject in combination with the GraphAware uuid plugin (https://github.com/graphaware/neo4j-uuid), given the lack of a proper unique ID in Neo4J I get vague errors when pushing a GraphObject twice.
Doing a push-pull-push works. Probably because the pull gets the uuid assigned in the server. 

```
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/http.py", line 203, in post
    response = self.__base.post(body, headers, **kwargs)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/packages/httpstream/http.py", line 984, in post
    return rq.submit(**kwargs)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/packages/httpstream/http.py", line 452, in submit
    return Response.wrap(http, uri, self, rs, **response_kwargs)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/packages/httpstream/http.py", line 489, in wrap
    raise inst
py2neo.packages.httpstream.http.ServerError: 500 Server Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/__init__.py", line 658, in push
    subgraph.__db_push__(self)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/ogm.py", line 399, in __db_push__
    graph.push(node)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/__init__.py", line 658, in push
    subgraph.__db_push__(self)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/types.py", line 488, in __db_push__
    remote(graph).resolve("batch").post(batch)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/http.py", line 212, in post
    raise_from(GraphError(message, **content), error)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/util.py", line 124, in raise_from
    raise exception
py2neo.database.status.GraphError: HTTP POST returned response 500
```

**Comment by nigelsmall** [comment]
Please define "play nice". I'm not familiar with this plugin.

**Comment by mjmare** [comment]
Yeah, play nice is not a very technical term ;-)

As you are well aware, Neo4j's node ID are not to be used as a unique identifier. So lacking this support the community recommends an unmanaged extension like the one from Graphaware to generate a uuid *on the server* when creating a node. This works fine in most situations. 
However when using the extension with py2neo OGM (with __primarykey__ = "uuid") will not work (generate errors), probably because the OGM expects the PK value to provided before pushing. IOW when pushing it does not know that the PK will be generated on the server. 

The whole issue would be moot if the OGM supported OOTB automatically generating a uuid as a PK. 
If not supported directly OOTB, it might be useful to be able to provide a default value (callable) for a property might be enough to solve the problem without a server extension. 
Usage would be something like:

def gen_uuid():
    return str(uuid.uuid4)

class MyClass(GraphBase):
    __primarykey__ = "uuid"

    title = Property(default=gen_uuid)     


 Hope this clears it up a bit.

**Comment by nigelsmall** [comment]
Thanks for the detail :-)

Support for this should be quite straightforward then. How are these stored in the database? Any property can contain a UUID and those properties will be stored as strings?

**Comment by mjmare** [comment]
You mean the GraphAware generated uuid? Yes, those are stored as a string property on the node.

**Comment by dmk255** [comment]
I'd like to resurrect this issue. I'm trying to use py2neo with graphaware's uuid plugin. I'm running into an issue where if I push a node without a uuid it will create the node succesfully. However, if the node already exists and I try to 'push' it with a blank uuid I get a `Neo.ClientError.Transaction.TransactionHookFailed`. See the example below.

```
from py2neo.ogm import GraphObject, Property
from py2neo import Graph

graph = Graph('bolt://localhost:7687/')

class Foo(GraphObject):
    __primarykey__ = 'uuid'

    def __init__(self, name):
        self.name = name

    uuid = Property()
    name = Property()

node = Foo('bar')
# This will work on the first run but fail on the second.
graph.push(node)
```

The way to fix this at the moment is to first 'pull' the node then 'push' it. However, if the node doesn't exist the pull will also return an error. Further, if you attempt to create other nodes & relationships in one push statement you will always receive an error unless all the nodes do not exist:

```
from py2neo.ogm import GraphObject, Property, RelatedFrom
from py2neo import Graph

graph = Graph('bolt://localhost:7687/')

class Foo(GraphObject):
    __primarykey__ = 'uuid'

    def __init__(self, name):
        self.name = name

    uuid = Property()
    name = Property()

class Biz(GraphObject):
    __primarykey__ = 'uuid'

    def __init__(self, name):
        self.name = name

    uuid = Property()
    name = Property()
    foos = RelatedFrom(Foo, "FOOS")


foo = Foo('foo')
biz = Biz('biz')
biz.foos.add(foo)
# This will work on the first run but fail on the second.
graph.push(biz)
```

**Comment by dmk255** [comment]
Quick follow up.

After some more investigation it looks like the main issue is that py2neo is trying to update the 'uuid' property on push (which throws an error in the `neo4j-uuid` plugin). The likely fix here is to have a 'readonly' property which would only be sent in two cases:
1. If the node doesn't exist during a 'push' event 
2. On a merge event
