### ISSUE TITLE
Add introspection capabilities to GraphObject class

### ISSUE THREAD

**Issue by mjmare** [technige/py2neo#542]
When constructing generic admin interfaces it is convenient to be able to inspect persistence classes in order to display them. 

E.g. I'd like to create some generic views for my GraphObject derived classes. For this to work I need to be able to find out for a given class what its defined Property and Related/RelatedTo/RelatedFrom's attrs are. Then I could display it in, say, a table.
Another use case is a generic (pretty) print function that would be able to display any GraphObject derived class in the REPL.

[Currently this is not obvious (to me) how to obtain this information. Something like dir(GraphObjectDerivedClass) will yield the class attributes, but filtering on class to find the Property's fails because type(GraphObjectDerivedClass.someProperty) fails in Property.**get** because no instance exists (obviously).]

**Comment by technige** [comment]
Good idea, I'll look into it.
