### ISSUE TITLE
Graph(uri) fails when URI contains a path prefix

### ISSUE THREAD

**Issue by duffj** [technige/py2neo#545]
Due to our path-based routing system, our neo4j instance has a data URL that looks like this:

```
http://<host>:<port>/foo/db/data/
```

Unfortunately, the py2neo library seems to assume that the `foo` path will never exist. I've had to hack the library and hard-code my path to get my scripts to work. Is this definitely a bug?

**Comment by nigelsmall** [comment]
Thanks for raising this. Path offsets are currently not supported but it should be reasonably easy to add when I get time.
