### ISSUE TITLE
Creating a relation alters the nodes. Is this expected behaviour?

### ISSUE THREAD

**Issue by razvankusz** [technige/py2neo#555]

**Comment by nigelsmall** [comment]
Sorry, you'll have to be far more specific.

**Comment by razvankusz** [comment]
Right. I was hoping I will click with someone who has run into this before. What happens is that creating a Relationship between two bounded nodes seems to pull the nodes from the database first. For example if I update a property of a node and then create a relationship with it at one end, the property will not persist to the database. Maybe this is just a limitation of the neo4j, but it would be nice to be able to batch such changes, because in my case having to push before creating new relationships is very inefficient.

**Comment by nigelsmall** [comment]
Can you show me some code...

**Comment by razvankusz** [comment]
`node_a = Node('a')
 node_b = Node('b') 
 graph.create(node_a)
 graph.create(node_b)
 
 node_a['my_prop']='1'
  
 graph.create(Relationship(node_a, 'link', node_b))
  
 assert(node_a['my_prop'] == '1')
`
Something like this. I'm sorry, I am pretty new to github :grin:

**Comment by razvankusz** [comment]
`node_a = Node('a')
node_b = Node('b') 
graph.create(node_a)
graph.create(node_b) 
node_a['my_prop']='1'
graph.create(Relationship(node_a, 'link', node_b))
assert(node_a['my_prop'] == '1')
`
Something like this. I'm sorry, I am new to github :grin:

**Comment by razvankusz** [comment]
`node_a = Node('a') 
node_b = Node('b')
graph.create(node_a) 
graph.create(node_b)
node_a['my_prop']='1' 
graph.create(Relationship(node_a, 'link', node_b))
assert(node_a['my_prop'] == '1') 
`
Something like this. I'm sorry, I am new to github :grin:

**Comment by razvankusz** [comment]
```python
node_a = Node('a')
node_b = Node('b')
graph.create(node_a)
graph.create(node_b) 
node_a['my_prop']='1'
graph.create(Relationship(node_a, 'link', node_b)) assert(node_a['my_prop'] == '1')
```
Something like this. I'm sorry, I am new to github :grin:

**Comment by razvankusz** [comment]
```python
node_a = Node('a')
node_b = Node('b')
graph.create(node_a)
graph.create(node_b) 
node_a['my_prop']='1'
graph.create(Relationship(node_a, 'link', node_b)) 
assert(node_a['my_prop'] == '1')
```
Something like this. I am sorry, I am new to github :grin:
