### ISSUE TITLE
RelatedObjects Doesn't Respect RelatedClass Argument

### ISSUE THREAD

**Issue by tjwright** [technige/py2neo#568]
For a given GraphObject based on a neo4j graph such as the one shown below, it seems that when retrieving the 'RelatedObjects' of an object that has incoming relationships of the same type but from two different class of node, the label of the node is not taken into account. As an example the sample code as shown below prints 'True'

![image](https://cloud.githubusercontent.com/assets/350873/18476931/c5f8001c-79c3-11e6-858f-3ad6a3540349.png)

Pink/red node class: pe
Blue nodes class: pc
Red node class: exchange_pdp

Code:

``` python
class PE(GraphObject):
    __primarykey__ = "Code"

    Code = Property()

    pcs = RelatedFrom("PC", "ENTITLES")
    exchange_pdp = RelatedFrom("exchange_pdp", "ENTITLES")

class PC(GraphObject):
    __primarykey__ = "Code"

    Code = Property()

    PE = RelatedTo("PE", "ENTITLES")

class exchange_pdp(GraphObject):
    __primarykey__ = "Code"
    __primarylabel__ = "Exchange PDP"

    Code = Property()

    PE = RelatedTo("PE", "ENTITLES")

graph = Graph(password='1')
pe = PE.select(graph, "5625").first()
print pe.pcs == pe.exchange_pdp

```

**Comment by dmk255** [comment]
I have the same issue and it's causing some significant problems with my data model.
