### ISSUE TITLE
Can't create multiple relationships between two nodes

### ISSUE THREAD

**Issue by jellever** [technige/py2neo#569]
I am trying to create multiple relationships between two nodes with the same relationship label. This does not seem possible with the py2neo library? What I expect is to create two relations between the nodes. Instead with this example code I create only 1 relationship? Is this expected behavior? Is there a way to create multiple relationships between 2 nodes? 

```
import py2neo
from py2neo.ogm import *

class TestClass1(GraphObject):
     __primarykey__ = "name"

     name = Property()

     my_rel = RelatedTo("TestClass2")


class TestClass2(GraphObject):
    __primarykey__ = "name"

    name = Property()
    rel = RelatedFrom(TestClass1, "MY_REL")


def main():
    graph = py2neo.Graph("http://neo4j:<MYPASSWORD>@localhost:7474/db/data/")
    testobj1 = TestClass1()
    testobj1.name = "TestObject 1"
    testobj2 = TestClass2()
    testobj2.name = "TestObject 2"

    testobj1.my_rel.add(testobj2)
    testobj1.my_rel.add(testobj2)
    graph.push(testobj1)
    graph.push(testobj2)


if(__name__ == "__main__"):
    main()

```

**Comment by felipsant** [comment]
Hey, I'm having the same problem. I can't create multiple relationship from the same nodes.

Why self.graph.create is actually doing an merge operation? Merge should merge, create should create, they should be different operations, no? Am I missing something?

```
   graph.schema.create_uniqueness_constraint('COMMENTS', 'uuid')

    def comment(self, post_uuid, comment):
        post = self.graph.find_one('Post','uuid', post_uuid)
        user = self.graph.find_one('User','uuid', self.uuid)
        r_comment = Relationship(user, "COMMENTS", post, comment=comment, uuid=uuid4().hex, date=str(datetime.utcnow()))
        self.graph.create(r_comment)
        return True
```

**Comment by technige** [comment]
This is a deliberate restriction. Please see #573 for an explanation. You will need to use Cypher directly, rather than the py2neo higher level API to achieve this.

**Comment by happymishra** [comment]
@technige Can you let me know how can I handle such a scenario like A = B+C+D+E+F.. and so. 
Its very difficult to create separate relation name for each relation type. Do I need to use cypher to handle this scenarion?

**Comment by hshrimp** [comment]
Hello, i meet the same question.
i have two relations which have same start node and end node and also the relation type. When i want to create this two relations by graph.create(), it run MERGE method but not the CREATE method, so the second relation will not to be create in the graph. why is MERGE?
thanks
Solution: I change the MERGE method to CREATE method in the py2neo, and it works. But i still confuse about that why is MERGE but not the CREATE in the py2neo.database.Graph.create().
