### ISSUE TITLE
socket error for database connection

### ISSUE THREAD

**Issue by ElnazBigdeli** [technige/py2neo#572]
Hi I have installed py2neo using 
sudo pip install py2neo

After that i wrote a code and saved the file as 'saran.py'

`from py2neo import neo4j, authenticate, Graph

host_port = "localhost:7474"
user_name = "neo4j"
password = "saran_probyto2425"

authenticate(host_port, user_name, password)
graph = Graph("http://localhost:7474/db/data/")
`

But I'm getting an error message as:
Traceback (most recent call last): File "saran.py", line 1, in <module> from py2neo import neo4j, authenticate, Graph ImportError: cannot import name neo4j 
I don't know what the problem is.Could you please help me?

**Comment by mikayla-grace** [comment]
You're likely using py2neo 3.  Try this:

```
from py2neo import Graph, Node, Relationship, Path

graphURL='http://localhost:7474/db/data/'
graphUser = "neo4j"
graphPassphrase = "saran_probyto2425"

graph=Graph(graphURL, user=graphUser, password=graphPassphrase)
```
