### ISSUE TITLE
Cannot model "Person OWNS Car" and "Person OWNS House" with OGM on py2neo 3.1.1

### ISSUE THREAD

**Issue by tgianko** [technige/py2neo#573]
In OGM, I am trying to model a situation in which a Person (node) can OWN (relationship), for example, a Car (node) or a House (node). 

My original question was asked few weeks ago on [stackoverflow.com](http://stackoverflow.com/questions/39292197/py2neo-ogm-relationship-with-multiple-node-labels) but unfortunately I couldn't find an alternative way to model this type of relationship with OGM. 

I had a quick look at the source code of py2neo and I suspect that there's no bug. Instead, I feel that this is a missing feature. I hope that this can be implemented as I find it extremely important. 

This is the type of graph that I intend to model with OGM:
![image](https://cloud.githubusercontent.com/assets/7878042/18973929/80252788-86a0-11e6-81f9-24538f897f5d.png)

This is the code I use for Car and House:

``` python
from py2neo.ogm import GraphObject, Property, RelatedTo
from py2neo import Graph

class Car(GraphObject):
    model = Property()

class House(GraphObject):
    city = Property()
```

My problem is on the Person class: how do I define with OGM a relationship that can point both to a Car and a House? 

`RelatedObject.add` appends node in a list, but I think the underlying assumption is that the list contains nodes of the same type. I tried to force this assumption and come up with a workaround that works to push data, but it fails when retrieving data.

So this is the Person class:

``` python
class Person(GraphObject):
    name = Property()
    Owns = RelatedTo("Car")
```

In the example above, I could have used `Owns = RelatedTo("House")` instead of `Owns = RelatedTo("Car")` without changing the final outcome of the experiment. 

The code to push data in neo4j is the following:

``` python
# Create Pete
p = Person()
p.name = "Pete"  

# Create Ferrari
c = Car()
c.model = "Ferrari"

# Pete OWNS Ferrari
p.Owns.add(c)

# Create House
h = House()
h.city = "New York"

# Now Pete OWNS a House in New York
p.Owns.add(h)

# Push this in the DB
g.push(p)
```

The code above manages to do the job. However, I could not find a solution to retrieve data with correct relationships. For example:

``` python
p = Person.select(g).where(name="Pete").first()
for n in list(p.Owns):
    print type(n).__name__
```

returns:

``` python
Car
Car
```

While my expectations were:

``` python
Car
House
```

The order of class names is irrelevant, what it matters for me is that I have the right nodes.

How can I retrieve correctly this type of relationships?

**Comment by tgianko** [comment]
As a comment of the last change: `push` does not need to be called twice. It works also by calling it once, at the end.

**Comment by tgianko** [comment]
After digging in the source code, I have found that in `ogm.py` at line 240 in function `__db_pull__` (See [here](https://github.com/nigelsmall/py2neo/blob/v3/py2neo/ogm.py#L240)), the list `nodes` contains both labels `Car` and `House`. However, in both cases, two instances of the class `Car` are created as a result of `wrap`.

At this point, should be rather easy to support a list of node labels, rather than a single label? 

For example, I am thinking to specify expected labels as follows:

```python
class Person(GraphObject):
    name = Property()
    Owns = NewRelatedTo("Car", "House")
```

Then,  when pulling data from the DB, `__db_pull__` checks whether any of the retrieved labels is in the list of expected labels. If yes, wrap.

**Comment by nigelsmall** [comment]
This kind of model is deliberately not supported by py2neo. Partly because it simplifies the client-side type system and partly because sharing a relationship type name across multiple semantically-different relationship types is a discouraged modelling technique. This relates to the efficiency of Cypher queries whereby it is generally more common to search for either type of relationship separately than it is to search for them both together.

The recommended approach is to name your relationship types `OWNS_CAR` and `OWNS_HOUSE` instead.

**Comment by philsloggett** [comment]
Thanks for that explanation @technige - What about if there were an additional label "Ownable" on all "Car" and "House" types. So an "Owned" relationship would still only ever exist against an "Ownable", would this have the same efficiency implications? I've only just started playing with py2neo (and neo4j) and haven't been successful in applying multiple labels to a node (to test this idea out), is this supported?

**Comment by mjmare** [comment]
@technige I'm not convinced that the OWNS_CAR and OWNS_HOUSE are semantically different. When even more than two Node types are possible (could be tens or hundreds different node types) a separate relationship type for each combination seems unfeasable. One could even say the model contains duplicate information (i.e. In the node type and in the relationship type).
