### ISSUE TITLE
How to get neighbors of a node ?

### ISSUE THREAD

**Issue by ikus060** [technige/py2neo#578]
I'm struggling to find the proper way to get all the relations for a given node.

```
from py2neo import Graph
g = Graph(...)
node = g.find_one('Person', property_key='name', property_value='ikus060')
node.relationships()
```

`node.relationships()` return an empty tuple.

From the `node` object, How do I get the list of relations ship and the neighbors ?

**Comment by technige** [comment]
You'll need to use the `Graph.match` method.
