### ISSUE TITLE
How to run graph.data in a single transaction?

### ISSUE THREAD

**Issue by enfeizhan** [technige/py2neo#582]
Have to run something like:

```
query_template = '''
    match (p1)-->(m)<--(p2)
    where p1.name = {p1_name} and p2.name = {p2_name}
    return p1.name, m.date, p2.name
'''
df = pd.DataFrame({})
for player1, player2 in player_pairs:
    df = df.append(
        graph.data(query_template, { "p1_name": player1,  "p1_name": player2})
    )
```
The problem is if ``player_pairs`` got 10k pairs the query above is terribly slow as each query runs in a separate transaction. So wondering if there is any way to pack all queries in a single transaction? Thanks:)

**Comment by technige** [comment]
So for example a `tx.data` method?

**Comment by technige** [comment]
Could you not combine all of your queries into a larger query into which you pass a list (or two lists) of players?
