### ISSUE TITLE
What do you think to add code coverage report to each PR?

### ISSUE THREAD

**Issue by andriisoldatenko** [technige/py2neo#588]
Current coverage is pretty good, it's 95% (on latest v4 branch).
But if somebody remove or add code, it's difficult to see how code coverage increase or decrease.
Proposal to add something like codecov-io or similar.
Also you can find usage in another projects e.g. https://github.com/KeepSafe/aiohttp/pull/1507
And screenshot of report:
![image](https://cloud.githubusercontent.com/assets/1374633/21521629/70201f98-cd07-11e6-8b68-df03ef17bca6.png)

P.S. 
As you can see you can configure and codecov-io will fail PR if code coverage decrease.
Links:
- https://codecov.io/
- [Python example](https://github.com/codecov/example-python)

**Comment by AraHaan** [comment]
I had to remake https://github.com/KeepSafe/aiohttp/pull/1507 because of a merge issue it now is: https://github.com/KeepSafe/aiohttp/pull/1518

**Comment by andriisoldatenko** [comment]
@technige Please review.

**Comment by technige** [comment]
Checking it out now.

**Comment by technige** [comment]
Looks good -> https://github.com/technige/py2neo/pull/591

However, within a Travis job for a particular version of Python, all Neo4j versions are tested end-to-end. For each, coverage can vary as the library is exercised in different ways. From which of these would the figure be generated? The last one to run?

**Comment by AraHaan** [comment]
The coverage is obtained by having tests that are not tracked by Codecov. And I don't know it seems it does an average of all the python versions it uses. It might be the last one idk for sure.

**Comment by technige** [comment]
This is now live.
