### ISSUE TITLE
Add a neo4j procedure call at the end of a 'graph.select' query

### ISSUE THREAD

**Issue by dan-kez** [technige/py2neo#592]
Hello!

First, thank you so much for developing this incredible tool. It has made neo4j far more useful and accessible (at least to me). In fact, I'm in the process of porting my microservice from node to python specifically because of py2neo. 

That said, I'm running into an issue for one of my most common use cases. I have a couple procedures defined in Neo4j. These procedures run (potentially) complex, optimised traversals and set labels on given nodes depending on the result. It's important for my use case to run these traversals whenever I request a given node so that its labels are always correct. 

Is there a way to add call a function at the end of a graph.select / graph.find function calls? An example query is below:

```
MATCH (n:Permission) 
CALL foo.userProc(n)
RETURN n
```

**Comment by dmk255** [comment]
So I found a way around this. It's very hacky but it works. 

```
Permission.select(graph).where("true CALL foo.userProc(_)")
```
Results in the query
```
MATCH (_:Permission) WHERE true CALL foo.userProc(_) RETURN _
```

It'd be nice to have an option like `Permission.select(graph).where("...").appendQuery("...")` so you don't have to the above hack.
