### ISSUE TITLE
OGM Feature: Relationship properties in class definition

### ISSUE THREAD

**Issue by dan-kez** [technige/py2neo#600]
At present you can add relationship properties to an OGM GraphObject when calling `node.rel_set.add(node, {obj})`. This is very useful, however it would be very nice if it was possible to predefine what properties are required for a given relationship on instantiation.

See the example below
```
class Movie(GraphObject):
    name = Property()
    actors = RelatedFrom(Actor, ActedIn)

class Actor(GraphObject):
    acted_in_movies = RelatedTo(Movie, ActedIn)

class ActedIn(GraphRelationship):
   year = Property()
```

**Comment by shubhamyedage** [comment]
Hii, How you connect two nodes?
