### ISSUE TITLE
create_unique -> merge?

### ISSUE THREAD

**Issue by phoebebright** [technige/py2neo#608]
I have just upgraded from v2. to v3 and find that create_unique has gone.
Would I be right in thinking that I can use merge where I was previously using create_unique?

**Comment by wgwz** [comment]
Just out of curiosity are you using ogm? From what I have read in the docs on merge operations they preserve uniqueness through the primarylabel and primarykey. http://py2neo.org/v3/ogm.html#py2neo.ogm.Graph.merge

**Comment by phoebebright** [comment]
No, I'm using neomodel with django, but I'll check that out.  Thanks.

**Comment by technige** [comment]
Yes, `merge` replaces `create_unique`.
