### ISSUE TITLE
Error with parameterized queries with { character

### ISSUE THREAD

**Issue by csweaver** [technige/py2neo#613]
Trying to run this query:

    result = db.run("Match (s:Sample)-[]-(p:Project) where p.name={project_name} and s.line=~{line_name} and s.reporter =~ {reporter}  return s.id as id",
                    project_name=project_name, line_name=".*" + line_name + ".*", reporter=".*" + reporter + ".*")

Where the value of reporter is "pJFRC32-10XUAS-IVS-nlsGFP (attP18) / VALIUM20P{TRiP.HMC03585}attP40(UAS-gluclalpha RNAi) " 

Gets this error:

---------------------------------------------------------------------------
DatabaseError                             Traceback (most recent call last)
<ipython-input-32-e9a367ce2de1> in <module>()
     27                 print(ids)
     28                 result = db.run("Match (s:Sample)-[]-(p:Project) where p.name={project_name} and s.line=~{line_name} and s.reporter =~ {reporter}  return s.id as id",
---> 29                     project_name=project_name, line_name=".*" + line_name + ".*", reporter=".*" + reporter + ".*")
     30                 for x in result:
     31                     print(x)

/Users/weaverc10/miniconda2/envs/py3/lib/python3.5/site-packages/py2neo/database/__init__.py in run(self, statement, parameters, **kwparameters)
    729         :return:
    730         """
--> 731         return self.begin(autocommit=True).run(statement, parameters, **kwparameters)
    732 
    733     def separate(self, subgraph):

/Users/weaverc10/miniconda2/envs/py3/lib/python3.5/site-packages/py2neo/database/__init__.py in run(self, statement, parameters, **kwparameters)
   1275         self.sources.append(source)
   1276         if self.autocommit:
-> 1277             self.finish()
   1278         return Cursor(source)
   1279 

/Users/weaverc10/miniconda2/envs/py3/lib/python3.5/site-packages/py2neo/database/__init__.py in finish(self)
   1294 
   1295     def finish(self):
-> 1296         self._sync()
   1297         Transaction.finish(self)
   1298         self.session.close()

/Users/weaverc10/miniconda2/envs/py3/lib/python3.5/site-packages/py2neo/database/__init__.py in _sync(self)
   1284             source = self.sources.pop(0)
   1285             while not source.loaded:
-> 1286                 connection.fetch()
   1287 
   1288     def _post(self, commit=False):

/Users/weaverc10/miniconda2/envs/py3/lib/python3.5/site-packages/py2neo/packages/neo4j/v1/bolt.py in fetch(self)
    342                 pass
    343             else:
--> 344                 handler(*fields)
    345         raw.close()
    346 

/Users/weaverc10/miniconda2/envs/py3/lib/python3.5/site-packages/py2neo/database/__init__.py in on_failure(self, metadata)
    959         :param metadata:
    960         """
--> 961         raise GraphError.hydrate(metadata)
    962 
    963     def rehydrate(self, obj, inst=None):

DatabaseError: Illegal repetition near index 47
.*pJFRC32-10XUAS-IVS-nlsGFP (attP18) / VALIUM20P{TRiP.HMC03585}attP40(UAS-gluclalpha RNAi).*

Am I wrong in thinking that a parameterized query should automatically escape special characters?

**Comment by technige** [comment]
Parameter values are escaped inasmuch as the Cypher query itself is concerned but the driver is unable to tell the difference between regular string parameters and string parameters that are intended to be used as regular expressions.

Regular expressions in Cypher rely on a separate, embedded parser. Curly brackets have specific meaning in this context, for example `a{3}` matches `aaa`. Therefore, you'll need to escape your curly brackets explicitly (which occur at index 47, as per the error message).
