### ISSUE TITLE
cannot change bolt port

### ISSUE THREAD

**Issue by ShaharKatz** [technige/py2neo#615]
Although I attempted to change the bolt port using:
```

authenticate(bolt_url_strippted + ":24786", username, password)
g = Graph(
          host=bolt_url_strippted,
          bolt=True,
          bolt_port=24786,
          user=username,
          password=password)
g.begin()
```

I get the following error:
`
py2neo.packages.neo4j.v1.exceptions.ProtocolError: Unable to connect to <server>.dbs.graphenedb.com on port 7687 - is the server running?`

I have successful connected to the server using a different python driver with the custom port. I am using py2neo ver 3.1.2, Neo4j version 3.0.8 via GrapheneDB

Thanks,

SK

PS - corresponding StackOverflow - 
http://stackoverflow.com/questions/42556012/py2neo-cannot-change-bolt-port

**Comment by l85m** [comment]
We're also seeing this. Any idea how to fix?

**Comment by pvanheus** [comment]
Fixed in in release 4.0.0b2 that is on pypi (for me at least). Not sure which commit fixed this, but it was, it seems, before the v3 branch was created in the code because the problematic code is not in that branch.

**Comment by technige** [comment]
The port issue should be resolved in the latest v4 betas.

**Comment by technige** [comment]
v4 has now been released - this should now be working.
