### ISSUE TITLE
how can I add different relationships between objects?

### ISSUE THREAD

**Issue by Mambix** [technige/py2neo#616]
I have two Nodes created with classes from GraphObject

lets say Nodes n1, n2

so what I now want is add more than one ralationship
so this will save the relationship.
```
n1.relationship.update(n2, properties={'var':'val1', 'timestamp': time.time()}
graph.create(n1)
```

But I also wan't to add more, for example
```
n1.relationship.update(n2, properties={'var':'val2', 'timestamp': time.time()}
graph.create(n1)
```

So this is going to override the first one.
Is there any way to tell the library I wan't relationships stored so that certain key:value pairs remain unique? In the above case when I pass `val1` for `var` it will update other properties.
But if I pass `var`:`val2` it will keep `val1` and create new one because it does not exist.

it would be handy if you could do it like this:
```
n1.relationship.update(n2, properties={'var':'val1', 'timestamp': time.time()}
graph.create(n1)
```

But I also wan't to add more, for example
```
n1.relationship.update(n2, properties={'var':'val1'}, timestamp=time.time())
n1.relationship.update(n2, properties={'var':'val2'}, timestamp=time.time())
graph.create(n1)
```
This would create two relationships with `timestamp` and `val` properties. And it would decide what relationship to create/override only on key/value pairs of what you pass in properties dictionary

**Comment by croccam** [comment]
I hope I understood your issue. Have you taken a look at graph.push(), RelatedTo() and RelatedFrom()?

If you want to store the same relationship (the same entity) but with different properties (which is what I understood) maybe you could design another scheme for your graph.

**Comment by Mambix** [comment]
I want to store same relationship, but with different properties yes. I will try with multiple schemes.

But it would be good if this would be supported automatically. What if there is a more dynamic set of attributes. You don't want to maintain a ton of schemes for every possible scenario.
