### ISSUE TITLE
OGM doesn't work with GrapheneDB

### ISSUE THREAD

**Issue by savvopoulos** [technige/py2neo#623]
Getting a model works, but getting related objects doesn't.

The problem seems to be that the graph driver cannot connect the database - the port seems to be off. For the snippet below, I see that when I try to iterate over c.employees, py2neo connects to this address: ('db-abc.graphenedb.com', 7687) which seems to be off.

```
from py2neo import Graph, authenticate
import time

from py2neo.ogm import GraphObject, Property, RelatedFrom, RelatedTo
from urllib.parse import urlparse

class Company(GraphObject):
    __primarykey__ = 'domain'
    domain = Property()
    employees = RelatedFrom('Person', 'WORKS_AT')

class Person(GraphObject):
    __primarykey__ = 'uuid'
    uuid = Property()

url = urlparse('https://app123-user:pass@db-abc.graphenedb.com:24780')
authenticate(url.hostname + ":24780", url.username, url.password)
g = Graph(\
    "bolt://" + url.hostname + ":24786", user=url.username, password=url.password,\
    bolt=True, secure = True, http_port = 24789, https_port = 24780)
c = Company.select(g, 'scandit.com').first()
print(c)
for r in c.employees:
    print(r)
```

**Comment by pvanheus** [comment]
This de-facto hardcoding of the port is related to #615. Can you test with py2neo v. 4.0.0b2?

**Comment by wgwz** [comment]
Are you still hitting this issue? Or can this be closed?

**Comment by technige** [comment]
The port issue should be resolved in the latest v4 betas.

**Comment by technige** [comment]
Closing this issue as this should be fixed in v4.
