### ISSUE TITLE
get_or_create_indexed_node not working

### ISSUE THREAD

**Issue by zhouhoo** [technige/py2neo#624]
I am using neo4j3.1.2 ,py2neo 3.1.2 on ubuntu14.04.

in my test, I want to use `get_or_create_indexed_node` function to insert  or get a index node in db. 
however it fail without any error message.  I just got empyt and db is also empty. which confused me a lot . here is my code piece.

```
from py2neo.ext.batman import ManualIndexManager

def getConception(self,node):
        cc=ManualIndexManager(graph).get_or_create_indexed_node('conception','conceptID',node)
        print(dict(cc))

        return cc
```

the above code print {}, nothing but empty .

but, when I use follwing code to insert node ,it work well.

```
def addNode(self,node):
        c=self.find(node)
        if not c:
            cc = Node('conception',conceptID=node)
            return graph.create(cc)
        else:
            return c
```

**Comment by wgwz** [comment]
Hi, there. If this is still an issue for you, can you show a minimal example that reproduces the issue?

**Comment by technige** [comment]
The batch functionality is very old and, in some places, broken. I recommend upgrading to py2neo v4 and using transactions instead.

**Comment by zhouhoo** [comment]
@technige thanks
