### ISSUE TITLE
ogm feature request: all method of a select query

### ISSUE THREAD

**Issue by wgwz** [technige/py2neo#626]
getting all of a certain node is currently:

    list(Employee.select(graph))

could mirror sqlalchemy as:

    Employee.select(graph).all()

it would be nice to have

**Comment by technige** [comment]
Given that this API isn't intended to mirror SQLAlchemy, what would be the benefit here?

The `.all()` method always returns a list. This seems less flexible and less Pythonic than wrapping in something like `list`. With the current API, you can just as equally use `list(Employee.select(graph))`, `set(Employee.select(graph))` or any other consumer of the iterable. You could even begin to iterate and then stop after a limit.

I guess it's probably all quite subjective.

**Comment by wgwz** [comment]
I can agree with that. But as someone who started with sqlalchemy, I half expected it to be there? I just wanted to raise this issue thinking, that others from the same background might think the same. But I agree it's probably better to be more explicit with list or set. I had not thought of it that way. In fact there's probably another reason the all method exists in sqlalchemy, other than just a convenience (which is how I have thought of it). It might actually be for when data gets loaded? Anyway, closing for now.
