### ISSUE TITLE
ogm feature request: first and all methods on a relationship returning nodes

### ISSUE THREAD

**Issue by wgwz** [technige/py2neo#627]
not sure if this is possible with how the ogm is working but IMO it would be nice to have

example:

    nodes = Client.select(db.graph).where("_.id='cliemail'").first().has_onboard

currently doing this: 

    list(nodes)

> [\<Onboard __id__=33\>]

but i'd like to have these: 

    nodes.all() 

> [\<Onboard __id__=33\>]

    nodes.first()

> \<Onboard __id__=33\>

**Comment by wgwz** [comment]
This is similar to the other issue I opened. I'll have to think about it some more.

**Comment by nunenuh** [comment]
does pull request is allowed or how contribution is made?

**Comment by technige** [comment]
These functions are provided by the matcher classes:
https://py2neo.org/v4/matching.html
