### ISSUE TITLE
Documentation for cursor.current.

### ISSUE THREAD

**Issue by mark-meyer** [technige/py2neo#628]
I am reading the docs here: http://py2neo.org/v3/database.html#cursors

I am getting errors when I try to use the example code like this:
```
if cursor.forward():
    print(cursor.current["name"])
```
The error I'm receiving is:
`TypeError: 'method' object is not subscriptable`

When I look at the source, `current()` looks like a simple function that returns and object, so I'm not sure how the documented usage can work. I've found this works as expected:
` print(cursor.current()["name"])`

Am I doing something wrong or is there a problem with the docs?

**Comment by wgwz** [comment]
It's an issue with the docs. Are you interested in submitting the PR?

**Comment by technige** [comment]
The docs are now aligned with the API on this.
