### ISSUE TITLE
Release without or with newer neo4j-driver

### ISSUE THREAD

**Issue by papachoco** [technige/py2neo#633]
Hello,

Currently py2neo 4.0.0b2   requires neo4j-driver==1.1.0rc1 ; however looking at master the neo4j-driver  dependency is gone. Could we get a new small release on pypi that either removes the neo4j-driver dependency or does not pin us to neo4j-driver 1.1.0rc1 (latest release of neo4j-driver is 1.4.0)

Thanks a lot

Carlos

**Comment by technige** [comment]
The new betas are using up-to-date versions of the official driver.
