### ISSUE TITLE
Queried relationship got different properties values than neo4j web browser ones

### ISSUE THREAD

**Issue by ehupin** [technige/py2neo#634]
Querying for relationship with py2neo, I noticed that returned properties values from relationships are different from neo4j web browser ones.

After a look in the code, it seems that the problem occurs in the cache update called by hydrate. 

In types.py (line 988)
```
    def hydrate(cls, data, inst=None):
        self = data["self"]
        start = data["start"]
        end = data["end"]

        if inst is None:

            def inst_constructor():
                return cls(Node.hydrate({"self": start}), data.get("type"),
                           Node.hydrate({"self": end}), **data.get("data", {}))

            inst = cls.cache.update(self, inst_constructor)
```
If I call the inst_constructor by myself, I got the right property values from the returned instance. However, if I check values in the instance from cls.cache.update(...), values are wrong, but it is this instance that is returned.

I'm not skilled enought to help for code correction, but I hope this issue report will be noticed by a better skilled develloper :)

**Comment by ehupin** [comment]
I've "corrected" the problem modifying the update method in caching.py. For sure it's not a clean solution, but it works and could give a hint to really solve this problem!
```

    def update(self, key, value):
        """ Extract, insert or remove a value for a given key.
        """
        with self.lock:
            if value is None:
                # remove
                try:
                    del self._dict[key]
                except KeyError:
                    pass
                else:
                    return None
            elif callable(value):
                # Here I forced the new instance creation
                new_value = value()
                self._dict[key] = new_value
                return new_value
            else:
                # insert or replace
                self._dict[key] = value
                return value


```

**Comment by wgwz** [comment]
Can you provide a minimal example that reproduces the problem? Including python and py2neo versions, thanks! That will help others debug and make recommendations

**Comment by technige** [comment]
I'm unable to simulate the problem with the current code. Please reopen if this is still an issue, and if a code snippet is available.
