### ISSUE TITLE
ETA Release

### ISSUE THREAD

**Issue by papachoco** [technige/py2neo#638]
Hello,

I was just wondering if there is an ETA for py2neo 4.0+

Thanks,

Carlos

**Comment by lifan0127** [comment]
It seems the development for py2neo has not been active lately. The main contributor @technige has shift his focus to https://github.com/neo4j/neo4j-python-driver. Is it still a good idea to use py2neo for new project? Or should we use neo4j-python-driver instead?

**Comment by wgwz** [comment]
See #631 as well. Some months back @technige presented some good ideas on how to proceed with py2neo. But it would seem like he hasn't had the time.

I would say carefully consider the features you need and make the choice that way. If you are planning to build you models with cypher, you might be better off just using the driver. 

But if you want to work with an OGM then you might be better off using py2neo. Fwiw I have found the important portions of the library to be pretty stable.

**Comment by lifan0127** [comment]
My preference is to use OGM APIs. I used to implement my own version of "OGM" on top of cypher until py2neo V3 came out. I have since abandoned my implementation and switched to py2neo OGM. I sincerely hope its development will continue.

**Comment by technige** [comment]
V4 RC1 was released a few days ago. Barring any major problems, this will go GA later this week.

**Comment by technige** [comment]
v4 has now been released
