### ISSUE TITLE
Transaction.run() code is missing(!)

### ISSUE THREAD

**Issue by Alan-R** [technige/py2neo#639]
This appears to be all there is of that code:

    def run(self, statement, parameters=None, **kwparameters):
        """ Send a Cypher statement to the server for execution and return
        a :py:class:`.Cursor` for navigating its result.
        :param statement: Cypher statement
        :param parameters: dictionary of parameters
        :returns: :py:class:`.Cursor` object
        """

And that's it. Nice function documentation, but the code itself seems to be missing.

**Comment by technige** [comment]
`Transaction` is a base class extended by `HTTPTransaction` and `BoltTransaction`. The `run` method is therefore not empty but abstract and is realised by the two concrete classes.

**Comment by Alan-R** [comment]
OK. Is there a factory function that will construct the appropriate kind of transaction depending on which kind of connection has been negotiated?

**Comment by Alan-R** [comment]
Also, maybe the abstract class should raise a NotImplementedError()?

**Comment by Alan-R** [comment]
The more I re-read the documentation, the more I realize I misread or misunderstood it. But for those who are thick-headed like I seem to be, the NotImplementedError("Use begin() to construct an appropriate type of Transaction") would make sense.

My apologies for being so thick-headed.
