### ISSUE TITLE
Subgraph() has some problem!

### ISSUE THREAD

**Issue by zk-wannng** [technige/py2neo#642]
with i got a set, which contain nodes and relationships, and a pass it to Subgraph(), i got a subgraph, but relationships are not reconnized correctly, and raise error. if i use Subgraph | relations, it works well.
what's the problem?
when Subgraph() receive a set, it should recognize what is nodes, what is relations. o_O

**Comment by zk-wannng** [comment]
I got the reason, cause there were two parameters.
but, the doc were bad and the error message are confusing...

**Comment by technige** [comment]
That's not how `Subgraph` works. It's constructor is based on the _G = (V, E)_ notation.

I'm not sure I understand how the docs fail to communicate this...

```
class py2neo.data.Subgraph(nodes, relationships)
    A Subgraph is an immutable set of nodes and relationships that can be provided as an
    argument to many graph database functions. It is also the base class for Node, Relationship
    and Walkable, allowing instances of those classes to be combined using set operations.
```

http://py2neo.org/v4/data.html#py2neo.data.Subgraph
