### ISSUE TITLE
Support of multiple labels in ogm

### ISSUE THREAD

**Issue by rescuehero** [technige/py2neo#651]
I was asking myself if it is possible to create a node with different labels with the ogm in py2neo.

cypher:

```
CREATE(n:label1:label2{name:'testname'})
RETURN n

```
py2neo ogm:

```
class label(GraphObject):
    __primarykey__ = "name"

    name=Property()

templabel=label()
templabel.name='testname'
graph.push(templabel)
#graph got initialized with graph=graph()

```
As you can see, the classname is defined as the labelname.

Kind regards,
resc

**Comment by technige** [comment]
Yes, labels can be added to an object using the `Label` class in the same way that `Property` attributes are added. They then surface as a boolean.

I note though that the docs don't give an example. There are examples in the text fixture file though which may be useful:
https://github.com/technige/py2neo/blob/v4/test/fixtures/ogm.py

**Comment by rescuehero** [comment]
thank you :)
