### ISSUE TITLE
inconsistent data returned

### ISSUE THREAD

**Issue by jasonnet** [technige/py2neo#653]
I'm seeing a situation where my python code (using py2neo 3.1.2) queries an edge in the database (returning a value of "onetype"), then updates the property on that edge to "twotype", and then queries that edge again.   I expect the second query to show the updated property value, but in most cases it shows the prior value.  -- FWIW the apps is a Flask server app.  And if another HTTP client submits a request, it will see the updated value even before the process above surprisingly returns the original value.

If I use watch("neo4j.bolt") and cursor.data() to debug this final query call, I see:

```
C: RUN '\n            MATCH (user:User_Test)-[rating:RATED_Test]->(r6e:R6e_Test)\n            WHERE (r6e.id = {r6e_id}) AND (user.username={username})\n            RETURN user, r6e, rating\n            ORDER BY rating.timestamp_valid DESC\n            ' {'username': 'testing_admin22', 'r6e_id': '576e69bb-b73f-4f48-9064-5d1448d66a1d'}
C: PULL_ALL
S: SUCCESS {'fields': ['user', 'r6e', 'rating'], 'result_available_after': 1}
S: RECORD [(b'N', (2850, ['User_Test'], {'username': 'testing_admin22', 'password': '$2a$12$ZCcVOWjmD0VWjS.K8YQAruSrK3y5mQTV5sQ.yBay/y5VMKVZddk2.', 'id': 'bbe66526-59b0-4eb0-a050-7ad2aa38f76a'})), (b'N', (4502, ['R6e_Test'], {'s7t_authorid': 'bbe66526-59b0-4eb0-a050-7ad2aa38f76a', 's7t_title_ref2': '', 'timestamp_last': 1520112470.163467, 'verdict_by_author': '2', 'other_verdict_text': '', 'text': 'title1', 'rating_sum': 2, 'this_authorid': 'bbe66526-59b0-4eb0-a050-7ad2aa38f76a', 'title': 'title1', 'id': '576e69bb-b73f-4f48-9064-5d1448d66a1d', 'rating_count': 1, 'published': True, 'timestamp': 1520112470.139383, 's7t_title_ref1': 'title1', 'nversion': 1, 'parent_authorid': 'bbe66526-59b0-4eb0-a050-7ad2aa38f76a', 'date': '2018-03-03'})), (b'R', (2853, 2850, 4502, 'RATED_Test', {'rated_s7t_nversion': 1, 'influence_level': 2, 'explanation': 'explanationtwo', 'rated_r6e_nversion': 1, 'issue_code': 'twotype', 'next_hx_id': 0, 'timestamp': 1520112479345}))]
S: SUCCESS {'result_consumed_after': 0, 'type': 'r'}
og/models.py( 1271):  [{'rating': (ce0fdac)-[:RATED_Test {explanation:"explanationone",influence_level:1,issue_code:"onetype",next_hx_id:0,rated_r6e_nversion:1,rated_s7t_nversion:1,timestamp:1520112474763}]->(ff7615b), 'r6e': (ff7615b:R6e_Test {date:"2018-03-03",id:"576e69bb-b73f-4f48-9064-5d1448d66a1d",nversion:1,other_verdict_text:"",parent_authorid:"bbe66526-59b0-4eb0-a050-7ad2aa38f76a",published:true,rating_count:1,rating_sum:2,s7t_authorid:"bbe66526-59b0-4eb0-a050-7ad2aa38f76a",s7t_title_ref1:"title1",s7t_title_ref2:"",text:"title1",this_authorid:"bbe66526-59b0-4eb0-a050-7ad2aa38f76a",timestamp:1520112470.139383,timestamp_last:1520112470.163467,title:"title1",verdict_by_author:"2"}), 'user': (ce0fdac:User_Test {id:"bbe66526-59b0-4eb0-a050-7ad2aa38f76a",password:"$2a$12$ZCcVOWjmD0VWjS.K8YQAruSrK3y5mQTV5sQ.yBay/y5VMKVZddk2.",username:"testing_admin22"})}]
```
As you can see, the Py2Neo seems to be receiving the updated value ("twotype") from the server, but it is passing the old value ("onetype")  up to the app as you can see rendered by cursor.data().

This looks like a bug to me.   Is there an explanation for this that is not a bug?

**Comment by technige** [comment]
Can you show some code?

**Comment by db-eatii** [comment]
I can confirm experiencing the same behaviour. Hopefully below helps clarify it a bit better...

- OSX 10.13.6
- py2neo==4.2.0
- Python 3.6.5
- using cypher statements with `graph.run(cypher)` to create many relationships of the same kind (but with different properties on each) between two nodes
- i've tried to create a generic method for creating these "structured" relationships which uses a combination of string formatting, and the `cypher.run()` ability to pass in parameter dictionaries
- creating these structured relationships is no problem, the issue occurs only when matching one, and then updating it
- in this situation the update is successful in neo4j, but the response returned from any subsequent matches in py2neo shows the original version
- it doesn't seem to be a time issue as i've built in manual pauses and confirmed the update has occurred. Even checked this using transactions and confirming through py2neo that the transaction has finished

code below:

`class StructuredRelationship(object):
	__graph = get_graph()

	def __init__(self, start_node, end_node, model):
		self.start_node = start_node
		self.end_node = end_node
		self.model = model

	def create(self):
		# TODO add in a constraint validation
		if self.model.id is None:
			raise GraphConstraintError('The relationship model id cannot be None for a StructuredRelationship')

		if self.start_node.__primarylabel__ != self.model.start_node_label:
			raise GraphConstraintError(
				'start_node.__primarylabel__ must be "{label}"'.format(label=self.model.start_node_label))

		if self.end_node.__primarylabel__ != self.model.end_node_label:
			raise GraphConstraintError(
				'end_node.__primarylabel__ must be "{label}"'.format(label=self.model.end_node_label))

		create_properties = vars(self.model)

		cypher = """
					MATCH (a:{start_primary_label}), (b:{end_primary_label})
					WHERE a.{start_primary_key} = '{start_id}'
					AND b.{end_primary_key} = '{end_id}'
					CREATE p=(a)-[r:{relationship_type}]->(b)
					SET r.{relationship_primary_key} = '{relationship_id}'
					SET r = {{properties}}
					RETURN p
					""".format(start_primary_label=self.start_node.__primarylabel__,
							   start_primary_key=self.start_node.__primarykey__,
							   start_id=self.start_node.id,
							   end_primary_label=self.end_node.__primarylabel__,
							   end_primary_key=self.end_node.__primarykey__,
							   end_id=self.end_node.id,
							   relationship_type=self.model.r_type,
							   relationship_primary_key=self.model.primary_key,
							   relationship_id=self.model.id)
		self.__graph.run(cypher, properties=create_properties)

	def update(self):
		update_properties = vars(self.model)

		tx = self.__graph.begin()
		cypher = """
					MATCH p=(a:{start_primary_label})-[r:{relationship_type}]->(b:{end_primary_label})
					WHERE a.{start_primary_key} = '{start_id}'
					AND b.{end_primary_key} = '{end_id}'
					AND r.{relationship_primary_key} = '{relationship_id}'
					SET r = {{properties}} 
					RETURN p
					""".format(start_primary_label=self.start_node.__primarylabel__,
							   start_primary_key=self.start_node.__primarykey__,
							   start_id=self.start_node.id,
							   end_primary_label=self.end_node.__primarylabel__,
							   end_primary_key=self.end_node.__primarykey__,
							   end_id=self.end_node.id,
							   relationship_type=self.model.r_type,
							   relationship_primary_key=self.model.primary_key,
							   relationship_id=self.model.id)
		tx.run(cypher, properties=update_properties)
		tx.commit()`

I've used both the `RelationshipMatcher` and standard cypher statements to match these nodes. They match successfully but do not return the updated properties. However, if you re-run the application the matched relationship _does_ show the updated properties. Not sure what is going on...

**Comment by technige** [comment]
Py2neo does not support multiple relationships of the same type between the same two nodes. This is due to how relationship equality is determined. For details...

https://py2neo.org/v4/data.html#py2neo.data.Relationship

This divergence from Neo4j itself is deliberate.
