### ISSUE TITLE
Only URI, not all initial settings, saved and used in graph_service()

### ISSUE THREAD

**Issue by nickw17** [technige/py2neo#654]
I was encountering a problem where the connection to the server would appear to close frequently.  I found that when the OGM would create a remote version of a node, used for follow-up pulls from the database, it would not save and use the full set of settings initially provided to connect to the graph.  It would retain and use only the provided host and http port (i.e. a URI), but not the username, password, or bolt selection.  So whenever I would make a call that would cause the node object to make a follow-up call to the database, it would fail due to an authentication error, although the error message described it as the server “closed the connection.”

I have worked around it by overriding py2neo.http.Remote.graph_service() to use the full set of settings, i.e.:

```
global settings
self._graph_service = GraphService(**settings)
```

where I set the settings outside the function.  This is clearly a hack, but it seems to have addressed the problem for now.

**Comment by technige** [comment]
Can you try in v4 RC1?

**Comment by technige** [comment]
Closing, as this code has been removed in v4.
