### ISSUE TITLE
can't use Graph.data('cypher')?

### ISSUE THREAD

**Issue by tzungtzu** [technige/py2neo#658]
when I use it, the error is 'Graph' object has no attribute 'data',

but i can use Graph.run(), how can I get data from the graph?

Thanks

**Comment by technige** [comment]
Assuming you're using v3, You should be able to use the `data` method on a `Graph` instance, e.g.:
```
>>> g = Graph()
>>> foo = g.data("UNWIND range(1, 10) AS n RETURN n")
```
Alternatively, you can use `run` and then `data` on the returned `Cursor`:
```
>>> g = Graph()
>>> foo = g.run("UNWIND range(1, 10) AS n RETURN n").data()
```

**Comment by technige** [comment]
The `Cursor.data()` method is available in v4 RC1.

**Comment by technige** [comment]
For `Graph.data(...)`, now use `Graph.run(...).data()`

**Comment by ghmc91** [comment]
Graph.data() has been deprecated?
