### ISSUE TITLE
How to delete node in batch?

### ISSUE THREAD

**Issue by imnujf** [technige/py2neo#660]
1000000 Nodes, how to delete them in batch?

**Comment by imnujf** [comment]
Three labels in my graph, 'A', 'B', ‘C’，They all have 100000 Nodes，I want to remove all Nodes with label 'A', how to do this in batch, please?

**Comment by imnujf** [comment]
my neo4j version is 3.3.4

**Comment by technige** [comment]
You'll need a Cypher statement like `MATCH (n:A) DELETE n`.
