### ISSUE TITLE
Version 3.1.2 gets installed with latest pip

### ISSUE THREAD

**Issue by RichStone** [technige/py2neo#665]
On my Mac Sierra with

```
$ pip --version
>> pip 10.0.1
```

When trying the bleeding edge version installation command from the documentation
`pip3 install git+https://github.com/technige/py2neo.git#egg=py2neo`
I get 

> Requirements satisfied

 respond

Is all of this the desired behavior? 

P.S.: 
`pip3 install git+https://github.com/technige/py2neo.git#egg=py2neo --upgrade`
gets py2neo to upgrade to version 4.0.0b12, which is the latest **(unstable) version**, I suppose ?

**Comment by technige** [comment]
Now that v4 has been released, you should get v4 with a regular install.
