### ISSUE TITLE
4.0.0b12 ignoring uri parameter

### ISSUE THREAD

**Issue by robjampar** [technige/py2neo#666]
The uri parameter for a call to class Graph() is being ignored and 127.0.0.1:7687 is always being used

problem is from **line** **150** in **py2neo/data.py**,

as far as i can tell...

`return graph(uri=None, **settings)`

should be

`return graph(uri=uri, **settings)`

**Comment by technige** [comment]
This has been fixed in RC1. The whole block of experimental code that contained this has actually been completely removed. Thanks for pointing it out.
