### ISSUE TITLE
OGM with custom property

### ISSUE THREAD

**Issue by kororo** [technige/py2neo#667]
Hi all,

I am new using this awesome library, I am bit puzzle on this particular function. It seems fishy.

https://github.com/technige/py2neo/blob/f83bca014064ac6a477f4a65e2f6fe9291ab9875/py2neo/ogm.py#L333-L342

What I am trying to achieve, is here:
```
from py2neo import Graph
from py2neo.ogm import GraphObject, Property


class TestObject(GraphObject):
    __primarykey__ = 'name'
    name = Property()

    @property
    def test_property(self):
        # this is very expensive process
        return 'DATA'


graph = Graph()
test = TestObject()
test.name = 'test'
graph.push(test)

# this code will call test_property
test.select(graph).where({'name': 'test'})
```

The function "where", call "wrap" function and eventually call: https://github.com/technige/py2neo/blob/f83bca014064ac6a477f4a65e2f6fe9291ab9875/py2neo/ogm.py#L340-L341

It does getattr to nothing. Is this intended?

Thanks
Rob

**Comment by technige** [comment]
Thanks for pointing this out. I don't recall why those lines were added in the first place, probably to bootstrap the property accessors, but they are now redundant and have been removed in RC1.
