### ISSUE TITLE
TypeError: Values of type neotime.Date are not supported

### ISSUE THREAD

**Issue by elena** [technige/py2neo#668]
Some clever-pants newb had to go start using the new-fangled "Date" type introduced in Neo4j 3.4.0 (https://neo4j.com/blog/neo4j-graph-database-3-4-ga-release/)

This started as error: 
`TypeError: Values of type neotime.Date are not supported`

After some small chatting with @technige and having a look the problem is occurring here:
https://github.com/technige/py2neo/blob/v4/py2neo/cypher/__init__.py#L187

Upon making it clearer the TypeError is specifically:
`TypeError: Can't convert 'Date' object to str implicitly`

The genesis of this error may be some where in here, the why this is occurring is not obviously forthcoming:
https://github.com/technige/neotime/blob/master/neotime/__init__.py#L774

The immediate issue is that it causes reference to specific `node` which uses "new" 3.4.0 `neotime.Date` property value to raise a `TypeError` so these nodes have to be avoided for the graph to be functional using the current version, whereas passing more gracefully will allow graphs which are using this new-fangled type.

**Comment by elena** [comment]
Will commit my workaround. It's stupid simple, but stops it exploding.

**Comment by elena** [comment]
Ack, workaround also introduces `neotime` as dependency, although it's installed down-the-line anyway it feels like the wrong thing to do. It does keep it simple, but just doesn't seem nice.

**Comment by elena** [comment]
nektminnit hit same for `TypeError: Values of type neotime.DateTime are not supported`

Adding workarounds for `Time`, `Date` and `DateTime` locally. 

Other "special" classes created in `neotime` seem to be `Clock`, `ClockTime` and `Duration`. 
See: https://github.com/technige/neotime/blob/master/neotime/__init__.py

Though I'm never going need these (and other famous last words).

**Comment by technige** [comment]
Thanks @elena - I'm back home now so can take a look over the next few days. Could you share a bit of code I could build a test upon please?

**Comment by technige** [comment]
Oh, and `Clock` and `ClockTime` are entirely "internal" to `neotime`. Though `Duration` will also be relevant.

**Comment by technige** [comment]
Added the label as per our off-GitHub conversation.
