### ISSUE TITLE
py2neo cannot run shortestpath function

### ISSUE THREAD

**Issue by Duanexiao** [technige/py2neo#670]
graph = Graph('http://xxx:7687',username="neo4j",password="xxx",bolt=False)
graph.run("match p = shortestPath((m)-[:has*..2]-(n)) where n.uid = 219733632 and m.uid = 140860476 return p")
this code raise below error:
py2neo.packages.neo4j.v1.exceptions.ProtocolError: Server responded HTTP. Make sure you are not trying to connect to the http endpoint (HTTP defaults to port 7474 whereas BOLT defaults to port 7687)

is it the reason of graph connection method leading to this error?
looking foraward your replying, many thanks!

**Comment by technige** [comment]
This is nothing to do with shortestPath. The solution is actually spelt out in the error message: you have a port/protocol mismatch.

HTTP runs on port 7474, Bolt runs on port 7687. You are mixing http and 7687 in the same URI.

**Comment by Duanexiao** [comment]
thank you for your replying.But I do not agree with your words.When I use http connection to run other select command,it's ok.Only the shortestPath command,raises that error.And I have changed many configure in the neo4j.conf file
