### ISSUE TITLE
Matching CypherLexer comments correctly

### ISSUE THREAD

**Issue by jurrian** [technige/py2neo#671]
Currently the CypherLexer fails to match comments in the right way.

At this time, the regex for one line comments is defined as:
https://github.com/technige/py2neo/blob/ba149481975efe859339b760e7264be20304ba40/py2neo/cypher/lexer.py#L382

However, when the lexer tries to match that to this it will match the entire string instead:
```SET o:`http://example.org` // This is a comment```

The solution to this problem is to set the regex for single comments to `r'//.*\n'`.
In my experience, this works well for multiple scenario's.

**Comment by technige** [comment]
@jurrian Would you mind reviewing the commit, please? To check it works for you. Thanks :)

**Comment by technige** [comment]
Oh, and reopen if necessary.

**Comment by jurrian** [comment]
I see this creates two comment tokens, I guess this was intentional?
Anyway, I can live with that.

Below the output of `get_tokens()` on the example I provided earlier:
```(Token.Comment.Single, u'//'), (Token.Comment.Single, u' This is a comment')```
