### ISSUE TITLE
Relationship type() missing 1 required positional argument 

### ISSUE THREAD

**Issue by shireenrao** [technige/py2neo#672]
I am trying something really basic and am using code from your documentation. 
I am using Python3.6, neo4j 3.4.1 and the latest driver for py2neo.

```python
from py2neo.data import Node, Relationship
a = Node("Person", name="Alice")
b = Node("Person", name="Bob")
ab = Relationship(a, "KNOWS", b)
c = Node("Person", name="Carol")
class WorksWith(Relationship): pass
ac = WorksWith(a, c)
ac.type()
```

I see the following error - 
<pre>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-a704c16ca39d> in <module>()
----> 1 ac.type()

TypeError: type() missing 1 required positional argument: 'name'
</pre>

If I check ac, I can see that it is - (Alice)-[:WorksWith {}]->(Carol)

Am I missing something?

Thanks

**Comment by technige** [comment]
It looks like the docs are out of date there. Sorry.

You'll need `type(ac)` instead.
