### ISSUE TITLE
document Transaction.results

### ISSUE THREAD

**Issue by keturn** [technige/py2neo#677]
Since `transaction.commit` no longer returns anything in the v4 API, I went looking for where to get those results.

It looks like that's probably the `transaction.results` attribute, currently undocumented.

(I think #516 was the same concern for an earlier version of the API.)

**Comment by keturn** [comment]
I think this is where Sphinx says how to document instance attributes: http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute

**Comment by keturn** [comment]
and I'm having some trouble deciphering what I'm getting back from that.

`transaction.results` is a list of `Result`s, which makes sense.

but then each `Result` also has a `.result` property of its own?

**Comment by technige** [comment]
`Transaction.results` was an internal attribute which should have had a leading underscore. It has been removed in later code. Results are per query, and are accessible through a `Cursor` following a `run`. The transaction itself doesn't provide access to those.
