### ISSUE TITLE
为何通过py2neo 创建不了节点

### ISSUE THREAD

**Issue by dengqiqi123** [technige/py2neo#678]
graph = Graph('http://localhost:7474/db/data',user='neo4j',password='test123')
tx = graph.begin()
a = Node(label='hero',name='凯')
tx.create(a)
tx.commit()
报错 builtins.TypeError: Parameters of type map are not supported  在执行create()方法的时候

**Comment by dengqiqi123** [comment]
tx = graph.begin()
 a = Node('hero',name='凯')
tx.create(a)
 tx.commit()
When you create it in this way, you still get an error.
so,I modify the  method  dehydrate() of in  json.py file 
isinstance(obj,list)  to isinstance(obj,map)
I don't know what will be wrong.But the node was created successfully

**Comment by noendings** [comment]
没看明白,后来问题解决了嘛?

**Comment by dengqiqi123** [comment]
谢谢，已经解决了，我用的是py2neo 4.0版本
但是又出现新的问题，查找关系的时候   我用graph.match(node,r_type=rel)
文档上说 这儿的node 是个集合或者序列，我尝试了多次没有成功，不知道这个node的形式是怎样的？
