### ISSUE TITLE
Update Connection Pool information

### ISSUE THREAD

**Issue by impguard** [technige/py2neo#689]
It seems like Py2Neo uses the underlying python driver by Neo4J, but doesn't expose any of the configuration parameters for tweaking things like connection timeouts lengths or connection pool sizes.

Is there any chance this could be exposed?

**Comment by technige** [comment]
A new setting for `max_connections` will be exposed in 4.3. In general, other settings will not exposed since these can't apply across both Bolt and HTTP.
