### ISSUE TITLE
Order the DataFrame columns in same way as Cypher RETURN

### ISSUE THREAD

**Issue by tpanza** [technige/py2neo#691]
Right now, `Cursor.to_data_frame()` returns a Pandas DataFrame with the column names in this dataframe sorted alphabetically.

Instead, it would be nice if the column names would be kept in the same order as the Cypher RETURN statement.

``` python
query = """
MATCH ...
RETURN some_node.id AS id, some_node.name AS name, some_node.address AS address
"""
curs = graph.run(query)
df = curs.to_data_frame()
```
This will currently return a dataframe with the columns ordered this way: `address, id, name` (alphabetically). It would be preferred if the dataframe was created with the columns in the original order in the Cypher RETURN statement: `id, name, address`.

**Comment by technige** [comment]
Not sure how to do this. Happy to accept a PR.
