### ISSUE TITLE
Allow for duplicate relationships with the same start/end node and relationship type

### ISSUE THREAD

**Issue by beaglez** [technige/py2neo#692]
This is a request to change the behavior outlined below:
https://github.com/technige/py2neo/blob/py2neo-4.1.0/py2neo/database.py#L975-L978

Neo supports this, and we have a use case that requires it. Would be cool if we could go through py2neo instead of having to drop down to cypher for create/merge of relationships.

Options to implement could include:
- a flag that would optionally allow duplicates
- allow duplicates if a separate unique constraint is established in neo. This is actually our use case - we allow for "duplicate" relationships in that they can have the same endpoints and type, but we have a separate unique constraint defined based on one of the properties of the relationship.

**Comment by impguard** [comment]
+1

Nodes already support this with the "primary key" and "primary label" type of logic. Would be awesome that relationships work just the same!

**Comment by technige** [comment]
I have previously ruled out making such a change. You will have to drop into Cypher to do this.
