### ISSUE TITLE
neo4j's "TransientError" class is redefined in py2neo

### ISSUE THREAD

**Issue by DanyL** [technige/py2neo#693]
So we encountered an `TransientError` in our code and added try .. except to catch it and handle it properly. Unfortunately this didn't really help as the exception was sometimes catched and sometimes not. Voodoo, you know..

After some debugging sessions, we learnt that `TransientError` was defined twice, first in `neo4j.exceptions`, and than in `py2neo`.
If they were the same class, I wouldn't bother opening an issue, as it's completely fine to re-export exceptions from other modules, but that's wasn't the case here, each definition of `TransientError`  is a different class, moreover - They inherit from different parent classes, which make it impossible to actually use them in a pythonic way (You know - `except TransientError as e` kind of thing).

**Proof:**
`In [4]: neo4j.exceptions.TransientError == py2neo.TransientError`
`Out[4]: False`

**`neo4j.exceptions.TransientError` Inherence:**
`In [9]: neo4j.exceptions.TransientError.mro()`
`Out[9]: [neo4j.exceptions.TransientError, neo4j.exceptions.CypherError, Exception, BaseException, object]`

**`py2neo.TransientError` Inherence:**
`In [10]: py2neo.TransientError.mro()`
`Out[10]:  [py2neo.database.TransientError, py2neo.database.GraphError, Exception, BaseException, object]`

Just thought this issue needs to be at least documented if not fixed, so other people can find it and understand whats going on.

**Comment by technige** [comment]
Yep, good call. I should clean this up.

**Comment by technige** [comment]
Not an issue in latest releases.
