### ISSUE TITLE
Immediate relationship turns out to be None when fetching path between two nodes

### ISSUE THREAD

**Issue by bhushanpant** [technige/py2neo#707]
Query Used: 

`MATCH (c1),(c2), p = ((c1)-[r*..2]-(c2:Company)) WHERE c1.name='Wonderful Villa' and and NONE(rel in r where type(rel) in ['IN_CITY','IS_PART_OF']) return c1.name,r,c2.name"`

Output: 

```
[{'c1.name': 'Wonderful Villa',
  'c2.name': 'Amazing Willa',
  'r': [(AAMOD PANSE)-[:None {}]->(Wonderful Villa),
   (AAMOD PANSE)-[:IS_OWNER]->(Amazing Willa)]},
 {'c1.name': 'Wonderful Villa',
  'c2.name': 'Great Villa',
  'r': [(RENU BHAT)-[:None {}]->(Wonderful Villa),
   (RENU BHAT)-[:IS_CARE_TAKER]->(Great Villa)]}]
```

This seems to work fine in version==3.1.2

I am extracting path using this query:
`path = graph.run(query).data()`

Thanks for the help!

**Comment by technige** [comment]
Closing impenetrable question.
