### ISSUE TITLE
How to operate the set of Nodes?I still cant understand

### ISSUE THREAD

**Issue by whbjzzwjxq** [technige/py2neo#710]
def search_main(ans,label):
    Nodes = []
    for keyword_0 in ans:
        Respon = Nmatcher.match(label, Name=keyword_0)
        Nodes.extend(Respon)
        for element in Respon:
            element["Main"]=True
    Nodes = search_son(Nodes,0)
    return Nodes,Relationships

   Actually,I wanna know how could I operate 2 Nodematch object?
I've tried operate them as list, but the variables lose their Nodematch class 

Sorry for so basic question

**Comment by technige** [comment]
I'm sorry, I really don't understand the question.

**Comment by whbjzzwjxq** [comment]
I've meant I dont know how to use RelationshipMatcher
Now,I know {} means a Sequence and [] means a Set and I think it should add to the handbook..
{source,target} or [Nodes]
Thanks lot for you reply
