### ISSUE TITLE
AttributeError: 'Cursor' object has no attribute 'to_data_frame'

### ISSUE THREAD

**Issue by timholds** [technige/py2neo#712]
I am trying to run PageRank in Python using Py2neo for a series of different years, and I want to write the results to a Pandas DataFrame. I have Pandas Installed (version 0.23.4), and I am using Py2neo version 4.

The code I am using is as follows:

`import pandas as pd
from py2neo import Graph, Node, Relationship
import numpy as np

graph = Graph("bolt://localhost:7687", auth=('neo4j', 'password'))

start_year, end_year, step = 1985, 2000, 5
dfs = []

for year in range(start_year, end_year+1, step):
    
    query = """
    CALL algo.pageRank.stream(
    'MATCH (p:Node) WHERE p.year < {} RETURN id(p) as id',
    'MATCH (p1:Node)-[:CITES]->(p2:Node) RETURN id(p1) as source, id(p2) as target',
    {{graph:'cypher', iterations:20, write:false, concurrency:20}})
    YIELD node, score
    WITH 
        *,
        node.title AS title, 
        node.year AS year, 
        score AS page_rank
    ORDER BY page_rank DESC
    LIMIT 1000
    RETURN 
        title,
        year, 
        page_rank;    
    """.format(year,year,year)

    df = graph.run(query).to_data_frame()`

The query works fine when I run it directly in the Neo4j browser, but when I try to run it with Py2neo and put the results in a DataFrame, I get the error `AttributeError: 'Cursor' object has no attribute 'to_data_frame'`. 

Does anyone have any idea what might be causing the error? Any help will be greatly appreciated. Thanks!

**Comment by timholds** [comment]
Another note is that when I change the last part of the query to be  
`df = graph.run(query
print(df)` 
it returns

`Running PageRank on works from < 1985... <py2neo.graph.Cursor object at 0x113de1668>
Running PageRank on works from < 1990... <py2neo.graph.Cursor object at 0x113de1198>
Running PageRank on works from < 1995... <py2neo.graph.Cursor object at 0x113de16a0>
Running PageRank on works from < 2000... <py2neo.graph.Cursor object at 0x113de1a58>
Running PageRank on works from < 2005... <py2neo.graph.Cursor object at 0x113de1908>
Running PageRank on works from < 2010... <py2neo.graph.Cursor object at 0x113de1c50>`

**Comment by technige** [comment]
Double check what version you're running, because it should be there.

```
from py2neo.meta import __version__
print(__version__)
```
