### ISSUE TITLE
Python2 no longer supported?

### ISSUE THREAD

**Issue by bwmetz** [technige/py2neo#715]
Python 2.7 is still listed as supported, but hitting multiple issues attempting to install py2neo-4.1 vs. py2neo-3.1.2

1. IPython & Jupyter

- Listed in requirements.txt & setup.py due to ipykernel reference.
- IPython was not required in py2neo 3.1.2
- IPython has not supported Python2 since version 5.8.0 (latest is 7.1.1)
- Have not located any import references to ipykernel or either module in any .py file in the tree

2. neo4j-driver dependency failure
- Assuming neotime dependency mismatch in setup.py
```
Adding neo4j-driver 1.6.2 to easy-install.pth file

Installed c:\python27\lib\site-packages\neo4j_driver-1.6.2-py2.7-win-amd64.egg
error: neotime 1.7.1 is installed but neotime==1.0.0 is required by set(['neo4j-driver'])
```

3. Manual uninstall/install of neo4j-driver-1.6.2:
- Removes neotime-1.7.1 in favor of required neotime-1.0.0
- Then fails due to missing neotime-1.7.1 egg file
- This is likely a pip issue due to workaround attempts vs. neo4j, but listed in case others attempt this

`WindowsError: [Error 2] The system cannot find the file specified: 'c:\\python27\\lib\\site-packages\\neotime-1.7.1-py2.7.egg'`

- Subsequent install neo4j-drive-1.6.2 succeeds
```
>pip install neo4j-driver==1.6.2
Requirement already satisfied: neo4j-driver==1.6.2 in c:\python27\lib\site-packages (1.6.2)
Requirement already satisfied: neotime==1.0.0 in c:\python27\lib\site-packages (from neo4j-driver==1.6.2) (1.0.0)
...
```

4. After updates to requirements.txt/setup.py to deal with #1, plus manual neo4j-driver correction from #2/#3; removal & re-install as well as pip dependency checks both complete successfully.
```
Using c:\python27\lib\site-packages
Finished processing dependencies for py2neo==4.1.0

>pip check
No broken requirements found.
```

This is being submitted in good faith as I am a newb with neo4j and py2neo; thus this is simply an install failure report.  I have not yet attempted a validation test.

**Comment by bwmetz** [comment]
Just an quick update to confirm that py2neo seems to be executing correctly in python 2.7.13 with the modifications that I roughly outlined as being necessary.  At least the following simple example using the moviegraph database seems to match text output seen using the neo4j browser.
```
>>> from py2neo import Graph, Node, Relationship
>>> graph = Graph('bolt://localhost:7687', password="password")
>>> cursor = graph.run('MATCH (tom {name: "Tom Hanks"}) RETURN tom')
>>> print cursor.evaluate()
(_71:Person {born: 1956, name: 'Tom Hanks'})
```

**Comment by technige** [comment]
Note that v4.1.1 has just been released, which removes the `ipython` and `juypter` dependencies and should enable Python 2 compatibility again.
