### ISSUE TITLE
Beta version in conda forge?

### ISSUE THREAD

**Issue by robarthur** [technige/py2neo#718]
Hi,

I've recently run into a few dependency problems when attempting to install py2neo in a jupyter stack.  I believe it's related to the issues referenced here:  https://github.com/technige/py2neo/issues/700 .

I'm using conda as a package manager for my environment, and it prompted me to notice that the latest version in the channel I'm using, conda-forge is at v4.0.0.0b2 (https://anaconda.org/conda-forge/py2neo ).  It seems that v4.1.0 was released back in August.  Is this something that can be updated?

**Comment by technige** [comment]
Note that v4.1.1 has just been released. I'm not familiar with Conda, so can't help you with that.
