### ISSUE TITLE
Unexpected behavior: graph.match((node, ), r_type=None) does not return all relationships

### ISSUE THREAD

**Issue by danZib** [technige/py2neo#721]
Hello everyone,

On my search if retrieving all immediate relationships of a chosen node, I found myself using the following setup:
```
relations = []
for rel in self.graph.match((node, ), r_type=None):
    relations.append(rel)
  ```
However, I noticed that the `match` method only returned 6 of the expected 14. I switched to using Cypher in the meantime, but just wonder if I miss-understood the function.

Thanks already and happy start into the Christmas time

**Comment by technige** [comment]
The `match` function should return everything; it won't limit your results. However, it's impossible to tell without seeing the content of your database exactly what's going on in your case. Why do you expect 14 relationships? Note that `(node, )` will only match _outgoing_ relationships from `node`, if that helps.

**Comment by danZib** [comment]
__will only match outgoing relationships from node,__ 
Ahh, that was the issue, could have gotten that myself. Just for the record, is there a way to get all the relationships at once or just calling both `(node, )` and `(, node)` is the way to go? Otherwise this can be closed. Thank you @technige

**Comment by technige** [comment]
Yep, you need to use a set instead of a tuple to indicate a direction-insensitive match, i.e. `{node}`.

As it says on the parameters for https://py2neo.org/v4/database.html#py2neo.database.Graph.match:
> nodes – Sequence or Set of start and end nodes (None means any node); a Set implies a match in any direction
