### ISSUE TITLE
TypeError while trying to access node labels - LabelSetView object is not callable

### ISSUE THREAD

**Issue by benjaminh** [technige/py2neo#724]
Hello there,
I'm using py2neo 4.1.3 along with neo4j 3.4.10 and python 3.6.5.

Following the documentation here [https://py2neo.org/v4/data.html?highlight=node#py2neo.data.Node](https://py2neo.org/v4/data.html?highlight=node#py2neo.data.Node), I try to add a label to a node object after casting it from a dict:
```
node = Node.cast(mydict)
node.labels.add(mylabel)
```
This throws me the following error : `TypeError: 'LabelSetView' object is not callable`
Is the documentation out of date, is this an issue or am I missing something ?

**Comment by technige** [comment]
Yep, looks like the docs are out of date here. Sorry about that.

You can use the following methods on any `Node` object:
```

    @property
    def labels(self):
        """ Set of all node labels.
        """
        self.__ensure_labels()
        return LabelSetView(self._labels)

    def has_label(self, label):
        self.__ensure_labels()
        return label in self._labels

    def add_label(self, label):
        self.__ensure_labels()
        self._labels.add(label)

    def remove_label(self, label):
        self.__ensure_labels()
        self._labels.discard(label)

    def clear_labels(self):
        self.__ensure_labels()
        self._labels.clear()

    def update_labels(self, labels):
        self.__ensure_labels()
        self._labels.update(labels)
```

**Comment by Luyaochen1** [comment]
is there any update on this issue?

**Comment by HIT-Owen** [comment]
the v4 handbook has problems, so i try to pip install py2neo=3.x.x
