### ISSUE TITLE
merge_one

### ISSUE THREAD

**Issue by sojoudian** [technige/py2neo#726]
merge_one was a use full command in v2, but as I see it has been deprecated, so what do you suggest to do for merging in this example :

```
from py2neo import *
graph = Graph()
nicole = Node("Person", name="Nicole", age=24)
graph.create(nicole)
nicole = graph.merge_one("Person", "name", "Nicole")
graph.create(nicole)
```

**Comment by technige** [comment]
The `Graph.merge` method implements this functionality.
