### ISSUE TITLE
graph.schema.create_index('merchant','name')  TypeError: super(type, obj):

### ISSUE THREAD

**Issue by yueyub** [technige/py2neo#727]
run  graph.schema.create_index('merchant','name') 
got error 

TypeError: super(type, obj): obj must be an instance or subtype of type

error chain:

graph.schema.create_index('whiteUser')

(cypher_escape(label), ",".join(map(cypher_escape, property_keys)))).close()

encoder = CypherEncoder(**kwargs)

 cls.__default_instance = super(CypherEncoder, cls).__new__(cls)

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by technige** [comment]
Closing as not enough information to recreate the error. Please reopen if more information is available.
