### ISSUE TITLE
Connection pool is full, discarding connection 

### ISSUE THREAD

**Issue by YunLoong** [technige/py2neo#728]
When I use HTTP to connect to the database by multi-process, will get a warning, like:

```
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection
```

The code like：

```
neo4j_client = Graph(
     "http://%s:7474" % os.environ.get('NEO4J_HOST'),
     username='neo4j',
     password='xxx'
)
```

Is there a way to modify the maxsize of the HTTP connection pool size?

**Comment by technige** [comment]
This new `max_connections` setting will be available in 4.3.
