### ISSUE TITLE
subgraph problem

### ISSUE THREAD

**Issue by lyllou** [technige/py2neo#730]
from py2neo import Node, Relationship

a = Node('Person', name='Alice')
b = Node('Person', name='Bob')
r = Relationship(a, 'KNOWS', b)
graph.create(r)
s = a | b |r
print(s)
 
when I run my program
j got 
<py2neo.data.Subgraph object at 0x7fe736ed2080>

what's wrong?

**Comment by elena** [comment]
Hi lyllou, 

I hope you got an answer on your question from the forum (https://community.neo4j.com/) or from stackoverflow, but I can tell you the official answer is probably this:

`s` *is* a Subgraph object. It is returning the correct thing -- this is kind of like the equivalent of a queryset in a RDBMS.

The code you may be looking for is this:
```python
for nd in s.nodes: 
    print(nd) 

(_1:Person {name: 'Alice'})
(_2:Person {name: 'Bob'})
```

Cheers!
