### ISSUE TITLE
is it possible to support call with apoc?

### ISSUE THREAD

**Issue by FFengIll** [technige/py2neo#731]
apoc is useful, so is it possible?

**Comment by FFengIll** [comment]
@elena for most of our requirements, we use apoc `call apoc.path.*` and `call apoc.create.*` and so on.
I agree with your idea - `too many apoc function now to support`.

BTW, for conveniency, I use Matcher in py2neo to build a basic query using `_query_and_parameters()`, and replace the `RETURN _` to a apoc call, yield and return.

I found out that, for many apoc, we just need to specify the call (str), the config (dict), the return value (tuple, or str), then we could do a string replace to complete it (in py2neo).

Maybe, it is not a perfect way, but a general solution for some frequently used apoc.

**Comment by technige** [comment]
You will be able to call procedures in Cypher but py2neo provides no direct support for APOC.
