### ISSUE TITLE
Documentation @py2neo.org is outdated.

### ISSUE THREAD

**Issue by abbasidaniyal** [technige/py2neo#736]
Several commands given in the documentation are outdated. Is there a way to get the latest updated documentation?

**Comment by technige** [comment]
You'll have to be far more specific than that. The documentation on https://py2neo.org is the latest.

**Comment by abbasidaniyal** [comment]
https://py2neo.org/v4/ogm.html#labels
https://py2neo.org/v4/ogm.html#object-matching 
These do not work with my py2neo version 4.2.0

**Comment by technige** [comment]
"Do not work" in what kind of way?

**Comment by technige** [comment]
Closing due to unhelpful vagueness.
