### ISSUE TITLE
Preloading relationships in OGM?

### ISSUE THREAD

**Issue by danielrs** [technige/py2neo#738]
We should be able to preload relationships, something like:

```
class Person(GraphObject):
    likes = RelatedTo('Person', 'LIKES')

Person.match(graph).preload('likes')
```

So the following code:

```
for person in Person.match(graph).preload('likes'):
    for other_person in person.likes:
        print(other_person)
```

Would be a lot faster (instead of lazily loading `person.likes`). Any thoughts on this? I tried searching the documentation, but the solution since to execute raw cypher queries.

**Comment by technige** [comment]
No, there's no functionality like that available.
