### ISSUE TITLE
Unable to connect remotely using TLS - 401 Unauthorized

### ISSUE THREAD

**Issue by LiBa001** [technige/py2neo#741]
# Getting "py2neo.database.status.Unauthorized" when trying to connect to a remote server (bug?)

> First of all: **username and password are correct!**

## What I'm doing
I'm running `Neo4j 3.5.0` on a server and try to connect via `https` using `py2neo v3`.

**Btw: I also tried to connect on localhost and that worked just fine.**

But I need to connect from another system so I tried this:
`graph = Graph('my.host.de', user='myuser', password='mypassword', secure=True)`
(I tried a few different ways/combinations of defining that graph and none of 'em worked.)

## Error
It raises `401 Unauthorized` which is weird because I'm 100% sure that my credentials are correct.

```
Traceback (most recent call last):
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/database/__init__.py", line 318, in __new__
    inst = cls.__instances[key]
KeyError: (<class 'py2neo.database.Graph'>, <ServerAddress settings={'host': 'my.host.de', 'secure': True}>, 'data')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/database/http.py", line 155, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, **kwargs)
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 969, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, **kwargs)
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 944, in __get_or_head
    result = rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 452, in submit
    return Response.wrap(http, uri, self, rs, **response_kwargs)
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 489, in wrap
    raise inst
py2neo.packages.httpstream.http.ClientError: 401 Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/database/__init__.py", line 327, in __new__
    use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)
  File "/home/linus/.local/lib/python3.6/site-packages/py2neo/database/http.py", line 163, in get
    raise Unauthorized(self.uri.string)
py2neo.database.status.Unauthorized: https://my.host.de:7473/db/data/
```
Since an `401` status code is usually only returned by the API when either the credentials are incorrect or no authorization is provided at all, I guess that it's the second one.  
But why would neo4j not receive an authorization when I specify it in the `Graph`?

Well, I tested a few things.

### My approach

First I used `watch('httpstream')` to get an idea of what's happening, but that didn't really helped me further. It just showed something like this:
`GET https://my.host.de:7473/db/data`

I used "Postman" to manually call the API and specify an auth header. It worked perfectly fine and was like the last prove to me that the credentials are valid.  
So I started searching the error inside of py2neo placing some print statements in the actual get method returning the headers and some other stuff:
```
{'User-Agent': 'py2neo/3.1.2 HTTPStream/1.5.0 Python/3.6.7-final-0 (linux)', 'X-Stream': 'true'} {'cache': True}
{'User-Agent': 'py2neo/3.1.2 HTTPStream/1.5.0 Python/3.6.7-final-0 (linux)', 'X-Stream': 'true'} https://my.host.de:7473/db/data/ GET https://my.host.de:7473/db/data/
```

And oh, what is this? There is no `Authorization` header at all!  
(At this point I'm just assuming that authorization is usually done using an auth header.)

#### Trying to solve things
After that I had a look at the actual instantiation of `Graph` and noticed a few things:
```Python
def __new__(cls, *uris, **settings):
        database = settings.pop("database", "data")
        address = register_server(*uris, **settings)  # <-- auth info passed into this
        key = (cls, address, database)
        try:
            inst = cls.__instances[key]
        except KeyError:
            inst = super(Graph, cls).__new__(cls)
            inst.address = address
            inst.__remote__ = Resource(address.http_uri("/db/%s/" % database))  # <-- no auth info going into this
            inst.transaction_uri = Resource(address.http_uri("/db/%s/transaction" % database)).uri.string
            inst.transaction_class = HTTPTransaction
            use_bolt = address.bolt
            if use_bolt is None:
                use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)  # <-- this is where the error appears; and again no auth info provided
            if use_bolt:
                auth = get_auth(address)  # <-- auth first accessed at this point (which is not reached)
                inst.driver = GraphDatabase.driver(address.bolt_uri("/"),
                                                   auth=None if auth is None else auth.bolt_auth_token,
                                                   encypted=address.secure,
                                                   user_agent="/".join(PRODUCT))
                inst.transaction_class = BoltTransaction
            inst.node_selector = NodeSelector(inst)
            cls.__instances[key] = inst
        return inst
```
The line where the error appears is basically calling `Resource.get()` but there was no credentials provided to the `Resource` object that is used.   
Being logically: **Authorization must fail.**

So I changed it a bit:
```Python
def __new__(cls, *uris, **settings):
        database = settings.pop("database", "data")
        address = register_server(*uris, **settings)
        key = (cls, address, database)
        try:
            inst = cls.__instances[key]
        except KeyError:
            auth = get_auth(address)  # <-- accessing auth

            inst = super(Graph, cls).__new__(cls)
            inst.address = address
            inst.__remote__ = Resource(address.http_uri("/db/%s/" % database), headers=None if auth is None else {'Authorization': auth.http_authorization})  # <-- providing http auth header
            inst.transaction_uri = Resource(address.http_uri("/db/%s/transaction" % database)).uri.string
            inst.transaction_class = HTTPTransaction
            use_bolt = address.bolt
            if use_bolt is None:
                use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)  # <-- now this has access to the auth header
            if use_bolt:
                inst.driver = GraphDatabase.driver(address.bolt_uri("/"),
                                                   auth=None if auth is None else auth.bolt_auth_token,
                                                   encrypted=address.secure,
                                                   user_agent="/".join(PRODUCT))
                inst.transaction_class = BoltTransaction
            inst.node_selector = NodeSelector(inst)
            cls.__instances[key] = inst
        return inst
```

Then I tried creating a `Graph` again and … SURPRISE: **it works!**

## Conclusion
To me everything looks like this is a bug but I'm still not 100% confident about it, because this is such a common thing to do that I really don't know how something like that would not have been recognized yet …  
Maybe I'm just missing something obvious?

Please tell me I'm not stupid. :/  (or just tell me what I'm doing wrong. Either way is strongly appreciated.)

**Comment by technige** [comment]
I suggest upgrading to py2neo v4, I no longer support v3.

**Comment by LiBa001** [comment]
The problem is that I already used v3 for my whole project. I plan to upgrade to v4 in the future, but for the moment it would be nice if it just worked . . .
However, when you don't know a possible solution to this I could just use my experimental solution for now.

**Comment by LiBa001** [comment]
Okay, nevermind. I'll just upgrade to v4 now. It seems I don't have to manage too many changes.

Should this issue stay open, though? I mean it's not really solved, but if you don't support v3 anyway then there's no need for it to stay open, I guess . . .

**Comment by technige** [comment]
A lot of issues around auth and connectivity were fixed in py2neo v4, so there is a strong chance you won't see this after an upgrade.

Sorry that I can't support old versions, but I work on this project by myself in my spare time, so don't have the capacity to do that.

**Comment by LiBa001** [comment]
Of course, that is completely understandable.
And you're right, py2neo v4 works just fine.

Thank you for your support and this __great__ library :D
