### ISSUE TITLE
Setting up a test environment for neo4j

### ISSUE THREAD

**Issue by vonum** [technige/py2neo#742]
I am trying to set up a testing environment for neo4j.
What are the usual approaches here?
I would imagine a separate database for testing.
Is the appropriate way just connecting to that separate database for testing or are there some other ways in which py2neo does it out of the box.

I couldn't find anything in the handbook regarding tests.

**Comment by Askir** [comment]
For our neo4j project I just set up a second database with docker on a different port and let our application connect to that testing database for unit tests.

**Comment by technige** [comment]
There are many different approaches to this but the one used here involves starting and stopping a brand new database either side of the test run.

The library itself provides no test facilities though; the test code included in here is simply for testing py2neo.
