### ISSUE TITLE
Querying related nodes return more results than expected when re-using relationship name

### ISSUE THREAD

**Issue by ajutras** [technige/py2neo#744]
I'm building a backend that use the OGM to automate a few things. My Neo4J contains a few different node types and sometime re-use relationship names. When defining a relationship between A and B and querying which specific instances of B are related to a specific instance of A, I will get C, D, E as part of the resultset too if they have the same relationship name as the one defined between A and B. To illustrate the issue here is a short example:

**In neo4j**

```
(Employee)-[HAS]->(Title)
(Employee)-[HAS]->(Gender)
(Employee)-[HAS]->(PersonalInterest)
(Employee)-[HAS]->(Role)
```

**In python**

```
from py2neo.ogm import GraphObject, Property, RelatedTo

from server.db.graph.utils import get_py2neo_connection


class Title(GraphObject):
    __primarykey__ = "name"
    __primarylabel__ = "Title"

    name = Property()


class Employee(GraphObject):
    __primarykey__ = "uuid"
    __primarylabel__ = "Employee"

    uuid = Property()
    titles = RelatedTo(Title, "HAS")


if __name__ == '__main__':
    node_property = "uuid"
    node_value = "3cb2e64c-3ccb-448f-9611-a07320ed73e2"
    employee = Employee.match(get_py2neo_connection()).where(
        f"_.{node_property} =~ '(?i){node_value}'").first()

    for title in employee.titles:
        print(title)
```

**This example will output:**

```
<Title name='AI Developer'>
<Title name='Male'>
<Title name=None>
<Title name=None>
<Title name=None>
<Title name='Developer'>
```

The thing is, only the first one is right. The second one is Gender, then I have 3 PersonalInterest and the last one is a Role. All of this despite specifying that the relationship is specific to Employee and Title.

I tested a manual fix in `py2neo.ogm.RelatedObjects.__db_pull__` that don't add nodes that don't have the label defined in the relationship (via the RelatedObjects.related_class attribute) and it works. But I'm wondering if my usage of the OGM is wrong, or if it's an intended behaviour.

Thank you for your time.

**Comment by technige** [comment]
The general recommendation with Neo4j is for relationship names to be kept unique. One of the big benefits of this is to avoid the query engine needing to scan beyond the relationship itself onto the related node when querying only relationships of a particular type. In your case, `(Employee)-[HAS]->(Title)` queries would need to search both the relationship type (`HAS`) _and_ the node label (`Title`) to see whether or not the relationship should be included. While Cypher _can_ do this, it's much more efficient to only look at the relationships.

In terms of the py2neo OGM, related objects classes are not considered in the underlying query. Therefore, all `HAS` relationships will be returned and all related nodes will be coerced to `Title` objects, regardless of their labels.

The correct approach is to use unique relationship types for each. Therefore, you'll want something like `(Employee)-[HAS_TITLE]->(Title)` or just `(Employee)-[TITLE]->(Title)` instead.

**Comment by KathRains** [comment]
I think, no matter of recommendation from Neo4j, the ORM must have a mechanism allowing distinguish nodes by a label.

**Comment by Vardan-Alaverdyan** [comment]
I'm experiencing the same issue.
Any updates on this?
