### ISSUE TITLE
installing a library containing py2neo

### ISSUE THREAD

**Issue by raldam** [technige/py2neo#746]
Hi,

I recently made a package for my own usage. I put py2neo in the requirements of the setup.py file 
`      install_requires=[
          'elasticsearch',
          "py2neo",
          "psycopg2",
      ],`

Then, when I install this package for another project, I get a weird import error

Traceback (most recent call last):
  File "/home/raldam/projects/learn/neo/test.py", line 4, in <module>
    graph = Graph(host=host, password=password, user=user)
  File "/home/raldam/envs/neo/lib/python3.6/site-packages/py2neo/database.py", line 309, in __new__
    database = Database(uri, **settings)
  File "/home/raldam/envs/neo/lib/python3.6/site-packages/py2neo/database.py", line 89, in __new__
    from py2neo.internal.connectors import get_connection_data
  File "/home/raldam/envs/neo/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 25, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

It works when I install the library "certifi" manually. Could you please tell me if I am doing something wrong ? I have used this scheme before for another package and I did not encounter this type of error.

**Comment by technige** [comment]
The `certifi` library _should_ be installed along with `urllib3` as the requirements.txt file for py2neo contains the `[secure]` extra:
https://urllib3.readthedocs.io/en/latest/user-guide.html?highlight=certifi#certificate-verification

If that's not happening in all cases though, I probably need to add `certifi` as a separate explicit requirement.
