### ISSUE TITLE
how to print the result of run cypher as it run in neo4j web terminal

### ISSUE THREAD

**Issue by loveJasmine** [technige/py2neo#747]
if I run
_LOAD CSV WITH HEADERS  FROM "file:///hudong_pedia.csv" AS line
CREATE (p:HudongItem{title:line.title,image:line.image,detail:line.detail,url:line.url,openTypeList:line.openTypeList,baseInfoKeyList:line.baseInfoKeyList,baseInfoValueList:line.baseInfoValueList})_

in http://localhost:7474/browser/:
I can see:
**Added 113037 labels, created 113037 nodes, set 791259 properties, completed after 2816 ms.**

so, i I use py2neo like:

str1 = '''
LOAD CSV WITH HEADERS  FROM "file:///hudong_pedia.csv" AS line
CREATE (p:HudongItem{title:line.title,image:line.image,detail:line.detail,url:line.url,openTypeList:line.openTypeList,baseInfoKeyList:line.baseInfoKeyList,baseInfoValueList:line.baseInfoValueList})
'''
ret = test_graph.run(str1)#.data()
print("str1 ret is ", ret)

the ret is []

how can I got the message 
**Added 113037 labels, created 113037 nodes, set 791259 properties, completed after 2816 ms.**
from py2neo

**Comment by technige** [comment]
You can obtain this information via the query statistics. Specifically, the `Cursor.stats()` method.

Better documentation for this functionality has been added in https://github.com/technige/py2neo/commit/4d7a7d7fffaeb64ce7d99762b635136cb0ad99d2 and will become available in the 4.3 release.
