### ISSUE TITLE
IPython 5.8 conflict (Python 2.7)

### ISSUE THREAD

**Issue by cadryden** [technige/py2neo#754]
When trying to pip install py2neo 4.3 in Python 2.7 I get the following error:

`ERROR: ipython 5.8.0 has requirement prompt-toolkit<2.0.0,>=1.0.4, but you'll have prompt-toolkit 2.0.9 which is incompatible.`

It looks like f4ddc190f719acb43eda6cab4f1feeac1452678f bumped the prompt_toolkit requirement beyond what IPython 5.8 requires.  Would it be possible to loosen this so py2neo could work with  the latest IPython for Python 2.7?

**Comment by technige** [comment]
I'm afraid this is a `wontfix`, as prompt_toolkit 2.0 is incompatible with 1.0. See:
https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading/2.0.html

So this would require downgrading the py2neo code back to the earlier version and blocking anyone who requires prompt_toolkit 2.0. I'm afraid the onus instead needs to be on ipython to _upgrade_.

Note also that prompt_toolkit now has a 3.0 release:
https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading/3.0.html
