### ISSUE TITLE
py2neo command line documentation

### ISSUE THREAD

**Issue by zeneofa** [technige/py2neo#755]
Hi,

New to py2neo, I am trying to use the command line option. Unfortunately the documentation is quite vague on how to actually use it. The online documentation simply says use 'py2neo --help'. However this doesn't actually tell me how to actually use it, eg: I am trying to run a .cypher file, so I am using:

` cat myfile.cypher | py2neo run -`

which fails, because of authentication issues. There is the "-a" option, but no documentation on the format I should use to pass the username/password. From delving into the source code it seems that the option value is passed directly to `Graph` eventually, so I have tried `-a "(usrname,pswd)" , '-a ("usrname","pswd")', '-a usrname -a pswd' `. Is there some example out there or explicit documentation that I am not aware of?

I am using py2neo 4.1.3, neo4j 3.5.6 

Any help would be greatly appreciated. 

P

**Comment by technige** [comment]
This has been fixed in the attached commit. The format you need is `-a user:password`.
