### ISSUE TITLE
Eagerly fetching related objects

### ISSUE THREAD

**Issue by ghostroad** [technige/py2neo#756]
I'm using `v4.3.0` and have a setup similar to the following:

```
class Person(GraphObject):
    name = Property()
    nationality = RelatedTo(Country)
```

Now I'd like to do something like:
```
Person.match(graph).order_by('_.name').skip(offset).limit(limit)
```

The problem I'm having is that this leads to something like the n+1 query problem: The `Person` objects are loaded initially with one query, but a new query is issued for each person when `nationality` is accessed. Is there any way to specify that nationalities should be eagerly loaded without having to resort to raw Cypher?

**Comment by technige** [comment]
No, you will have to drop into Cypher for a greater degree of control over data loading.
