### ISSUE TITLE
Nested transactions not rolling back on outer exception

### ISSUE THREAD

**Issue by EdLeafe** [technige/py2neo#757]
I'm creating an app where any code that touches the database is decorated with a function that creates a transaction. It's working fine, except in the case where these transactions end up getting nested. The decorator code looks like this:

```
def wrap_tx(self, fn):
  @functools.wraps(fn)
  def wrapper(context, *args, **kwargs):
      # The app gets and maintains a connection to the database
      cxn = get_connection()
      with cxn.begin() as tx:
          # Pushes transactions on a LIFO queue if they are active
          if self._context_tx_active(context):
              self.tx_queue.put(context.tx)
          context.tx = tx
          try:
              ret = fn(context, *args, **kwargs)
          except Exception as e:
              # Utility to allow catching and re-raising exceptions
              with excutils.save_and_reraise_exception():
                  pass
          finally:
              if self.tx_queue.qsize():
                  # Pop the queued transaction from the queue
                  context.tx = self.tx_queue.get()
          return ret
  return wrapper
```
So in some cases the code can call multiple functions that have that decorator. Example:

```
@wrap_tx
def delete_all_the_things(context):
    delete_thing_one(context)
    delete_thing_two(context)
    # Now do some local queries
    context.tx.run("MATCH (foo:THING) RETURN foo")
    # Finally, call a method that raises an exception
    bad_juju(context)

@wrap_tx
def delete_thing_one(context):
    context.tx.run("MATCH (t1:THING {name: "thing1"}) DELETE t1")

@wrap_tx
def delete_thing_two(context):
    context.tx.run("MATCH (t2:THING {name: "thing2"}) DELETE t2")

@wrap_tx
def bad_juju(context):
    context.tx.run("SOME BAD CYPHER QUERY")
```
What I'm seeing is that in some cases, the two deletes succeed and their transactions commit, then the third raises an exception, which rolls back its transaction, and causes the outer transaction for `delete_all_the_things()` to also roll back. However, it doesn't roll back the two deletes that were committed, and they stay deleted.

I'm fairly new to Neo4j and py2neo, but have been working in relational DBs for decades, and nested transactions such as these "just work". I'm wondering if I'm misunderstanding how to use nested transactions, and specifically if doing the nesting through the transaction's context manager is the right way to do it. Any and all advice would be appreciated.

**Comment by technige** [comment]
Nested transactions are not supported by py2neo or Neo4j itself.
