### ISSUE TITLE
HTTP to HTTPS : Cannot to connect to Bolt service

### ISSUE THREAD

**Issue by WernerWildenboer** [technige/py2neo#760]
`graph = Graph(host="bolt://link:443", auth=('neo4j', 'pass'),bolt_port=443,secure=True)`

And I get the error 

`ServiceUnavailable: Cannot to connect to Bolt service on ('fuji-bolt.ambrite.ch', 443) (looks like HTTP)`

Was working fine before hosting as HTTPS

**Comment by WernerWildenboer** [comment]
I have not added : `#dbms.connectors.default_listen_address=0.0.0.0` to config file as I am not hosting it

**Comment by technige** [comment]
Have you configured Bolt to listen on 443? If not, this will be why. The port you provide should be where the Bolt service is listening.

Also, please ask general support questions on StackOverflow or the Neo4j Community Forum. I cannot provide general support on this project issues list.
