### ISSUE TITLE
delete a node failed

### ISSUE THREAD

**Issue by comprel** [technige/py2neo#761]
create a node like this:
————————————————
from py2neo.data import Node
node = Node(name='v')
graph.create(c)
————————————————
create success , but then I want to delete it like this, it failed , no error and give me, I can find it on web
————————————————
from py2neo.data import Node
node = Node(name='v')
graph.delete(node)
————————————————

but if use delete_all  , it can delete all,  can you help me?

and for match_one:
————————————————
from py2neo.data import Node
node = Node(name='v')
node = graph.match_one([node])
print node
————————————————
the result is None,  but I'm sure this node exists.

**Comment by jtwool** [comment]
HI Comprel - 

This is not the proper syntax for deleting a node (or relationship) in py2neo. 
The proper way to do this is to use `py2neo.matching.NodeMatch`

```python
matched_nodes = my_graph.nodes.match({'name':'v'})
my_graph.delete(matched_nodes.first())
```

I suggest that we update the docs to clarify this.

**Comment by technige** [comment]
Node objects can be bound to remote nodes through the `graph` and `identity` attributes. When you `create` or `match`, for example, the node objects used will have such a link attached. Only nodes that are bound in this way can be deleted.
