### ISSUE TITLE
Fail to create remote node and relationship

### ISSUE THREAD

**Issue by boristchague** [technige/py2neo#762]
Please i need help because i don't understand what is happening. The code below is an exemple from Py2neo's doc but it doesn't work for me

--------------------------------------------------------------------------------------------------------- 
from py2neo import Graph, Node, Relationship
g = Graph()
g = Graph(uri="http://localhost:7474", user ="neo4j" ,password="xxxx")
tx = g.begin()

a = Node("Employee", name="Alice")
tx.create(a)

b = Node("Employee", name="Bob")

ab = Relationship(a, "WORKS_WITH", b)

graph.create(ab)

graph.commit()

graph.
----------------------------------------------------------------------------------------------------------

Error message 

HydrationError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\py2neo\internal\connectors.py in run(self, statement, parameters, tx, graph, keys, entities)
    371         try:
--> 372             raw_result = hydrator.hydrate_result(r.data.decode("utf-8"))
    373         except HydrationError as e:

C:\ProgramData\Anaconda3\lib\site-packages\py2neo\internal\hydration\__init__.py in hydrate_result(self, data, index)
    432         if data.get("errors"):
--> 433             raise HydrationError(*data["errors"])
    434         return data["results"][index]

HydrationError: {'code': 'Neo.ClientError.Statement.InvalidSyntax', 'message': '$x not defined (line 1, column 8 (offset: 7))\n"UNWIND $x AS data CREATE (_:Employe) SET _ = data RETURN id(_)"\n        ^'}

During handling of the above exception, another exception occurred:

ClientError                               Traceback (most recent call last)
<ipython-input-95-370c4dcece46> in <module>()
      5 
      6 a = Node("Employe", name="Alice")
----> 7 tx.create(a)
      8 b = Node("Employe", name="Bob")
      9 

C:\ProgramData\Anaconda3\lib\site-packages\py2neo\database.py in create(self, subgraph)
    904             raise TypeError("No method defined to create object %r" % subgraph)
    905         else:
--> 906             create(self)
    907 
    908     def delete(self, subgraph):

C:\ProgramData\Anaconda3\lib\site-packages\py2neo\data.py in __db_create__(self, tx)
    607 
    608     def __db_create__(self, tx):
--> 609         create_subgraph(tx, self)
    610 
    611     def __db_delete__(self, tx):

C:\ProgramData\Anaconda3\lib\site-packages\py2neo\internal\operations.py in create_subgraph(tx, subgraph)
    134     for labels, nodes in _node_create_dict(n for n in subgraph.nodes if n.graph is None).items():
    135         identities = _create_nodes(tx, labels, list(map(dict, nodes)))
--> 136         for i, identity in enumerate(identities):
    137             node = nodes[i]
    138             node.graph = graph

C:\ProgramData\Anaconda3\lib\site-packages\py2neo\internal\operations.py in _create_nodes(tx, labels, data)
     85     label_string = "".join(":" + cypher_escape(label) for label in sorted(labels))
     86     cypher = "UNWIND $x AS data CREATE (_%s) SET _ = data RETURN id(_)" % label_string
---> 87     for record in tx.run(cypher, x=data):
     88         yield record[0]
     89 

C:\ProgramData\Anaconda3\lib\site-packages\py2neo\database.py in run(self, cypher, parameters, **kwparameters)
    826                                              graph=self.graph,
    827                                              keys=[],
--> 828                                              entities=entities))
    829         except CypherError as error:
    830             raise GraphError.hydrate({"code": error.code, "message": error.message})

C:\ProgramData\Anaconda3\lib\site-packages\py2neo\internal\connectors.py in run(self, statement, parameters, tx, graph, keys, entities)
    375             if tx is not None:
    376                 self.transactions.remove(tx)
--> 377             raise GraphError.hydrate(e.args[0])
    378         else:
    379             result = CypherResult({

ClientError: InvalidSyntax: $x not defined (line 1, column 8 (offset: 7))
"UNWIND $x AS data CREATE (_:Employe) SET _ = data RETURN id(_)"
        ^

**Comment by technige** [comment]
What version of Neo4j are you using? The `$x` syntax replaced the old `{x}` syntax, so as it's unrecognised, the chances are your Neo4j version is too old to be compatible.

Also, please use StackOverflow or the Neo4j Community Forum for general support questions. I cannot guarantee to answer those here.
