### ISSUE TITLE
"Node" datastructure  in previous query changed by following query 

### ISSUE THREAD

**Issue by phyank** [technige/py2neo#763]
I found a confusing issue which I think might be a problem for programmers. "Node" object returned  in previous query could be changed by the following query. I think it's because of the reuse of data structure. The following code shows this problem:
```
from py2neo import Graph
from copy import copy

graph = Graph(uri="http://some.host", auth=("user", "pass"))

node=graph.run("MATCH (n:Person{name:'Vincent van Gogh'}) RETURN n;").data()[0]['n']

assert node is not None

# node=copy(node) # uncomment this line to solve this problem

print("id:",id(node))
print("node before change:",node)

node['ghost_property']="will disappear"
print("Adding new property:",node)

assert 'ghost_property' in node

graph.run("MATCH (n:Person{name:'Vincent van Gogh'}) RETURN n;")

print("Ghost property disappeared:")
print("id:",id(node))
print("node:",node)

```
Is it an expected behavior?

**Comment by bebound** [comment]
All of the retrieved `Node` will be cached in `Graph`:`self.graph.node_cache`.
After running second cypher statement, the nodes property will be replaced by data retrieved from neo4j when collecting result.

Run Cypher, collect result:
https://github.com/technige/py2neo/blob/v4.3/py2neo/internal/connectors.py#L367-L386

Refresh `Node` properties:
https://github.com/technige/py2neo/blob/v4.3/py2neo/internal/hydration/__init__.py#L149L152

**Comment by technige** [comment]
This is intended behaviour. Think of local `Node` objects as pointers to nodes in the remote database that hold snapshots of the last known data. When that data is re-read, their content is updated accordingly. If you want to keep hold of the previous data, extract it from the `Node` object into your own data structure.
