### ISSUE TITLE
Py2Neo graph.run() assertionerror

### ISSUE THREAD

**Issue by qianShang-Tj** [technige/py2neo#765]
There is the error:
```
Traceback (most recent call last):
  File "generate.py", line 19, in <module>
    utility.run_cypher('MATCH (r) WHERE id(r) = 18756723 DETACH DELETE r')
  File "E:\utility.py", line 141, in run_cypher
    graph.run(cypher)
  File "C:\Program Files\python3.6\lib\site-packages\py2neo\database.py", line 533, in run
    return self.begin(autocommit=True).run(cypher, parameters, **kwparameters)
  File "C:\Program Files\python3.6\lib\site-packages\py2neo\database.py", line 828, in run
    entities=entities))
  File "C:\Program Files\python3.6\lib\site-packages\py2neo\internal\connectors.py", line 370, in run
    assert r.status == 200  # TODO: other codes
AssertionError
```
And there is the python code:
```
from py2neo import Graph, Node
graph = Graph('http://192.168.xxx.xx', author=('neo4j','xxxxxx'))
graph.run('MATCH (r) WHERE id(r) = 18756723 DETACH DELETE r')
```
Can anyone please tell me how to make py2neo run Cypher correctly?

**Comment by elena** [comment]
Please check your syntax `author` is incorrect.

https://py2neo.org/v4/database.html#py2neo.database.Graph

**Comment by qianShang-Tj** [comment]
@elena Your suggestion is very useful. Thank you for your reply! And I'm sorry for the question in py2neo, because I found nothing such as StackOverflow. Thanks a lot anyway!

**Comment by lmq-1118** [comment]
> @elena Thank you for your reply! Your suggestion is very useful! And I'm sorry for the question in py2neo, because I found nothing on website such as StackOverflow. Thanks a lot anyway!

So how did you finally solve the probelem ?
