### ISSUE TITLE
Target node lable in Graph. But relationshipmatcher.match throw node error. 

### ISSUE THREAD

**Issue by SuFIND** [technige/py2neo#767]
Hi, all!
I hope to use class RelationshipMatcher to get the target path. I try to set node ={...} for limiting the path nodes. 

Follow the code, I use cypher and run it .It's okey. I can get expected data.
```python
cypher = '''
MATCH p=(:XX {xxx_id:'XXX'})-[:r1]->(:YY) 
RETURN p
UNION
MATCH p=(:XX {xxx_id:'XXX'})-[:r1]->(:YY)-[:r2]->(:YY) 
RETURN p
'''
rst = g.run(cypher).to_data_frame()
```
But I use RelationshipMatcher. It caused error **'Node (:XX {}) does not belong to this graph'.** I'm sure node (:XX {}) in this graph. The code like this:
```python
matcher = RelationshipMatcher(g)
way = matcher.match(nodes={'XX', 'YY'},r_type='r1').limit(5)
list(way)
```
So if I want to use RelatinshipMatcher, what I should do? Or maybe a bug?

**Comment by SuFIND** [comment]
OK，emmm.  V4 is my py2neo version.

**Comment by benjaminlaird** [comment]
Also experiencing this. Haven't dug into the source to see why. I'm doing a simple query, in Cypher would roughly be: 
```
MATCH (c:Company {name: "Google"}) <- [r: WORKS_AT] - (p:Person)
RETURN p
```

With `py2neo`: 
```
graph = Graph(...)
matcher = NodeMatcher(graph)
company = matcher.match("Company", name="Google")
RelationshipMatcher(graph).match((None, company), "WORKS_AT").first()
```
returns a Company node that isn't `Google` with 
```
Node {....}
does not belong to this graph
```

Very strange.

**Comment by technige** [comment]
The line `company = matcher.match("Company", name="Google")` assigns a `NodeMatch` object to `company` rather than (as I assume you are intending) a `Node` object.

More than likely, you actually want `company = matcher.match("Company", name="Google").first()` instead.
