### ISSUE TITLE
How to create spatial geographic coordinate with OGM

### ISSUE THREAD

**Issue by zphingphong** [technige/py2neo#768]
```
class ExternalLocation(GraphObject):
    __primarylabel__ = 'ExternalLocation'
    __primarykey__ = 'coordinate'
    street = Property()
    city = Property()
    province = Property()
    country = Property()
    coordinate = Property()
```

In what format should latitude and longitude be saved into the `coordinate` property? Tuple? An array of 2?

py2neo 4.3.0

**Comment by technige** [comment]
The last release of py2neo did not provide any means to input spatial point values; these could only be output in results. The attached commit extracts the point classes `CartesianPoint` and `WGS84Point` into a new `py2neo.spatial` module making them available via constructions such as `p = CartesianPoint((12.34, 56.78))`.

This will be available in the next release.
