### ISSUE TITLE
The first node generated by walk() cannot be transformed into a dictionary

### ISSUE THREAD

**Issue by AlucardNosferatu** [technige/py2neo#770]
Hi, I've encountered a strange thing, that is, while I try to run script directly with follow codes:
`for each in walk(relationship_inst):`
&nbsp;&nbsp;&nbsp;`each_dict = dict(each)`
&nbsp;&nbsp;&nbsp;`print(each_dict)`
the result always show empty dict with first "each" of walk(), I tried to use single action procedure to rearrange the orders of every "each":
`temp=[]`
`for each in walk(relationship_inst):`
&nbsp;&nbsp;&nbsp;`temp.append(each)`
`print(dict(temp[2])`
`#skip temp[1] which is not a Node`
`print(dict(temp[0])`
the result shows that temp[2] is ok but temp[0] output empty dict regardless the running orders of 2 dict(temp[x]):
![image](https://user-images.githubusercontent.com/10172485/67572908-bf065200-f769-11e9-889e-6f95c40bcd30.png)
AND, the most strange part of this issue is that, while toggled debug mode on and switch the breakpoint before dict(temp[0]), the output is OK:
![image](https://user-images.githubusercontent.com/10172485/67573082-173d5400-f76a-11e9-8d0f-80143b1b10dc.png)
this issue has been confirmed non-recurrent without using walk() on a relationship matched from graph (which means you cannot just create 2 nodes and 1 REL to reproduce this phenomenon)

**Comment by AlucardNosferatu** [comment]
Got something intriguing:
I try to match relationship from A to B and B to A, and I found different result:
![image](https://user-images.githubusercontent.com/10172485/67575029-3d64f300-f76e-11e9-8754-1f35661da42b.png)
![image](https://user-images.githubusercontent.com/10172485/67575070-51a8f000-f76e-11e9-91bd-6109dc5966c6.png)
the node able to be transformed into a dict is a node already matched beforehand, even though the return of search() was never been called.

**Comment by AlucardNosferatu** [comment]
Procedure to reproduce:
1.Match a node in a graph
2.Match a relationship with the node matched
3.Walk the relationship while print(dict(each))

**Comment by technige** [comment]
Recreated and verified as a bug.

**Comment by technige** [comment]
The following sequence, when run against an empty database, highlights the issue:
```python
>>> from py2neo import *                                                                             
>>> g = Graph()                                                                                      
>>> a = Node("Person", name="Alice")                                                                 
>>> b = Node("Person", name="Bob")                                                                   
>>> ab = Relationship(a, "KNOWS", b)                                                                 
>>> g.create(ab)                                                                                     
>>> g.node_cache.clear()                                                                            
>>> g.relationship_cache.clear()                                                                    
>>> r = g.match((g.nodes.match("Person", name="Alice").first(),), "KNOWS").first()    
>>> [dict(x) for x in walk(r)]                                                                      
[{'name': 'Alice'}, {}, {}]
>>> g.pull(r)                                                                                       
>>> [dict(x) for x in walk(r)]                                                                      
[{'name': 'Alice'}, {}, {'name': 'Bob'}]
```
