### ISSUE TITLE
Merge crashes when __primarykey__ is not unique

### ISSUE THREAD

**Issue by motey** [technige/py2neo#773]
I had some issues pinning this case down :sweat_smile: 

```python
from py2neo.ogm import GraphObject, Property
from py2neo import Graph

g = Graph(host="localhost", user="neo4j", password="neo4j")


class Thing(GraphObject):
    __primarylabel__ = "Thing"
    __primarykey__ = "val"
    val = Property()

    def __init__(self, val):
        self.val = val


tx = g.begin()
th = Thing("2")
tx.create(th.__node__)
tx.commit()

tx = g.begin()
th = Thing("2")
tx.create(th.__node__)
tx.commit()

tx = g.begin()
th = Thing("2")
tx.merge(th.__node__)
tx.commit()
``` 
Resulting in 
```
Traceback (most recent call last):
  File "/home/USERNAME/Repos/git/dzdgitlab/python-sketches-and-tests/py2neo-orm/tmp.py", line 28, in <module>
    tx.merge(th.__node__)
  File "/home/USERNAME/.local/lib/python3.7/site-packages/py2neo/database.py", line 975, in merge
    merge(self, primary_label, primary_key)
  File "/home/USERNAME/.local/lib/python3.7/site-packages/py2neo/data.py", line 618, in __db_merge__
    merge_subgraph(tx, self, primary_label, primary_key)
  File "/home/USERNAME/.local/lib/python3.7/site-packages/py2neo/internal/operations.py", line 168, in merge_subgraph
    node = nodes[i]
IndexError: list index out of range
``` 
It make sense that merge dont know what to do, if multiple nodes with the same __primarykey__ exists.
I am not sure which behavior would make sense, but the current is not satisfying.

## Current behavior 

Merge throws an "IndexError: list index out of range", as the query for one __primarykey__ returns more than one node and merge is not expecting that

## Better behavior (?)

**Option 1:** Merge just wont do a "create" as there is already a(or more in this case) node(s) existing
**Option 2:** Merge throws an error, but more explicit like "Can not merge as there are multiple nodes with __primarykey__  '<value>'".

Whats your opinion on that?

## Testcase parameters:
**Neo4j version** 3.5.12
```
docker run --rm\
    --publish=7474:7474 --publish=7687:7687 \
    -e NEO4J_AUTH=none \
    --name neo4jtests \
    neo4j
```
**py2neo version:** 4.3.0
**Python version:** 3.7.5rc1

**Comment by benjaminlaird** [comment]
+1 - This is a very opaque error and should be throwing something more specific than an `IndexError`. Independently ran into this same issue yesterday: https://github.com/technige/py2neo/issues/701#issuecomment-552515511

**Comment by mstrofbass** [comment]
I'm thinking that Option 2 makes more sense. In the case of option 1, wouldn't that require selecting one of the multiple options to merge with? Seems like that would result in unpredictable behavior. Further, this can be a result of a bug in code elsewhere (ask me how I know) and option 1 would hide that.

Having dug into this portion of the code earlier, it seems like option 2 or something similar would be easy to implement. (I just printed out the relevant label/key property, not the actual key itself. That was sufficient for me so I didn't look to see if I could print out the actual key value.)

**Comment by emigre459** [comment]
@technige I'm getting this error when simply trying to run `Graph().run("MATCH (p:Publication) RETURN p.title, p.embedding").to_data_frame()` when my graph is connected to a remote Community Edition instance of Neo4j 4.3. If I run it outside of a Jupyter notebook or I `LIMIT` the query (which should return about 29,000 results) or I get rid of the list being return (`p.embedding`), it works fine. 

Is this possibly an OOM error under a different guise? It seems to have starting cropping up after we upgraded from Neo4j 4.2 to 4.3.

**Comment by motey** [comment]
Hi @emigre459, 
I do not believe you run into the same error. You are doing something completely different. Please post the complete error stack.
Having the same resulting error message does not mean having the same error.

Also you already point to your problem and solution 

> . If I run it outside of a Jupyter notebook [..] it works fine

Seems to be an issue with Jupyter Notebook. 
I have some colleagues using Jupyter Notebook and they regulary have weird issues especially with larger results. One reason why I am not a big fan of Jupyter Notebooks. You put a heap of more complexity on your debugging stack.
