### ISSUE TITLE
cache bug with gunicorn

### ISSUE THREAD

**Issue by xubiaosunny** [technige/py2neo#776]
My English is not very good, so I use code to express it

## Environment:

* python3.7
* py2neo4.3.0

my flask demo

```python
# test.py
from flask import Flask, request, jsonify
import requests
from py2neo import Graph

app = Flask(__name__)

graph = Graph('bolt://localhost:7687', auth=('neo4j', '123456'))


@app.route('/py2neo/test', methods=['GET', 'POST'])
def test():
    if request.method == 'POST':
        data = request.json
        name = data.pop('name')
        cypher = f"""
        MERGE (n:Test{{name: '{name}'}})-[r:TestR]->(m:Test2)
        ON CREATE SET r = $x
        ON MATCH SET r += $x
        """
        graph.run(cypher, x=data)
        return jsonify(data)
    name = request.args.get('name')
    cypher = f"""
    MATCH (n:Test{{name: '{name}'}})-[r:TestR]->(m:Test2)
    RETURN r
    """
    results = graph.run(cypher).data()
    return jsonify(results[0]['r'])
```

run flask with gunicorn
```bash
gunicorn -w 4 -b 0.0.0.0:5000 --timeout 300 --access-logfile - --error-logfile - test:app
```
request to my server

```python
import request


requests.post('http://127.0.0.1:5000/py2neo/test', json={'name': 'test', 'age': 1}, headers={ "Content-Type": "application/json"})
print('update to 1')
for _ in range(5):
    print(requests.get('http://127.0.0.1:5000/py2neo/test?name=test').content)
requests.post('http://127.0.0.1:5000/py2neo/test', json={'name': 'test', 'age': 2}, headers={ "Content-Type": "application/json"})
print('update to 2')

for _ in range(5):
    print(requests.get('http://127.0.0.1:5000/py2neo/test?name=test').content)
requests.post('http://127.0.0.1:5000/py2neo/test', json={'name': 'test', 'age': 3}, headers={ "Content-Type": "application/json"})
print('update to 3')

for _ in range(5):
    print(requests.get('http://127.0.0.1:5000/py2neo/test?name=test').content)
```

console output result

```
update to 1
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":1}\n'
update to 2
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":1}\n'
update to 3
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":1}\n'
b'{"age":3}\n'
b'{"age":1}\n'
```

the graph already update ’age‘ to 2 and 3，but flask server still return 1。

This is a bug caused by caching, `ThreadLocalEntityCache` is not working well with gunicorn

**Comment by technige** [comment]
I'm not sure how gunicorn interacts with the thread local behind the cache, but I can easily believe there is an issue here.

The cache exists to avoid many redundant trips to the server. When you iterate a relationship or path, for example, you may already know the details of the nodes it contains from a recent (or the same) results. This is a common case, and the client can hold onto those values, so removing the cache completely from the library is a bad idea, and even allowing it to be disabled could have unforeseen performance consequences.

So this leaves us with the option of _clearing_ the cache explicitly if required. There are a pair a simple incantations for this, depending on whether you want to clear the node or the relationship cache: `g.node_cache.clear()` or `g.relationship_cache.clear()` where `g` is a `Graph object. I recommend you place one or both of these before your second Cypher call.
