### ISSUE TITLE
Node dict disappears unless referenced before acted upon

### ISSUE THREAD

**Issue by darkshade9** [technige/py2neo#782]
Sorry for the terse title, I couldn't think of a shorter way of explaining it.

Issue here is that the dict of the Nodes from a RelationshipMatch (user.start_node) doesn't append to my list unless I call something like str(), print() or repr().  Example:

## See https://py2neo.org/v4/matching.html#py2neo.matching.RelationshipMatch
Works as expected:
```
user_list = []
for user in load_user_in_account:
    print(user)
    user_list.append(dict(user.start_node))
 
print(user_list)
[{age: 31, first_name: 'Charlie',  last_name: 'Kelly'}, {age: 33, first_name: 'Dee', last_name: 'Reynolds'}]
```

Empty dicts in list:
```
user_list = []
for user in load_user_in_account:
    user_list.append(dict(user.start_node))
 
print(user_list)

[{}, {}]
```

Returns only the first index, second index returns {}:
```
user_list = []
for i, user in enumerate(load_user_in_account):
    if i == 0:
        str(user)
    user_list.append(dict(user.start_node))
 
print(user_list)

[{age: 31, first_name: 'Charlie',  last_name: 'Kelly'}, {}]
```

May be related to #770 ?

**Comment by technige** [comment]
Yes, I think it's similar to the other bug. Currently looking into it.
