### ISSUE TITLE
NodeMatcher produces errors when adding relationships to result

### ISSUE THREAD

**Issue by welworx** [technige/py2neo#789]
I need to search for an existing node and add further relation ships (which i assume is pretty common)

i have tried the following methods:
```
project = NodeMatcher(self.db_driver).match("Project", project_id=str(index)).first()
project = Project.match(self.db_driver).where(u"_.project_id = \"%s\"" % str(index)).first()
```

Both find the objects, but when trying to add relationships to them, the second works and the first throws the following error:

```
 site-packages\py2neo\ogm.py", line 249, in <listcomp>
    x=subject_id, y=[obj.__node__.identity for obj, _ in related_objects])

AttributeError: 'Node' object has no attribute '__node__'
```

I have tried it in the version 4.2.0, 4.3.0 and the current one.

**Comment by technige** [comment]
@welworx Can you share the full snippet of code where you try to add the relationship. I assume you are passing a `Node` object to the `add` method, rather than a `GraphObject`.
