### ISSUE TITLE
SyntaxError: The old parameter syntax `{param}` is no longer supported

### ISSUE THREAD

**Issue by msramalho** [technige/py2neo#791]
Using neo4j 4.0.0

Using py2neo v4

`g.nodes.match(U, _id=3125349375).first()`

yields:
```
ClientError: SyntaxError: The old parameter syntax `{param}` is no longer supported. 
Please use `$param` instead (line 1, column 30 (offset: 29))
"MATCH (_:USER) WHERE _._id = {1} RETURN _"
```

**Comment by vishal-akg** [comment]
i also started receiving this error when i installed latest neo4j verions 4.0.0. In neo4j document they have changed little bit of cypher syntax for using parameters,  without providing backward compatibility , so py2neo has comply with their new syntax.

**Comment by lovesuper** [comment]
I have this issue too. When fix?

**Comment by dcsan** [comment]
same here, sad to say.
is there any way to do read queries (simple match) with py2neo now or do we have to drop down to `.run` for everything?

```
        matcher = NodeMatcher(Topic.graph)
        found = matcher.match("Topic", name=cname )


py2neo.database.ClientError: SyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 32 (offset: 31))
"MATCH (_:Topic) WHERE _.name = {1} RETURN count(_)"
```

I also tried  ` '$name'=name` but that's illegal python syntax,

**Comment by Kyle-is-online** [comment]
I just renamed all the "{x}" instances to "$x" in the internal/operations.py file. It fixed the bug for now but I wonder if this is safe and if it won't break something else.

**Comment by dcsan** [comment]
so is this a change with the neo4j version 4 and the way it matches queries?

**Comment by dcsan** [comment]
@Kyle-is-online maybe you can publish a new version of the driver 🥇

**Comment by Kyle-is-online** [comment]
@dcsan Cool, my first issue

**Comment by Kyle-is-online** [comment]
@dcsan Could you elaborate please? Do you mean publishing the latest version on pypi.org? Sorry, I'm new here.

**Comment by dcsan** [comment]
@Kyle-is-online yes. or maybe make your fork public?
you won't be able to publish under that name, but maybe a separate name.
or if the URL is public, it's also possible to install directly from a github URL (risky!)
https://codeinthehole.com/tips/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/

I'm also personally more familiar with the nodeJS package ecosystem but seems similar things work with pip

**Comment by Kyle-is-online** [comment]
@dcsan Funny how in this case the stable release on pypi was less functional than the bleeding edge code. Guess I'll just use it until @technige updates the pip package. This issue has to be marked as solved, doesn't it?

**Comment by dh12306** [comment]
anyone knows how to fix the problem？ thx

**Comment by sdabhi23** [comment]
> I just renamed all the "{x}" instances to "$x" in the internal/operations.py file. It fixed the bug for now but I wonder if this is safe and if it won't break something else.

@Kyle-is-online @dcsan This fixes problems in pull and push, but it still throws error during node matching

**Comment by RayDean** [comment]
Hi:
I solved this problem by changing the function _property_conditions() in matching.py like this:

def _property_conditions(properties, offset=1):
    for i, (key, value) in enumerate(properties.items(), start=offset):
        if key == "__id__":
            condition = "id(_)"
        else:
            condition = "_.%s" % cypher_escape(key)
        if value is None:
            condition += " IS NULL"
            parameters = {}
        elif isinstance(value, (tuple, set, frozenset)):
            # condition += " IN {%d}" % i # changed here , use $ instead of {}
            condition += " IN $%d" % i
            parameters = {"%d" % i: list(value)}
        elif re.match(_operators_search, key):
            parts = re.search(_operators_search, key)
            prop = parts.group(1)
            operator = parts.group(2)
            # condition = "_.%s %s {%d}" % (prop, _operators[operator], i) # changed here , use $ instead of {}
            condition = "_.%s %s $%d" % (prop, _operators[operator], i)
            parameters = {"%d" % i: value}
        else:
            # condition += " = {%d}" % i # changed here , use $ instead of {}
            condition += " = $%d" % i
            parameters = {"%d" % i: value}
        yield condition, parameters

Seems it works. Good Luck

**Comment by axxe-git** [comment]
This issue with the new vs old cypher syntax seems to be cropping up in multiple places in py2neo. Explicitly executing a Graph().run() with the new cypher argument syntax for a path-finding query is resulting in this error being thrown in the `pull_subgraph()` method in  `internal/operations.py`. Looks like this is going to need several changes to be fixed across py2neo.

**Comment by technige** [comment]
In the v5 beta released today, these should all now use the new syntax.

`pip install py2neo==5.0b1`

**Comment by dcsan** [comment]
is 5.0b backward compatible before neo4j v4 ? eg 3.6 series?
or there is some sync we need to do keep right versions matching?

**Comment by technige** [comment]
Most features will be backward compatible, yes.

**Comment by hmthanh** [comment]
Thansk you so much !

**Comment by createrfang** [comment]
thank you
