### ISSUE TITLE
Use of triple-double quotes in queries to enable the use of double-quote as property?

### ISSUE THREAD

**Issue by welworx** [technige/py2neo#794]
# Problem
Tying to add a property with a double-quote leads to the following error:

```
ClientError: SyntaxError: Invalid input '"': expected whitespace, '.', node labels, '[', "=~", IN, STARTS, ENDS, CONTAINS, IS, '^', '*', '/', '%', '+', '-', '=', '~', "<>", "!=", '<', '>', "<=", ">=", AND, XOR, OR, FROM GRAPH, CONSTRUCT, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE UNIQUE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, CALL, RETURN, UNION, ';' or end of input (line 1, column 34 (offset: 33))
"MATCH (_:Token) WHERE _.text = """  RETURN _"
```
# With cypher_escape 
With the use of cypher_escape the following error is returned:
```
ClientError: SyntaxError: Invalid input '`': expected whitespace, '.', node labels, '[', "=~", IN, STARTS, ENDS, CONTAINS, IS, '^', '*', '/', '%', '+', '-', '=', '~', "<>", "!=", '<', '>', "<=", ">=", AND, XOR, OR, FROM GRAPH, CONSTRUCT, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE UNIQUE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, CALL, RETURN, UNION, ';' or end of input (line 1, column 35 (offset: 34))
"MATCH (_:Token) WHERE _.text = "`"`"  RETURN _"
```

# Possible solution:
Can the use of triple-double quotes solve this problem?
`""" MATCH (_:Token) WHERE _.text = """  RETURN _ """`

# Info
py2neo version: 4.2.0

**Comment by technige** [comment]
This is not related to Python string escaping. This is related to the Cypher engine's ability to parse the string. You have 3 options:

1. Use single quotes around the string, e.g. `RETURN '"'`
2. Escape the quote, e.g. `RETURN "\\""` (this will probably need double escaping unless you use an r"" string
3. Pass the value as a parameter, e.g. `RETURN $x` with parameters `{"x": "\""}`

Best practice would be to go for option 3.
