### ISSUE TITLE
Can't begin a new transaction

### ISSUE THREAD

**Issue by TIANRENK** [technige/py2neo#798]
when I run graph.create(node)

RuntimeError: Can't begin a new transaction.

**Comment by wulaoshi** [comment]
> when I run graph.create(node)
> 
> RuntimeError: Can't begin a new transaction.

Hi，do u resolve the problem? I also had the same problem.

**Comment by DeweiHu66666** [comment]
Same with you guys

**Comment by technige** [comment]
Cannot diagnose this without more context.

**Comment by technige** [comment]
Closing due to lack of detail.

**Comment by Ylizi** [comment]
py2neo/internal/ connetors.py Can't begin a new transaction
