### ISSUE TITLE
Contradictory requirements after installing py2neo 4.1.3

### ISSUE THREAD

**Issue by V61K** [technige/py2neo#800]
**A.   After running: 
pip install -U jupyter_console**

I get:
ERROR: py2neo 4.1.3 has requirement prompt-toolkit==1.0.15, but you'll have prompt-toolkit 3.0.5 which is incompatible.
Installing collected packages: prompt-toolkit
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 1.0.15
    Uninstalling prompt-toolkit-1.0.15:
      Successfully uninstalled prompt-toolkit-1.0.15
Successfully installed prompt-toolkit-3.0.5
-------------------------------------------------------------------------- 
**B.  in jupyter notebook, after:  
!pip install py2neo==4.1.3**

I get the following error:
ERROR: jupyter-console 6.1.0 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
ERROR: ipython 7.13.0 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
===========
**The result is that the kernel is crashing.
Any solutions ?**

**Comment by technige** [comment]
Upgrade to the latest release.
