### ISSUE TITLE
Is there an efficient way to bulk import data?

### ISSUE THREAD

**Issue by hscspring** [technige/py2neo#802]
I am now using this way to import data:

```python
# (Keanu, Act, Neo)
for start, relation, end in item:
    start = nmatcher.match("Person", name=start).first() or Node("Person", name=start)
    end = nmatcher.match("Person", name=end).first() or Node("Person", name=end)
    relation = Relationship(start, relation, end)
    tx = graph.begin()
    tx.create(relation)
    tx.commit()
```

the speed is 60 items/sec, seems a little slower.

**Comment by Wenzel** [comment]
I'm also wondering what's the best way to create thousands or more nodes with `py2neo`.

A transaction will only bring you the safety of being able to roll back, it's not about performance, each time you do `tx.create(x)`, the remote node is created if it does not exists, which implies a network communication and processing by Neo4j server.

@technige Any performance advices you would like to share ?

**Comment by Wenzel** [comment]
@hscspring According to this blog post, using an OGM kills the performance:

> The next thing to do is completely forget object mappers.

> You can find Neo4j-ogm in Java, Python, etc. but when you want to write fast and you need to write personalized queries for your writes and domain, the Object-Graph Mapper (OGM) adds a lot of overhead, is not made for batch imports and keeps you from going fast.

> So if you want to write 100,000 nodes as fast as possible, it doesn’t make sense to use object mappers.

**Comment by hscspring** [comment]
@Wenzel Yep, I've read the document. They recommended to use `neo4j-admin`, that make sense, we could preprocess the dataset first, and then batch import them. It's a one-pass task,
we do not need to use ORM.

Here are the some references:

- [CSV Import Guide: How to Use LOAD CSV Command for Neo4j](https://neo4j.com/developer/guide-import-csv/)
- [CSV Import Guide: How to Use LOAD CSV Command for Neo4j](https://neo4j.com/developer/guide-import-csv/)
- [Bulk importing data from CSV files – Neo4j Aura](https://aura.support.neo4j.com/hc/en-us/articles/360040985554-Bulk-importing-data-from-CSV-files)

**Comment by motey** [comment]
https://github.com/kaiserpreusse/graphio is also an alternative
