### ISSUE TITLE
OGM: TypeError: Cannot cast Person to Node

### ISSUE THREAD

**Issue by Wenzel** [technige/py2neo#805]
Hi,

I'm having an issue with the `py2neo` OGM.
I'm playing with the `movies` database from neo4j:
![Capture d’écran de 2020-05-31 09-32-31](https://user-images.githubusercontent.com/964610/83346990-bdb18f00-a321-11ea-897b-aebc158456a7.png)

And the following lines are triggering a `TypeError` in `py2neo`
~~~Python
from py2neo.ogm import GraphObject, RelatedTo, Property

# define Person Node
class Person(GraphObject):
    name = Property()
    born = Property()
    acted_in = RelatedTo('Person', 'ACTED_IN')

    def __init__(self, name, born):
        self.name = name
        self.born = born

# find Tom Hanks
tom_hanks_node = Person.match(graph).where(f"_.name = 'Tom Hanks'").first()
# find all Movies where Tom Hanks ACTED_IN
graph.match((tom_hanks_node, None), 'ACTED_IN').first()
~~~

~~~Python
In [117]: graph.match((tom_hanks_node, None), 'ACTED_IN').first()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-117-955f34abc553> in <module>
----> 1 graph.match((tom_hanks_node, None), 'ACTED_IN').first()

~/Projets/oswatcher/venv/lib/python3.8/site-packages/py2neo/matching.py in first(self)
    277         :return: a single matching :class:`.Relationship` or :const:`None`
    278         """
--> 279         return self.graph.evaluate(*self._query_and_parameters())
    280 
    281     def _query_and_parameters(self, count=False):

~/Projets/oswatcher/venv/lib/python3.8/site-packages/py2neo/matching.py in _query_and_parameters(self, count)
    310         elif isinstance(self._nodes, Sequence):
    311             if len(self._nodes) >= 1 and self._nodes[0] is not None:
--> 312                 start_node = Node.cast(self._nodes[0])
    313                 verify_node(start_node)
    314                 clauses.append("MATCH (a) WHERE id(a) = {x}")

~/Projets/oswatcher/venv/lib/python3.8/site-packages/py2neo/data.py in cast(cls, obj)
    823 
    824         inst = Node()
--> 825         apply(obj)
    826         return inst
    827 

~/Projets/oswatcher/venv/lib/python3.8/site-packages/py2neo/data.py in apply(x)
    820                 inst.add_label(ustr(x))
    821             else:
--> 822                 raise TypeError("Cannot cast %s to Node" % obj.__class__.__name__)
    823 
    824         inst = Node()

TypeError: Cannot cast Person to Node
~~~

However, using the `NodeMatcher` instead of the OGM works:
~~~Python
matcher = NodeMatcher(graph)
tom_hanks_node = matcher.match('Person', name='Tom hanks').first()
graph.match((tom_hanks_node, None), 'ACTED_IN').first()
-> (Rita Wilson)-[:ACTED_IN {roles: ['Suzy']}]->(_1)
~~~

I think this is a bug in the OGM @technige 

Using:
- **py2neo==4.3.0**
- **Neo4j 3.4**

Thanks !

**Comment by technige** [comment]
This is not a bug. The problem is due to mixing two separate layers of API. In particular, the following two lines use the OGM API and the lower-level Node API respectively:

```
# find Tom Hanks
tom_hanks_node = Person.match(graph).where(f"_.name = 'Tom Hanks'").first()
# find all Movies where Tom Hanks ACTED_IN
graph.match((tom_hanks_node, None), 'ACTED_IN').first()
```

In addition, there are a couple of problems with your class definition as well. Firstly, you don't define a `__primarykey__` which is generally essential. Secondly, `acted_in` should be related to a `Movie` instance, rather than a `Person` instance.

For the movies database, there are examples of these classes already in the py2neo docs:
```
class Movie(GraphObject):
    __primarykey__ = "title"

    title = Property()
    tag_line = Property("tagline")
    released = Property()

    actors = RelatedFrom("Person", "ACTED_IN")
    directors = RelatedFrom("Person", "DIRECTED")
    producers = RelatedFrom("Person", "PRODUCED")


class Person(GraphObject):
    __primarykey__ = "name"

    name = Property()
    born = Property()

    acted_in = RelatedTo(Movie)
    directed = RelatedTo(Movie)
    produced = RelatedTo(Movie)
```

Finally, for clarity, `tom_hanks_node` should probably be renamed to `tom_hanks_person` or just `tom_hanks`. This will contain a `Person` instance, not a `Node` instance, and the two are not the same thing.

So to tackle this, you either need to explicitly translate between the two layers, or align to use a single API layer. I'd generally advise the latter for better code hygiene.

In your case, you can simply iterate through the `tom_hanks_node.acted_in` attribute to retrieve those movies. With these adjustments, you should see something like:

```
>>> tom_hanks = Person.match(graph).where("_.name = 'Tom Hanks'").first()                                                                                 
>>> list(tom_hanks.acted_in)                                                                                                                              
[<Movie title='A League of Their Own'>,
 <Movie title='Cloud Atlas'>,
 <Movie title='The Da Vinci Code'>,
 <Movie title='Sleepless in Seattle'>,
 <Movie title='The Polar Express'>,
 <Movie title='The Green Mile'>,
 <Movie title='Cast Away'>,
 <Movie title="Charlie Wilson's War">,
 <Movie title='That Thing You Do'>,
 <Movie title='Joe Versus the Volcano'>,
 <Movie title='Apollo 13'>,
 <Movie title="You've Got Mail">]
```

**Comment by Wenzel** [comment]
@technige thank you very much for this detailed answer !

A couple of remarks:
> In particular, the following two lines use the OGM API and the lower-level Node API respectively

I think the documentation is not making it very clear that we cannot mix both of these APIs.

Can you put a :warning:  warning sign that advertise this in the front page of the [OGM](https://py2neo.org/v4/ogm.html) docs ?
Otherwise, I believe other people will get tricked into mixing these APIs, and follow the same path I did.

Furthermore, is there a way you could detect this issue internally in `py2neo`, and add a complementary message to the exception being raised ?
`TypeError: Cannot cast Person to Node. (Are you mixing the OGM and lower-level Node APIs ?)`

> In addition, there are a couple of problems with your class definition as well. Firstly, you don't define a __primarykey__ which is generally essential.

Per the documentation, I didn't clearly understood that it was something absolutely essential to define:

[`__primarykey__`](https://py2neo.org/v4/ogm.html#py2neo.ogm.py2neo.ogm.GraphObject.__primarykey__)
> The primary property key used for Cypher MATCH and MERGE operations. If undefined, the special value of "__id__" is used to hinge uniqueness on the internal node ID instead of a property. Note that this alters the behaviour of operations such as Graph.create() and Graph.merge() on GraphObject instances.

So if the Node's `__id__` property is used, it should be unique, as each Node in the graph get's a unique `ID` when created ? :thinking: 
The docs didn't make it clear that this is an issue, as it is indicated that a default behavior is defined by `py2neo`.

> Secondly, acted_in should be related to a Movie instance, rather than a Person instance.

Indeed, that's my fault ! :-)

Thank you.
