### ISSUE TITLE
Cypher unescape function

### ISSUE THREAD

**Issue by Wenzel** [technige/py2neo#807]
Hi,

I'm using a function of your library, [`cypher_escape`](https://github.com/technige/py2neo/blob/py2neo-4.3.0/py2neo/cypher/__init__.py#L29), in `py2neo.cypher` to properly escape a Python string for Neo4j.

Is there an equivalent function to do the reverse operation, `cypher_unescape` ?

Thanks.

**Comment by technige** [comment]
There isn't. What exactly are you trying to achieve? Where are you getting an escaped value from, that you need to unescape?

**Comment by Wenzel** [comment]
Hi Nigel,

basically I'm dealing with a filesystem that I want to insert in Neo4j.

I divide the Path and each relationships `:HAS_CHILD` has a property `name` that contains the filename.

Some files may appear like this `/boot/grub/i386-pc/multiboot2.mod`
After using `cyper_escape` and created the relationships, when you query `relationships(path)`, you will get:
`["boot", "grub", "`i386-pc`", "`multiboot2.mod`"]`

So is a `cypher_unescape` function equivalent to removing the backticks in the string ?
~~~Python
def cypher_unescape(string: str) -> str:
    return string.strip('`')
~~~

Or are there more things to do to find the original Python string ?

Thanks !

**Comment by technige** [comment]
The `cypher_escape` function is for use in preparing inline identifiers within Cypher query text. It is not related to storing string values in properties. In the general case, you probably don't need it, unless you are compiling Cypher queries using string concatenation.
