### ISSUE TITLE
specifying data types of properties in the OGM

### ISSUE THREAD

**Issue by diegoquintanav** [technige/py2neo#830]
Say I have a model using the OGM module from py2neo

```python
from py2neo.ogm import GraphObject

class Person(GraphObject):
    name = Property()
    age = Property()
```

I wish to persist a node `Person(name="diego", age=22)`.  There's nothing that stops me from passing the number 22 as a string e.g. "22".  Is there anything like, say, `name = Property(dtype=str)` available in py2neo that attempts to cast args from the `__init__` to these dtypes?

**Comment by diegoquintanav** [comment]
I've tried subclassing the `Property` class

```python
class CustomProperty(Property):
    """Implements a datatype"""

    def __init__(self, **kwargs):
        dtype = kwargs.pop("dtype")
        if dtype is not None:
            self.dtype = dtype
        super().__init__(**kwargs)

    def __set__(self, instance, value):
        if hasattr(self, "dtype"):
            instance.__node__[self.key] = self.dtype(value)
```

with this

```python
class Person(GraphObject):
    name = CustomProperty(dtype=str)
    age = CustomProperty(dtype=int)
```

I guess this should raise some type of exception, but so far it works.

**Comment by technige** [comment]
No, there is no such functionality. Neo4j itself does not enforce such a schema: a property value may be of any type, and may be different from similarly-named properties on other nodes. And may even not exist at all. So this flexibility is surfaced fully into the OGM.

**Comment by gabrieldelaparra** [comment]
Hi,

I think that you are looking for SHACL. Neo4j supports it: https://neo4j.com/docs/labs/nsmntx/current/validation/

Cheers,

**Comment by diegoquintanav** [comment]
Hi @technige! thanks for your reply. You are right when you say that neo4j does not enforce a schema, but just for the record, it does support datatypes.

https://neo4j.com/docs/cypher-manual/current/syntax/values/#property-types

and apoc supports them as well through a `mapping`

https://neo4j.com/docs/labs/apoc/current/import/load-csv/#_configuration_options

and also it seems that the `graph.evaluate` method of the py2neo library supports datatypes, if I'm not mistaken

https://github.com/technige/py2neo/blob/2ca8de4c3e523979bf92871b6731e8d3b1474b80/test/integration/test_types.py

**Comment by technige** [comment]
@diegoquintanav I'm aware of the page on data types in the Neo4j manual. I wrote it :-P

Your original question was around the enforcement or automatic coercion of data types by OGM and Neo4j/or itself for any given property. This functionality is absolutely not provided by either py2neo or the core Neo4j product. I cannot comment offhand on non-core products such as neosemantics or APOC as I'm not massively familiar with either. But py2neo itself is built only against core Neo4j and, as such, the statement stands.

The `graph.evaluate` method (similarly to the `graph.run` method) can return data of any type, depending on your query. But I don't see how this relates to your original question. Property values in the core database can still contain any type, and may have different values to similarly names properties on other nodes. No type constraint functionality is available at any layer: this would still have to be enforced by your application.
