### ISSUE TITLE
Py2neo graph.run.data not retrieving records even when present in the graph

### ISSUE THREAD

**Issue by karanthpallavi** [technige/py2neo#833]
Have used the following code snippet:

for i in listSignalNames:
       query = '''MATCH(n) WHERE n.name CONTAINS "{ }" RETURN(n)'''.format(i)
       results = query.run.data()
       print(results)

This retrieves node names containing the string specified in i only for few nodes,
Though many nodes are present in the graph, this is unable to get node names of those nodes,
It returns [ ] as query result,
Any idea how this can be resolved?
Thanks

**Comment by karanthpallavi** [comment]
Can I get a response for this one?

query.run.data() is unable to fetch the results from graph though the nodes are present in the graph,

Kindly help in resolving this issue

**Comment by technige** [comment]
Your example code makes no sense. You are trying to call the `run` method on `query`, which is itself a string.

Given that the `data()` method _definitely_ works (it is used very regularly) then this will be user error of some kind. Either the database does not contain what you think it does, you query is incorrect Cypher, or you are not reading the results correctly.
