### ISSUE TITLE
Getting cypher substring from py2neo objects (node, relation, subgraph)

### ISSUE THREAD

**Issue by peey** [technige/py2neo#838]
Hi, I like the programmability offered by py2neo objects.

However, as you note in your documentation, `tx.merge` operation differs from the `MERGE` query.

I was wondering if I could just create the subgraph structure using these objects and get them as a string which I could use in a merge query I create myself.

Is that possible?

**Comment by technige** [comment]
No, none of these internals are exposed through API.
