### ISSUE TITLE
Adding related objects has unexpected behavior in OGM

### ISSUE THREAD

**Issue by smokeyflavor** [technige/py2neo#839]
Let's say I have a `Book(GraphObject)` which relates to `Page(GraphObject)`.
Book has a `pages = RelatedTo(Page, 'HAS_PAGE')` property.

This following code will only add the last page to the object:
```
book = Book()
page1 = Page()
page1.name = 'Index'
page2 = Page()
page2.name = 'Preface'
page3 = Page()
page3.name = 'Chapter One'
book.pages.add(page1)
book.pages.add(page2)
book.pages.add(page3)
```

This happens because when you call `.add()`, the code checks if the added object is already in the relationship list.
The `__eq__` code does that by comparing `__primarykey__` and `__primaryvalue__`, which in this case are equal, because the default primary key is `<id>` and the value is `None` (since the node is not even in the DB yet). Therefore, each call to `add()` would result in the previous node being replaced with the new one, and no additions would be made.

A workaround would be to `push()` the new page nodes first, then each one would have a primary value set. 

This behavior is unexpected, and can lead to major data loss. `add()` is also a bad name for this function since it doesn't describe the function as you would expect. It actually checks for duplicates and then replaces them, and only then considers adding.

**Comment by technige** [comment]
Confirmed as a bug due to unintended behaviour. I will work on a fix.
