### ISSUE TITLE
Node update not working

### ISSUE THREAD

**Issue by alvarolloret** [technige/py2neo#843]
I'm using py2neo==5.0b5 # https://py2neo.org/v5/

I get a node instance such as this:
`node = (_735:Patient {active: true, born_date: [2020, 9, 1], id: 62, status_score: 0})`
when I invoke the update method on the node such as:
```
dict_update = {'born_date': 'update'}
node1 = node.update(dict_update)
```
The node returned is equal to None, how is that possible?

**Comment by technige** [comment]
Just as with the built-in `dict.update` method, the function mutates the object, it does not return an updated copy of it. Therefore, your code is incorrect in expecting a return value.
