### ISSUE TITLE
How to get the properties of a Related key using OMG?

### ISSUE THREAD

**Issue by jcaviedesc** [technige/py2neo#848]
Taking the example of the movies
```python
class Person(Model):
    __primarykey__ = "name"

    name = Property()

    know = RelatedTo("Person")
```
suppose I have  three relationships of type  `(a)-[:KNOW { created_at: date, match: 0.8 }]->(b)`
i want get relationship properties
```python
for friend, properties in person.know:
    print("{} -> {}".format(friend.name, properties))
```
OUTPUT 
`juan ->  { created_at: date, match: 0.3 }`
`pedro -> { created_at: date, match: 0.5 }`
`Deivid -> { created_at: date, match: 0.8 }`

**Comment by technige** [comment]
While this is possible, the syntax is far from obvious. Issue #854 describes how to currently do it, and is a reminder to me to design an improved API for this.

**Comment by technige** [comment]
As of the next release, this will be possible with the `triples` method, e.g. `list(person.know.triples())` as added in https://github.com/technige/py2neo/commit/de60f4a51eba492497c3e30ba1aaf74aed94d555
