### ISSUE TITLE
OGM Related().add() only inserts one direction, instead of bidirection

### ISSUE THREAD

**Issue by mockingjet** [technige/py2neo#849]
What I expect:
![image](https://user-images.githubusercontent.com/32839503/93757698-cb28b700-fc39-11ea-8bf1-4f1fa9641438.png)

But I get:
![image](https://user-images.githubusercontent.com/32839503/93757795-ee536680-fc39-11ea-8ef4-c5f3d9b44e57.png)

See my code: 
https://repl.it/@nothinghappens/py2neo-demo#main.py
line 97-100, 107-109

**Comment by elena** [comment]
This is the correct behaviour as Cypher only creates relationships in one-direction.

If you want to do bi-directional relationships you need to create them through a 2nd relationship creation process.

The documentation is here: https://neo4j.com/docs/cypher-manual/current/syntax/patterns/

**Comment by mockingjet** [comment]
@elena Thanks.

OGM provides Related, RelatedTo, and RelatedFrom three kinds of relationship direction. 

And I inspect the source code and found that each has direction value respectively -- UNDIRECTED, OUTGOING, INCOMING.

So it's not a Bidrection as I thought.
