### ISSUE TITLE
The ability to create relationships of the same kind between nodes

### ISSUE THREAD

**Issue by fakegermano** [technige/py2neo#851]
Hello!

As I found myself using this library I stumbled upon the particular way the **Relationship** class works, and how it's uniqueness and equality is measured against the remote database.

We all know neo4j supports the ability to create a relationship of a particular type between two nodes any number of times. It may not be very usual to have this type of relationship, but it exists out there in the world.

However, when using this library, the **Relationship** class states (in it's documentation):

_Relationship equality is based on equality of the start node, the end node and the relationship type (node equality is described above). This means that any two relationships of the same type between the same nodes are always considered equal. Note that **this behavior differs slightly from Neo4j itself** which permits multiple relationships of the same type between the same nodes._

As the documentation clearly states, this behavior is somewhat different from what neo4j supports.

Is it on this library's roadmap to someday support this kind of behavior? It will be very much appreciated if it is!

**Note**: I do understand the need to develop a feature that is backwards compatible with the current behavior, so my suggestion is that the relationship may have a `__primarykey__` property (much like the **Node** class works) that defaults to the label of the relationship, but can be overwritten by the user to some other underlying property of the **Relationship** so that the creation, matching and equality behavior matches that which neo4j supports.

This is a fantastic library with many useful abstractions over the default neo4j driver for python, and I look forward to your feedback on the matter.

**Comment by technige** [comment]
Thanks for your feedback. This was a design decision I made some time ago on the basis that (1) the client-side code would be easier to implement (2) I personally consider this to be bad graph data modelling practice, as it is generally semantically meaningless, and (3) where such multiple relationships exist, they should probably instead by represented by nodes. On a similar note, I would consider heavy use of relationship properties to be a bad code (model?) smell.

However, I do appreciate your point on legacy data models. For those I would recommend dropping down an abstraction level into Cypher, or (if possible) considering migration to a different model. Even if I now considered my previous decision to be incorrect or incomplete (which I don't) this py2neo functionality is very well established _at this level of abstraction_.

FWIW I also personally disagree with the original design choices of Neo4j in allowing such relationships to exist. That decision does however pre-date even my decade-long involvement with the software.

So I'm afraid this is a _wontfix_.
