### ISSUE TITLE
map function over nodes

### ISSUE THREAD

**Issue by matiasmorant** [technige/py2neo#858]
I would like to be able to map a function over nodes in a `NodeMatch`

```
g=Graph('bolt://localhost:7687')
node_match = g.nodes.match("Person")
node_match.map('_.name').all() # something like this
```

**Comment by technige** [comment]
I'm not quite sure what you're after here. If you mean that you want to carry out a Cypher operation on a set of matched nodes, then simply use a Cypher query, such as `MATCH (a:Person) RETURN a.name`, instead of the `match` method.

**Comment by matiasmorant** [comment]
Yes, that's it. Sure I could write Cypher, but I thought the point of py2neo was not having to write Cypher directly?

**Comment by technige** [comment]
Not at all. Py2neo provides _some_ higher level functions, but it's far from being a complete replacement for Cypher - that has never been the intention.

In the case you show above though, I'd suggest using something like the following:
```
[person["name"] for person in g.nodes.match("Person").all()] 
```

This should still avoid you needing to run Cypher.
