### ISSUE TITLE
How can I match relations for a bulk of node?

### ISSUE THREAD

**Issue by qwzlh** [technige/py2neo#863]
Hello, i want to check reltation of a bulk of node, here is my code:

for node1, node2 in node_list:
     if r_matcher.match([node1, node2]).first() is not None:
        print(1)

there is about 10000 node pairs in node_list, and I find that matching the relation one by one costs lots of time.
how can i make this code efficien?

**Comment by technige** [comment]
Sorry but I cannot answer general usage questions here.
