### ISSUE TITLE
ConnectionUnavailable: Cannot open connection to ConnectionProfile('bolt://

### ISSUE THREAD

**Issue by pwrose** [technige/py2neo#870]
I'm trying to connect to a Neo4j instance using py2neo in a Jupyter Notebook running on Mybinder.org. See the example here:
https://mybinder.org/v2/gh/pwrose/ipycytoscape/HEAD?filepath=examples%2FNeo4j_Example.ipynb

I'll get the following error:

ConnectionUnavailable: Cannot open connection to ConnectionProfile('bolt://...')

What causes this problem and how can I work around it?

**Comment by technige** [comment]
It'll be down to a local network issue. I have no way to diagnose your problem.
