### ISSUE TITLE
convert the 'run' function results to list is too slow and hang

### ISSUE THREAD

**Issue by lancexiang** [technige/py2neo#874]
when i run `list(map(lambda x: x['r2'], nccn_graph.graph.run("match (m)-[r1]->(n)-[r2]->(o) where id(m)=1 and o.type='Strategy' return r2")))`, the program hang, and when there are about 300 relationships, the time cost is about 1min, it's too slow, how can i fix it properly?

**Comment by technige** [comment]
Please check performance in the 2021.0.0 release. This should now be improved.
