### ISSUE TITLE
Consumption of results from large query takes long

### ISSUE THREAD

**Issue by mpreusse** [technige/py2neo#875]
When I run a Cypher query that returns a large number of rows it takes unexpectedly long to consume the results. 

Here is a self-contained example that creates 250k nodes and then runs a query to return the properties of those nodes. To test consumption of results, it runs the `.to_data_frame()` function, the `.data()` function and iterates the result cursor. All functions take ~90 seconds to complete (i5 from 2016). The timing is done with `linetimer`. I tried Python 3.7 and 3.8, no difference.

```python
from py2neo import Graph
from linetimer import CodeTimer

graph = Graph(host='localhost', port=7687, password='test')

graph.run('MATCH (a) DETACH DELETE a')

graph.run("""UNWIND range(0, 250000) as i CREATE (t:Test) 
SET t.a = 'aaaaaaaaa', t.b = 'bbbbbbbbb', t.c = 'ccccccccc'
""")

# large data query
query = 'MATCH (t:Test) RETURN t.a as a, t.b as b, t.c as c'

results = graph.run(query)
with CodeTimer('Iterate over list of results', unit='s'):
    for x in results:
        pass

results = graph.run(query)
with CodeTimer('.to_data_frame()', unit='s'):
    results.to_data_frame()

results = graph.run(query)
with CodeTimer('.data()', unit='s'):
    results.data()
```

I ran cProfile and the output shows a very high number of calls to `__init__` of namedtuple and something in `packstream`:

<img width="1005" alt="snakeviz" src="https://user-images.githubusercontent.com/6180358/106655722-05b44000-659a-11eb-9a2f-9649ec82658c.png">

Is it possible to improve result consumption/handling on Python side? I don't really understand whats going on but iterating 250k rows in the result object should be faster I think.

**Comment by lancexiang** [comment]
I have the same question! And my situation is more severer than yours', when i travel the 2000 relationships, it tooks about 40s with Cypher query only consume 0.3s, i don't know how to solve this.

**Comment by technige** [comment]
I've just performed some minor refactoring on the hydration function and, using your test script @mpreusse, have seen the following improvements:

Before:
```
Code block 'Iterate over list of results' took: 87.24387 s
Code block '.to_data_frame()' took: 93.95999 s
Code block '.data()' took: 93.11120 s
```

After:
```
Code block 'Iterate over list of results' took: 12.74957 s
Code block '.to_data_frame()' took: 17.12523 s
Code block '.data()' took: 16.93152 s
```

This seems like a significant improvement.

The hydration function is called for each value in a result, and it previously contained some time-consuming but redundant lines of code. These have now been moved to module level, so they are no longer executed for each call.

**Comment by technige** [comment]
Please check performance in the 2021.0.0 release. This should now be improved.

**Comment by mpreusse** [comment]
That's fantastic, thank you @technige! 

Out of curiosity: Why does it still take 12 seconds? The data is transported over the wire before the iteration, right?

Is there a more efficient way to get at the data, maybe using the Neo4j driver?

**Comment by mpreusse** [comment]
For reference: Running the query with the Neo4j driver is significantly faster for me. Here is an extended test script that includes the driver:

```python
from py2neo import Graph
from linetimer import CodeTimer
from neo4j import GraphDatabase

# py2neo
graph = Graph(host='localhost', port=7687, password='test')
# Neo4j driver
uri = "neo4j://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "test"))

# delete DB
graph.run('MATCH (a) DETACH DELETE a')
# create nodes
graph.run("""UNWIND range(0, 250000) as i CREATE (t:Test) 
SET t.a = 'aaaaaaaaa', t.b = 'bbbbbbbbb', t.c = 'ccccccccc'
""")

# large data query
query = 'MATCH (t:Test) RETURN t.a as a, t.b as b, t.c as c'

# test py2neo
with CodeTimer('py2neo: get result', unit='s'):
    results = graph.run(query)
with CodeTimer('py2neo: Iterate over list of results', unit='s'):
    for x in results:
        pass

with CodeTimer('py2neo: get result', unit='s'):
    results = graph.run(query)
with CodeTimer('py2neo: .to_data_frame()', unit='s'):
    results.to_data_frame()

with CodeTimer('py2neo: get result', unit='s'):
    results = graph.run(query)
with CodeTimer('py2neo: .data()', unit='s'):
    results.data()

# test with driver
with driver.session() as s:
    with CodeTimer('driver: get result', unit='s'):
        result = s.run(query)
    with CodeTimer('driver: Iterate over list of results', unit='s'):
        for x in result:
            pass
```

Output for py2neo 2021.0.0 vs neo4j 4.2:

```
Code block 'py2neo: get result' took: 5.75310 s
Code block 'py2neo: Iterate over list of results' took: 10.05772 s
Code block 'py2neo: get result' took: 5.87161 s
Code block 'py2neo: .to_data_frame()' took: 19.74684 s
Code block 'py2neo: get result' took: 6.83446 s
Code block 'py2neo: .data()' took: 16.77510 s
Code block 'driver: get result' took: 0.01966 s
Code block 'driver: Iterate over list of results' took: 12.71221 s
```

**Comment by technige** [comment]
Refactoring further, I've reduced the times again. Now I'm down to:
```
Code block 'Iterate over list of results' took: 3.72923 s
Code block '.to_data_frame()' took: 7.69288 s
Code block '.data()' took: 7.39891 s
```

In terms of the official driver, both code was written at different times with slightly different aims in mind. There is some structural difference for py2neo as it tries to maintain a similar interface for both Bolt and HTTP.

However, the differences above came from reducing the amount of work done when hydrating records, in particular avoiding looping over the same values multiple times.

I think there may be further improvements possible, but these will require some more extensive refactoring. I'll keep that as a job for some point in the future. In the meantime, the improvements above will be included in the next release.

**Comment by technige** [comment]
After more playing around this weekend, my best run now looks like this:
```
Code block 'Iterate over list of results' took: 0.96482 s
Code block '.to_data_frame()' took: 4.29333 s
Code block '.data()' took: 3.89576 s
```

Therefore I'm going to consider this issued now closed :)
