### ISSUE TITLE
how to get json like "Export to Json" in the Neo4j Brower

### ISSUE THREAD

**Issue by lancexiang** [technige/py2neo#881]
How to implement this operation in py2neo? Thanks.
![image](https://user-images.githubusercontent.com/22250092/109908608-8c665500-7cdf-11eb-8ed4-d3433ca1b882.png)

**Comment by technige** [comment]
This is a feature of the Neo4j browser, not of Cypher itself. I assume the values are converted in some form into JSON. You would have to do that manually with py2neo.
