### ISSUE TITLE
OGM Relationship with property

### ISSUE THREAD

**Issue by dov84d** [technige/py2neo#882]
Hi,
I would like to build a Relationship with property
Is py2neo support it? and how?

Thanks!

For example:

class Movie(GraphObject):
    __primarykey__ = "title"

    title = Property()
    tagline = Property()
    released = Property()

    actors = RelatedFrom("Person", "ACTED_IN")
    directors = RelatedFrom("Person", "DIRECTED")
    producers = RelatedFrom("Person", "PRODUCED")

class Person(GraphObject):
    __primarykey__ = "name"

    name = Property()
    born = Property()

    acted_in = RelatedTo(Movie)
    **reviewed = Reviewed(Movie)**

class Reviewed(RelatedTo):

    rating = Property()
    def __init__(self, rating):
        self.rating = rating

**Comment by iamliamc** [comment]
I think you are looking for this: 
https://py2neo.org/2021.0/ogm/index.html#py2neo.ogm.RelatedObjects.add

```
class Register(Model):
    __primarylabel__ = "Register"
    __primarykey__ = "uuid"

    uuid = Property()
    point_id = Property()
    brick_class = Property()
```
  
```
class HeatingCurve(Model):
    __primarylabel__ = "HeatingCurve"
    __primarykey__ = "uuid"

    name = Property()
    point_id = Property()
    uuid = Property()
    X1 = RelatedFrom("Register", "X1")
    X2 = RelatedFrom("Register", "X2")
    Y1 = RelatedFrom("Register", "Y1")
    Y2 = RelatedFrom("Register", "Y2")
    supply_temp = RelatedFrom("Register", "IS_SUPPLY_TEMP")
    calculated_supply_temp = RelatedFrom("Register", "IS_CALC_SUPPLY_TEMP")
    outside_temp = RelatedFrom("Register", "IS_OAT")
    minimum = RelatedFrom("Register", "IS_MIN")
    maximum = RelatedFrom("Register", "IS_MAX")
```

```
<HeatingCurve uuid='33937616-7ccd-49bf-943c-c8c406f2f5c9'>
hc.maximum
<py2neo.ogm.RelatedObjects object at 0x7f20d5bb16d0>
max = Register.match(self.graph).where(point_id=new_entity.maximum.point_id).first()
hc.maximum.add(max, brick_type="isPointOf")
```

![image](https://user-images.githubusercontent.com/5678517/110824084-b7612380-8260-11eb-9590-8bf63a406740.png)

**Comment by dov84d** [comment]
Hi,
Thank you for your answer,
Yes, but I would like to use set the related object property with a class, as the node properties. 
Is there any way?

Best,
Dov

In your example:

class Register(Model):
    __primarylabel__ = "Register"
    __primarykey__ = "uuid"

    uuid = Property()
    point_id = Property()
    brick_class = Property()

class HeatingCurve(Model):
    __primarylabel__ = "HeatingCurve"
    __primarykey__ = "uuid"

    name = Property()
    point_id = Property()
    uuid = Property()
    X1 = RelatedFrom("Register", "X1")
    X2 = RelatedFrom("Register", "X2")
    Y1 = RelatedFrom("Register", "Y1")
    Y2 = RelatedFrom("Register", "Y2")
    supply_temp = RelatedFrom("Register", "IS_SUPPLY_TEMP")
    calculated_supply_temp = RelatedFrom("Register", "IS_CALC_SUPPLY_TEMP")
    outside_temp = RelatedFrom("Register", "IS_OAT")
    minimum = RelatedFrom("Register", "IS_MIN")
    maximum = RelatedFrom("Register", "IS_MAX")

class IS_MAX(RelatedTo):

         brick_type = Property()
          def __init__(self, brick_type):
              self.brick_type = brick_type

"""<HeatingCurve uuid='33937616-7ccd-49bf-943c-c8c406f2f5c9'>
hc.maximum
<py2neo.ogm.RelatedObjects object at 0x7f20d5bb16d0>
max = Register.match(self.graph).where(point_id=new_entity.maximum.point_id).first()
hc.maximum.add(max, IS_MAX(brick_type="isPointOf"))"""

**Comment by iamliamc** [comment]
https://py2neo.org/2021.0/data/index.html?highlight=relationship#py2neo.data.Relationship

I think if you extend the class `Relationship` and then replace it on the model it might work not sure. 

```
class IS_MAX(Relationship):
    def __init__(self, brick_type):
        self["brick_type"] = brick_type
```

The relationship object already takes property key words so the `__init__` might be unnecessary... 

The thing is in the above I am adding a Register object to the `RelatedObject` of `HeatingCurve`

https://py2neo.org/2021.0/ogm/index.html?highlight=relatedobject#py2neo.ogm.RelatedObjects

Therefore if we make a Relationship class... we would have to add it a different way (cause you add Nodes not Relationships) to the RelatedObject

I'd have to look... not sure what upside you are looking for with this specific kind of implementation

**Comment by dov84d** [comment]
Thank you,

The upside is to manage relationships properties in an object oriented way, the same as I add a properties to a Model/GraphObject, which is more convenient and type based, and not as untracked keys and values.
I hope it's more clear (-:

I guess there is no way to build subclasses of relationship objects and get that object from a matcher.
If you find something please let me know.



Thanks again!

**Comment by iamliamc** [comment]
This does work: 

```
class IS_MAX(Relationship):
    def __init__(self, *args, brick_type, **kwargs):
        super().__init__(*args, **kwargs)
        self["brick_type"] = brick_type
```

It's a bit ugly cause the class `IS_MAX` can't take the Model objects proper so you have to pass in the underlying node: 

````
max = Register.match(self.graph).where(point_id=new_entity.maximum.point_id).first()
hc = HeatingCurve.match(self.graph, '065cec5c-20c1-4c22-9c9b-81406ac08060').first()
n_m = IS_MAX(max.__node__, hc.__node__, brick_type="isPointOf")
self.graph.create(n_m)
[x for x in hc.maximum]
[<Register uuid='ebddde31-57c2-4048-ad28-f8f82a713052'>]
max.uuid
'ebddde31-57c2-4048-ad28-f8f82a713052'
```

**Comment by dov84d** [comment]
Great thanks,

Maybe ugly but that whats I ment basically.
But now can I add some functionality for the class?

Let's say:

class IS_MAX(Relationship):
    def __init__(self, *args, brick_type, **kwargs):
        super().__init__(*args, **kwargs)
        self["brick_type"] = brick_type
    
    def print_brick_type:
          print(self["brick_type"] )

And then search for it and get the IS_MAX type and use it's functions?

This is actually basic uses and functionality of ORM in any other system, and here it works well for the Model (node) object but for the Relationship we should do some hacks.

Best,
Dov

**Comment by iamliamc** [comment]
It's all there I think...
```
class IS_MAX(Relationship):
    def __init__(self, *args, brick_type, **kwargs):
        super().__init__(*args, **kwargs)
        self["brick_type"] = brick_type

    def say_hi(self):
        print(self["brick_type"])
```


```
>>> from building_topology.adapters.secondary.persistance_graphql.models.heating_curve import IS_MAX
>>> x = self.graph.match(r_type=IS_MAX).all()
>>> x
[IS_MAX(Node('Max_Discharge_Air_Temperature_Setpoint_Limit', 'Register', brick_class='Max Discharge Air Temperature Setpoint Limit', point_id='KRSD8ADM.Air Distribution.AHU.SAT Y Max (stooklijn)', uuid='ebddde31-57c2-4048-ad28-f8f82a713052'), Node('Heating_Curve', point_id='KRSD8ADM.Air Distribution.AHU', uuid='08633a0a-953f-4477-96f9-9fd42c16dfbf'), brick_type='isPointOf')]
>>> x[0].say_hi()
isPointOf
```

**Comment by dov84d** [comment]
Looks good,
I will try it,

Thanks!
