### ISSUE TITLE
Error in routing mode: "TypeError: 'RoutingTable' object is not iterable"

### ISSUE THREAD

**Issue by meseta** [technige/py2neo#889]
I'm trying out the experimental routing support with Graph(..., routing=True), with the following error

```
  File "/root/.local/share/virtualenvs/workdir-tL8tMG2Q/lib/python3.9/site-packages/py2neo/client/__init__.py", line 990, in _refresh_routing_table
    old.update(profile for profile in rt if profile not in routing_table)
TypeError: 'RoutingTable' object is not iterable
```

Using py2neo 2021.0.1, with Neo4j enterprise causal cluster 4.2.2 deployed with helm charts, connecting to a core cluster using:
```py
Graph(
    ConnectionProfile(host=host),
    auth=(neo4j_username, neo4j_password),
    routing=True,
)
````
where `host` is is a plain domain name without scheme, e.g. `neo4j.namespace`

**Comment by technige** [comment]
Thanks for highlighting this. I'm currently working on maturing the routing support, and have just checked the latest code - that particular problem should disappear in the new release.

**Comment by technige** [comment]
@meseta Please have another try with the latest release. This should now be fixed.

Note also the new `ServiceProfile` class which extends `ConnectionProfile` with a `routing` attribute:
https://py2neo.org/2021.1/profiles.html#py2neo.ServiceProfile
