### ISSUE TITLE
Changelog for new releases

### ISSUE THREAD

**Issue by icfly2** [technige/py2neo#890]
I know they are a pain to create, but I haven't been able to find a changelog for the releases of py2neo. Are there any? If so, would it be able to create one for the next release?

**Comment by technige** [comment]
There haven't been, although you chose the right point at which to ask, as there is now one for 2021.1:
https://py2neo.org/2021.1/release-notes.html#version-2021-1

I can't guarantee being able to publish one of these with every release, but will try to make sure all the major stuff is listed.
