### ISSUE TITLE
Unable to connect DB with latest py2neo (2021.0.0)

### ISSUE THREAD

**Issue by krdpk17** [technige/py2neo#892]
Issue: My code which was working with py2neo(2020.0.0) broke with py2neo(2021.0.0)

**Code**: Full code can be found at https://github.com/krdpk17/twitter-neo4j/blob/master/docker/features/libs/cypher_store.py
def get_graph():
    
    global NEO4J_URL,NEO4J_HOST,NEO4J_PORT,NEO4J_AUTH
    pdb.set_trace()
    #test()

    # Connect to graph
    creds = NEO4J_AUTH.split('/')
    #TODO: Enable cert verify after fix
    graph = Graph(user=creds[0], password=creds[1], host=NEO4J_HOST, port=NEO4J_BOLT_PORT, secure=NEO4J_BOLT_SECURE, verify=False)
    graph.run('match (t:Tweet) return COUNT(t)')
    return graph

**pip** output for not working case
$ pip freeze | grep py2neo
py2neo==2021.0.1

**pip** output for  working case
$ pip freeze | grep py2neo
py2neo==2020.0.0

**Workaround:**
Reverted my library to working version

Please let me know for any more info

**Comment by technige** [comment]
"Broke" isn't specific enough. What was the error?

**Comment by technige** [comment]
Closing issue due to lack of detail in problem description.
