### ISSUE TITLE
Hyperlink nodes

### ISSUE THREAD

**Issue by YojanaGadiya** [technige/py2neo#894]
Dear all,

I am interested in knowing if there is a possibility to create a clickable node? For example, if I have a node with an email address, would it be possible to create a node that has a clicking function to open an email browser or something?

Thank You.

**Comment by technige** [comment]
I don't understand the issue. Are you sure you have raised this against the right project?

**Comment by YojanaGadiya** [comment]
> I don't understand the issue. Are you sure you have raised this against the right project?

Yes. So I have a node with an email address. I wanted to know if there is a possibility through py2neo of creating a hyperlink on this email address such that when an individual clicks the node, it opens up a dialog box for sending the mail to the respective email id.

**Comment by technige** [comment]
Clicks on the node where? Py2neo is a connectivity library - it doesn't have a GUI.

**Comment by YojanaGadiya** [comment]
So with Py2neo one could create a node in Neo4J. When visualizing into Neo4J, is there a possibility to add hyperlinks with respect to the node displayed? If yes, is there anything that can be done by Py2neo or would it be the environmental settign for Neo4J?

**Comment by technige** [comment]
If you mean the Neo4j browser, then I don't think there is any way to do that. But that would be a question for the browser team at Neo. This is, though, completely unrelated to py2neo functionality.

**Comment by YojanaGadiya** [comment]
Okay. Sorry. Closing the issue.
