### ISSUE TITLE
FileNotFoundError:[Error 2]No such file or directory:'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI76962\\py2neo\\VERSION'

### ISSUE THREAD

**Issue by daobuxuxing** [technige/py2neo#895]
FileNotFoundError:[Error 2]No such file or directory:'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI76962\\py2neo\\VERSION'
py2neo:2021.1.1
os:WIN7

**Comment by daobuxuxing** [comment]
import os
os.environ.setdefault("READTHEDOCS_PROJECT", "py2neo")
os.environ.setdefault("READTHEDOCS_VERSION", "latest")

**Comment by daobuxuxing** [comment]
Traceback(most recent call last):
Flie"movie_storage.py"line4, in <module>
File"<frozen importlib.__bootstrap>", line 991, in _find and _load
File"<frozen importlib.__bootstrap>", line 975, in _find and _load_unlocked
File"<frozen importlib.__bootstrap>", line671, in _load_unlocked
File"py2neo\__init__.py", line 83, in <module>
File"py2neo\meta.py", line 130, in get_metadata
File"py2neo\meta.py", line121, in get_version_data
FileNotFoundError:[Error 2]No such file or directory:'C:\Users\ADMINI~1\AppData\Local\Temp\_MEI76962\py2neo\VERSION'
[5116]Failed to execute script movie_storage

**Comment by daobuxuxing** [comment]
with py2neo version 4.3
can execute script succefully.

**Comment by technige** [comment]
Please do not just dump an error message as an issue. This is useless information without context. Issues need to have a basic description of the problem as well as some detail of what actions were being carried out.

**Comment by daobuxuxing** [comment]
thank you, Py2neo is wondwrful, It help me edit 2 applications, when I use Pyinstaller meet the error.                    yours:王昌文-------- 原始邮件 --------发件人： Nigel Small ***@***.***>日期： 2021年5月10日周一 下午3:31收件人： technige/py2neo ***@***.***>抄送： wang changwen ***@***.***>, State change ***@***.***>主    题： Re: [technige/py2neo] FileNotFoundError:[Error 2]No such file or directory:'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI76962\\py2neo\\VERSION' (#895)
Please do not just dump an error message as an issue. This is useless information without context. Issues need to have a basic description of the problem as well as some detail of what actions were being carried out.
